### ISSUE TITLE
Autofocus warning on navigation

### ISSUE THREAD

**Issue by marispro** [hotwired/turbo#100]
When navigating to page which contains form with "autofocus" text field, getting warning in console:
`Autofocus processing was blocked because a document already has a focused element.`
Meanwhile autofocus works as expected.
Is there any workaround to remove this ?

Browser: Latest Chrome
PS: Firefox and Safari - no warning

**Comment by tleish** [comment]
Is the turbo library adding `autofocus` to your fields?

**Comment by marispro** [comment]
> Is the turbo library adding `autofocus` to your fields?

No, I think it shouldn't. It just loads a page which have one field with autofocus.

**Comment by tleish** [comment]
This is a Chrome specific issue.  If you google it, you can find post of others discussing it with other libraries, although I haven't seen a solution yet.

I suggest closing this ticket as it has nothing to do with turbo.

**Comment by marispro** [comment]
Ok no problem with that.
We just can keep on eye on that issue in future.
