### ISSUE TITLE
data-turbo-permanent for cross-site / different subdomains

### ISSUE THREAD

**Issue by danielnc** [hotwired/turbo#1001]
I have one element on my page that I want the state to be persisted across requests, it works fine UNLESS one of the links changes subdomains, the element is the same across different pages, but wondering if there is a way to force a snapshot cache across subdomains.

from a stimulus controller I do something like this:

```js
const snapshot = Turbo.navigator.view.snapshot.constructor.fromElement(
  this.element
);

Turbo.navigator.view.snapshotCache.put(window.location, snapshot);
```

It works fine unless there is some subdomain changes, and I am not sure what I am missing or if this is supported at all

**Comment by afcapel** [comment]
This is not supported. Turbo only works within the same [origin](https://developer.mozilla.org/en-US/docs/Glossary/Origin), it relies on [`History.pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) which requires the URLs to be in the same origin.
