### ISSUE TITLE
Permanent elements are not always preserved

### ISSUE THREAD

**Issue by stgm** [hotwired/turbo#101]
Related to #80 

**Actual problem**

Permanent elements are not always preserved because in certain circumstances the "previous page" is cached in a state where permanent elements have been replaced by meta tags. This means that when browsing "back", the incorrectly cached page is reinstated, and the incorrectly cached meta tags aren't replaced by the current contents of their associated permanent elements.

**Circumstances**

For me this **only** happens in Safari when I navigate towards a page containing a Youtube embed. It doesn't happen when I navigate to a very similar page that doesn't have such an embed. It is also completely consistent, so it always happens.

**What does the log say**

`View.cacheSnapshot()` is responsible for cloning the DOM of the old page. In general circumstances, the line making the clone executes at the very end of the page navigation sequence, right after `Visit.loadResponse()` is completely done.

With the Youtube embed present, the cloning code from `View.cacheSnapshot()` is executed much earlier, right when the new body is assigned: `assignNewBody()` -> `replaceElementWithElement()` -> `parentElement.replaceChild()` (and before `replaceElementWithElement()` returns).

**What does the debugger say**

Unfortunately, not much. When stepping into the `parentElement.replaceChild()` call, execution immediately jumps to the cloning part of `View.cacheSnapshot()`.

Also, no Youtube JS is encountered in the debugger until after Turbo finishes the page transition.

Interestingly, if the new page itself contains a `script` tag, it will be executed right after the `parentElement.replaceChild()` call. This does not affect in any way the moment that the cloning code is run: that still depends only on the presence of the Youtube embed.

**await vs setTimeout**

The old page DOM is supposed to be cached _after rendering_ the new page because this speeds up presenting the new page. This is effected by splitting off the cloning code as a new task using `await`. Previously, this was done using `setTimeout()`.

As it happens, putting back `setTimeout()` does indeed ensure that the cloning always happens at the end of the navigation sequence.

**Conclusion**

For some reason, it seems that calling `replaceChild()` for the body, when the new body contains a Youtube embed, yields control to queued code.

Is this the Micro task queue vs the normal task queue? But why would it be triggered by the Youtube embed and not generally?

I would appreciate if anyone has any pointers on how to debug this further!

**Comment by stgm** [comment]
Additional note: Firefox doesn't exhibit this behaviour.

**Comment by stgm** [comment]
Minimal problematic example is here:
https://stgm.github.io/permanent-element-bug/

- Click on **Go to page with video** and navigate back: permanent element disappears.
- Click on **Go to page without video** and navigate back: permanent element still there.

**Comment by sstephenson** [comment]
Would you mind testing v7.0.0-beta.4 to see if the issue has been fixed?

**Comment by stgm** [comment]
Yes! It all works in my local app, and the example linked above is now also A-OK 👌

Thanks for all the great work!

**Comment by stgm** [comment]
Oh, I forgot to mention: I _think_ it was already corrected before [yesterday's change](https://github.com/hotwired/turbo/commit/669ae289877eefd796085f460c3b3812fd43bd32), but I had only been able to verify one particular example. If this extra change has any performance implications or otherwise, it may be worth reconsidering—I would be happy to do some testing.

**Comment by sstephenson** [comment]
Wonderful! Thanks for checking 👍
