### ISSUE TITLE
Working with local data - Turbo.visit(htmlGeneratingFn)!?

### ISSUE THREAD

**Issue by ajaishankar** [hotwired/turbo#1020]
Hi

Was researching what would be best practice for implementing a dynamic dropdown.

For example, a states dropdown depends on selected country. Really dig the "fetching remote data" approach mentioned here.

https://github.com/thoughtbot/hotwire-example-template/tree/hotwire-example-dynamic-form-fields#fetching-remote-data-with-javascript

But when all the data is available locally, then I think the usual approach is to resort to Javascript, DOM manipulation etc.

**But what if we could make the local data fetch and remote data fetch transparent?**

That is `Turbo.visit` could accept a function that returns html (similar to what a remote url would do)

```js
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
   onCountryChange(e) {
     Turbo.visit(() => "<select name="states">...</select>", { frame: "states" } )
   }
}
```
Feel this would keep Javascript logic in Stimulus controllers minimal.

Thanks

Ajai

**Comment by seanpdoyle** [comment]
If you're targeting a known frame, could you set the [innerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) property directly?

```javascript
const frame = document.getElementById("states")

frame.innerHTML = `<select name="states">...</select>`
```

**Comment by ajaishankar** [comment]
Doh!

Yes that would work 😄  had the following questions:

1. Just by setting the innerHtml would any Turbo related events fire
2. Will Stimulus controllers that are attached to the states frame get disconnected/reconnected etc.

**Comment by seanpdoyle** [comment]
> Doh!
> 
> Yes that would work 😄 had the following questions:
> 
> 1. Just by setting the innerHtml would any Turbo related events fire
> 2. Will Stimulus controllers that are attached to the states frame get disconnected/reconnected etc.

1. No. Which events would you be depending on?
2. Thanks to how they're powered by `MutationObserver`, they should!
