### ISSUE TITLE
Concurrent lazy loaded frames not replacing DOM reliably

### ISSUE THREAD

**Issue by joergd** [hotwired/turbo#103]

**Comment by dhh** [comment]
Need more detail.

**Comment by joergd** [comment]
I have two lazily loaded turbo-frames.

Both frames return with a response within a few miliseconds of each other (almost simultaneously). Sometimes both frames render, but more often only one of them will render.

For now, in my actions I need to put in

`sleep rand`

This will reliably render both frames.

**Comment by joergd** [comment]
Sorry - scrap this (egg on my face).

It has to do with the charting library I am using (chartkick) which perhaps isn't working so well with lazy loaded turbo frames at this stage.

I will investigate further.
