### ISSUE TITLE
Sending non-Turbo Stream data over a websocket results in Turbo appending it to the DOM

### ISSUE THREAD

**Issue by joelmichael** [hotwired/turbo#1043]
I like Turbo, and I'm not entirely sure if this is desired behavior or not. I wanted to be able to send a non-Turbo Stream message over my websocket connection; specifically, the word "ping". This would happen every second and test to see if my receivers were still active and receiving messages. It wouldn't do any DOM adjustments, or have any other effect besides giving me a more accurate receiver count by triggering the drop of inactive receivers.

To my surprise, the word "ping" started filling up my DOM. It appeared after the `</body>` and before the `</html>`. Despite this strange location, it does cause a display issue, filling the bottom of the page with text.

I couldn't fathom why this was happening, and tried disabling the `Turbo.connectStreamSource` command. Sure enough it went away. It seems that Turbo Stream doesn't just listen for `<turbo-stream>` tags, it wants ALL data on the socket to be Turbo Stream data. I conclude it's trying to append this string to the end of the page as a sort of default Turbo Stream behavior.

I even tried replacing the "ping" with a semi-relevant rendering of Turbo Stream HTML, but I'd prefer not to do unnecessary DOM updates. Have I misdiagnosed this problem, or is there a way I can get around it?

**Comment by dhh** [comment]
What's the mechanism by which you do anything with that ping? You have some client side code that grabs that ping? Either way, the stream source is indeed intended to be exclusive to Turbo. Not meant for sharing.

**Comment by joelmichael** [comment]
I have some Rust code for the websocket on the backend that loops waiting for a tokio broadcast receiver to receive a message:
```rust
        while let Ok(msg) = receiver.recv().await {
            if socket.send(Message::Text(msg)).await.is_err() {
                break; // client disconnect
            }
        }
```
It might be a peculiarity of this implementation, but I'm not sure of a way to terminate the receiver loop short of sending a message that fails due to client disconnect. The ping felt like an acceptable solution because it would force an error and drop the receiver. Otherwise, the receiver could sit there waiting for a message and appear open despite a user having closed the websocket (by closing their browser tab).

I appreciate you explaining that this is the intended behavior of Turbo Stream and I'll see if I can find another solution. I do want to keep using Turbo so there's probably another angle. Also, it's an honor to receive a reply from DHH! Thanks.
