### ISSUE TITLE
How to run browser tests on local machine?

### ISSUE THREAD

**Issue by michelson** [hotwired/turbo#1045]
I'm trying to run specs on my local env, and the browser specs are failing; I'm still trying to figure out why. I see them retrying. I'm my fork; however, they run fine in the GitHub actions. Is there some extra procedure that should be run before running the tests?

![Screen Shot 2023-10-24 at 12 31 49 PM](https://github.com/hotwired/turbo/assets/11976/b38b7dcf-fc63-49b7-bebb-6cd47606f3f7)

ref: https://github.com/hotwired/turbo/pull/1042

**Comment by afcapel** [comment]
Did you run `yarn install && yarn playwright install --with-deps`? After that `yarn test:browser` should work.

How to run test is documented [here](https://github.com/hotwired/turbo/blob/main/CONTRIBUTING.md#testing).

Hopefully that will help, but feel free to reopen the issue if now.

**Comment by michelson** [comment]
Yes, unfortunately, I had already installed the dependencies and ran the tests with: `yarn test: browser --project=chrome.` I am trying to understand why I have all tests failing, but in GitHub actions they are running fine.
