### ISSUE TITLE
Promoted Frame Visits cause `tracked_element_mismatch` reloads

### ISSUE THREAD

**Issue by domchristie** [hotwired/turbo#1047]
This only impacts `main` branch builds since https://github.com/hotwired/turbo/pull/887.

When promoting Frame Visits using `data-turbo-action="…"`, Turbo will reload the page. The `turbo:reload` event reason is: `tracked_element_mismatch`. This only appears to be an issue since: #887 

/cc @seanpdoyle

**Comment by domchristie** [comment]
@afcapel I think this is quite a major issue, since it breaks all Turbo Frames visits with a data-turbo-action. Would be good to get fixed before v8 is released

**Comment by afcapel** [comment]
Agreed, let's get it fixed before v8 👍

**Comment by qinmingyuan** [comment]
Any progress for this issue?

**Comment by seanpdoyle** [comment]
@domchristie I'm unable to reproduce this locally in the following test:

```js
test("navigating turbo-frame[data-turbo-action=advance] from within pushes URL state", async ({ page }) => {                                                                                                        
  await page.click("#add-turbo-action-to-frame")                                                                                                                                                                    
  await page.click("#link-frame")                                                                                                                                                                                   
  await nextEventNamed(page, "turbo:frame-load")                                                                                                                                                                    
  await noNextEventNamed(page, "turbo:reload")                                                                                                                                                                      
  await nextEventNamed(page, "turbo:load")                                                                                                                                                                          
  await noNextEventNamed(page, "turbo:reload")                                                                                                                                                                      
                                                                                                                                                                                                                    
  const title = await page.textContent("h1")                                                                                                                                                                        
  const frameTitle = await page.textContent("#frame h2")                                                  
                                                                                                                                                                                                                    
  assert.equal(title, "Frames")                                                                           
  assert.equal(frameTitle, "Frame: Loaded")                                                                                                                                                                         
  assert.equal(pathname(page.url()), "/src/tests/fixtures/frames/frame.html")                                                                                                                                       
})   
```

I've added some assertions related to `turbo:reload`:

```diff
diff --git a/src/tests/functional/frame_tests.js b/src/tests/functional/frame_tests.js
index b090aff..a796e44 100644
--- a/src/tests/functional/frame_tests.js
+++ b/src/tests/functional/frame_tests.js
@@ -642,7 +642,10 @@ test("navigating a frame with a form[method=get] that does not redirect still up
 test("navigating turbo-frame[data-turbo-action=advance] from within pushes URL state", async ({ page }) => {
   await page.click("#add-turbo-action-to-frame")
   await page.click("#link-frame")
+  await nextEventNamed(page, "turbo:frame-load")
+  await noNextEventNamed(page, "turbo:reload")
   await nextEventNamed(page, "turbo:load")
+  await noNextEventNamed(page, "turbo:reload")
 
   const title = await page.textContent("h1")
   const frameTitle = await page.textContent("#frame h2")
```

Does this reflect the type of scenario you're encountering?

If you're able to cut a branch or open a pull request that reproduced the issue, I'm happy to take it over and explore solutions.

**Comment by afcapel** [comment]
@qinmingyuan thanks for the failing test, that's very useful. No need for a rails app, we should fix this within Turbo.

**Comment by domchristie** [comment]
@seanpdoyle https://github.com/domchristie/turbo_promoted_frame_visit_test

It appears to only impact turbo-rails setups. I tried a minimal demo, serving plain html files (where the frame visit response included a minimal layout to mimic the turbo-rails behaviour), and it worked.

**Comment by seanpdoyle** [comment]
@domchristie I wonder if it's related to a mostly, or completely) empty `<head>` element coming from `turbo-rails`:

https://github.com/hotwired/turbo-rails/blob/4eb4e928e30be8cd537af8073f98b80ddea4a578/app/views/layouts/turbo_rails/frame.html.erb#L2-L4

```erb
  <head>
    <%= yield :head %>
  </head>
```

If I copy the application layout, it behaves as expected:

```sh
~/Work/domchristie/turbo_promoted_frame_visit_test main*
❯ mkdir -p app/views/layouts/turbo_rails 

~/Work/domchristie/turbo_promoted_frame_visit_test main*
❯ cp app/views/layouts/application.html.erb app/views/layouts/turbo_rails/frame.html.erb
```

**Comment by qinmingyuan** [comment]
> @domchristie I wonder if it's related to a mostly (or completely) empty `<head>` element coming from `turbo-rails`:
> 
> https://github.com/hotwired/turbo-rails/blob/4eb4e928e30be8cd537af8073f98b80ddea4a578/app/views/layouts/turbo_rails/frame.html.erb#L2-L4
> 
> ```
>   <head>
>     <%= yield :head %>
>   </head>
> ```
> 
> If I copy the application layout, it behaves as expected:
> 
> ```shell
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ mkdir -p app/views/layouts/turbo_rails 
> 
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ cp app/views/layouts/application.html.erb app/views/layouts/turbo_rails/frame.html.erb
> ```
> 
> > where the frame visit response included a minimal layout to mimic the turbo-rails behaviour
> 
> Could you share that code? I wonder what about the Rails setup is different.

My header is nothings in header, but also the same issue:
```ruby
<html>
  <head></head>
  <body>
    <turbo-frame id="body">
      <%= yield %>
    </turbo-frame>
  </body>
</html>
```

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo-rails/pull/534 to re-propose responding to Turbo Frame requests with full documents.

**Comment by qinmingyuan** [comment]
Understood, thanks. Maybe have a better resolution.

**Comment by seanpdoyle** [comment]
@domchristie thank you! Are you saying that despite the fact that the [`<head>` element](https://gist.github.com/domchristie/d143a6e7ae1807bd1f8323ecc8a4978b#file-about-html-L2-L3) is empty, that gist works as expected, whereas https://github.com/domchristie/turbo_promoted_frame_visit_test reloads as a mismatch?

**Comment by domchristie** [comment]
@seanpdoyle yes, exactly

**Comment by seanpdoyle** [comment]
@domchristie is there unexpected behavior if you make this change?

```diff
-  <script src="https://unpkg.com/@hotwired/turbo@8.0.0-beta.1/dist/turbo.es2017-umd.js"></script>
+  <script src="https://unpkg.com/@hotwired/turbo-rails@8.0.0-beta.1/app/assets/javascripts/turbo.js"></script>
```

I wonder if the issue stems from the Rails side, or the `turbo-rails` side.

**Comment by weizheheng** [comment]
> @domchristie I wonder if it's related to a mostly (or completely) empty `<head>` element coming from `turbo-rails`:
> 
> https://github.com/hotwired/turbo-rails/blob/4eb4e928e30be8cd537af8073f98b80ddea4a578/app/views/layouts/turbo_rails/frame.html.erb#L2-L4
> 
> ```
>   <head>
>     <%= yield :head %>
>   </head>
> ```
> 
> If I copy the application layout, it behaves as expected:
> 
> ```shell
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ mkdir -p app/views/layouts/turbo_rails 
> 
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ cp app/views/layouts/application.html.erb app/views/layouts/turbo_rails/frame.html.erb
> ```
> 
> > where the frame visit response included a minimal layout to mimic the turbo-rails behaviour
> 
> Could you share that code? I wonder what about the Rails setup is different.

Chipping in here, I am having the same issue where Turbo reloads when promoting Frame Visits using data-turbo-action="…". Copying the application layout to `app/views/layouts/turbo_rails` does stop the unexpected reloading.

**Comment by weizheheng** [comment]
> @domchristie I wonder if it's related to a mostly (or completely) empty `<head>` element coming from `turbo-rails`:
> 
> https://github.com/hotwired/turbo-rails/blob/4eb4e928e30be8cd537af8073f98b80ddea4a578/app/views/layouts/turbo_rails/frame.html.erb#L2-L4
> 
> ```
>   <head>
>     <%= yield :head %>
>   </head>
> ```
> 
> If I copy the application layout, it behaves as expected:
> 
> ```shell
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ mkdir -p app/views/layouts/turbo_rails 
> 
> ~/Work/domchristie/turbo_promoted_frame_visit_test main*
> ❯ cp app/views/layouts/application.html.erb app/views/layouts/turbo_rails/frame.html.erb
> ```
> 
> > where the frame visit response included a minimal layout to mimic the turbo-rails behaviour
> 
> Could you share that code? I wonder what about the Rails setup is different.

Chipping in here, I am having the same issues where Turbo reloads when promoting Frame Visits using data-turbo-action="…".

Copying the `<head></head>` from the layout to `turbo_rails/frame.html.erb` does stops Turbo from unexpected reloading.

**Comment by domchristie** [comment]
> It appears to only impact turbo-rails setups. I tried a minimal demo, serving plain html files (where the frame visit response included a minimal layout to mimic the turbo-rails behaviour), and it worked.
> https://github.com/hotwired/turbo/issues/1047#issuecomment-1834632507

This is not correct. The minimal demo did not have `data-turbo-track="reload"`. Adding that, and we see the same behaviour.

**Comment by domchristie** [comment]
@seanpdoyle [the minimal repro gist](https://gist.github.com/domchristie/d143a6e7ae1807bd1f8323ecc8a4978b) has been updated to demonstrate the issue when `data-turbo-track="reload"` is present

**Comment by seanpdoyle** [comment]
@afcapel @jorgemanrubia I've encountered this today, and like @domchristie mentioned in https://github.com/hotwired/turbo/issues/1047#issuecomment-1825113897, it's a major impediment to upgrading.

I'm not sure about how to resolve it. Like I mentioned in https://github.com/hotwired/turbo/issues/1047#issuecomment-1835358502, I've opened https://github.com/hotwired/turbo-rails/pull/534. I've also opened https://github.com/hotwired/turbo/pull/694 to send the `Turbo-Action:` header when it's present in the requesting context. Turbo Rails could render the full document when both `Turbo-Frame:` and `Turbo-Action:` are present.

I think https://github.com/hotwired/turbo/pull/694 (even without the `Turbo-Action:` header) fits into the Morph-centric mental model: the server renders full HTML documents, then the client decides how to negotiate that new content into the document.

**Comment by domchristie** [comment]
Part of me wonders whether we revise our approach to how we update the history in frame navigations?

We currently start a non-rendering Visit if the frame navigation has an action (added here: https://github.com/hotwired/turbo/pull/398/files#diff-8f44fafd854f6f716d51a2b05b5689266a9b66e0b1ad9d68570bd4e8cefd0a47R269)

This triggers a Visit lifecycle (including checking for tracked assets). To me a `Visit` is more of a "`PageVisit`", so I'm wondering if there's another way we could compose this behaviour?

**Comment by afcapel** [comment]
This is caused because we're sending the `Turbo-Frame` header in promoted Turbo frame requests, that are intended for full page replacements. Frame navigations that are promoted with `[data-turbo-target=_top]` already don't include this header. I think navigations promoted with `[data-turbo-action]` should do the same.

PR in https://github.com/hotwired/turbo/issues/1047
