### ISSUE TITLE
Access snapshot cache 

### ISSUE THREAD

**Issue by vitobotta** [hotwired/turbo#105]
Hi! With Turbolinks I was using a little trick to prefetch pages on mouseover (so to make perceived responsiveness better for the user). So on mouseover the page is fetched and added to Turbolinks's cache. However some methods seem to have been removed from Turbo and I cannot find a way to access has/put methods on the snapshot cache from the Turbo object. Any workaround? From my experience prefetching pages really makes a big difference in UX, especially together with Turbo/Turbolinks. Thanks!

**Comment by DmitryBochkarev** [comment]
I think you can do this by accessing `Turbo.navigator.view.snapshotCache.{get,put}` Passing [Snapshot](https://github.com/hotwired/turbo/blob/c52d87c9426ebbbb735e9e8947b3cbdfde8a2a10/src/core/drive/snapshot.ts#L4) instance to `put` method.

**Comment by vitobotta** [comment]
Thanks @DmitryBochkarev, I should have checked objects more in depth in the hierarchy. In the meantime I solved in another way without using Turbo's cache but will try your suggestion to see if it works better. Thanks!

**Comment by vwong** [comment]
Keen to see how you solved it though. I'm sure lots of people (like me) are interested in the solution.

**Comment by vitobotta** [comment]
@vwong I borrowed code from instantpage.js and simplified it a bit with a couple of changes to make it work with Turbo, see https://gist.github.com/vitobotta/dc264d271fa07363622b7c2cd9352d5a#file-prefetching-js

**Comment by vwong** [comment]
Thanks @vitobotta I like the idea of of using `<link rel="prefetch" href="/the-link" />`. I'll try this for now, barring any Turbo native solutions.

**Comment by vitobotta** [comment]
@vwong apparently link prefetch is not supported by Safari, so I am gonna try again my previous code with @DmitryBochkarev 's suggestion

**Comment by vitobotta** [comment]
@DmitryBochkarev ehm.. I am looking at the code but I can't find how to create a new Snapshot so I can add it with cache.put. I am not too good with JavaScript. Any suggestions? :)

**Comment by DmitryBochkarev** [comment]
@vitobotta  I tried using this api. But unfortunately there is no easy way to do it without a turbo repository fork. I apologize for misleading

**Comment by vitobotta** [comment]
@DmitryBochkarev I actually got it working nicely and cross browser compatible :) I'll write some notes tomorrow.

**Comment by vwong** [comment]
I'm building a site with progressive enhancement everywhere - so am not too fussed that some browsers may not support it. 

In the time gap between HTML being delivered, and JS being activated, 100% of browsers effectively have Javascript "disabled", and we fallback to native browser capabilities.

That said, it'll be better if we can get prefetching working in more browsers. Looking forward to your updates!

**Comment by vwong** [comment]
@vitobotta FYI, I had to add this to your instant.page solution, otherwise I was getting errors when Turbo is showing the preview of a previously cached page.

```
document.addEventListener("turbo:before-cache", () => {
  const links = document.head.getElementsByTagName("link")
  for (let i = links.length - 1; i >= 0; i--) {
    if (links[i].rel === "prefetch" && links[i].href.startsWith(location.origin)) {
      links[i].remove()
    }
  }
})
```

**Comment by vitobotta** [comment]
@vwong This is what I came up with and works fine https://gist.github.com/vitobotta/8ac3c6f65633b5edb2949aeff0dec69b

By default it preloads a page in the Turbo cache the first time you hover on the link. If some pages cannot work with Turbo cache due to some incompatible js libraries, you can just add a data attribute "prefetch-with-link" to the relevant links to prefetch them with the other method in my previous code. But by default it uses Turbo's cache. It works fine in Safari too.

**Comment by StanBright** [comment]
@vitobotta thanks, mate! I've added your code to https://www.libhunt.com, and I can confirm that it works fine for me, too.

Note: `mouseoverListener` was raising an undefined `mouseoverTimer`. All I had to do is defining it at the top level. (I think people using your snippet will have to add `import * as Turbo from "@hotwired/turbo"` at the top of the file, too.

**Comment by vwong** [comment]
Ooo. Very nice! No unnecessary duplicate prefetching anymore. Thanks!

**Comment by StanBright** [comment]
On the whole, this seems like something that many people would love to opt-in for. It'd be great if there was a Turbo config to enable it.

**Comment by vitobotta** [comment]
@StanBright oops I missed that variable. I actually have other unrelated stuff there that I need to separate. I totally agree that Turbo should have this built in and configurable! Would be awesome.

@vwong 👍

**Comment by fleck** [comment]
@vitobotta @StanBright @vwong Just stumbled upon this thread, I'm working on a prefetcher for turbo: https://github.com/fleck/nitrous-oxide. If anybody can kick the tires and give feedback that'd be great! nitrous-oxide uses plain fetch so it'll work in Safari!

**Comment by vitobotta** [comment]
@fleck that's awesome, will give it a try as soon as I have a min. Thanks!
