### ISSUE TITLE
Should/Can we keep the contents of a lazy frame on visit instead of reloading it?

### ISSUE THREAD

**Issue by weaverryan** [hotwired/turbo#106]
Hi!

We have a sidebar that we put in a frame so we can load it lazily:

```html
<!-- /foo -->
<turbo-frame src="/sidebar"></div>

<a href="/foo">Foo</a>
```

```html
<!-- /bar -->
<turbo-frame src="/sidebar"></div>

<a href="/bar">Bar</a>
```

Each time we navigate through the site (using normal Turbo NOT in a frame), the lazy sidebar re-loads. This makes sense: on each visit, the sidebar is replaced with a fresh `<turbo-frame src="/sidebar"></div>` which clears out the content and causes a new AJAX call to populate the frame.

When a lazy frame is being replaced by an identical lazy frame, would it makes sense to simply *keep* the original frame? Or is there a better solution? Like adding `data-turbo-permanent` to/around the lazy frame? Note: this currently doesn't work - could be user error, or could be something "missing" at the moment - https://github.com/hotwired/turbo/issues/21#issuecomment-750340131

Cheers!

**Comment by sstephenson** [comment]
You can use `<turbo-frame id="..." src="..." data-turbo-permanent>` to preserve a frame from one Turbo Drive page change to the next, as long as both pages' frames have the same ID and the permanent attribute. 👍

The issue you linked to is about preserving permanent elements _inside_ frames during frame navigation.
