### ISSUE TITLE
turbo 8 will support turbo-permanent on iframes?

### ISSUE THREAD

**Issue by michelson** [hotwired/turbo#1067]
Today I've tried the main branch of turbo with the new morph to test the behavior on turbo-perpanent with iframes on it. it seems the iframes get reloaded. Will turbo-8 support this on iframes?

in the idiomoprh readme there is an example of morphing with iframes so it should work, right?

**Comment by afcapel** [comment]
No plans, I'm afraid. We're dealing with browsers security restrictions here. Browsers reconnect iframes when they are connected and disconnected from the DOM. If you mark the element with data-turbo-permanent that will always happen. If you just do a morph refresh, with no data-turbo-permanent, then it depends on the specific mutation and if the morphing algorithm can perform it without reconnecting the iframe to the DOM, but that's not always possible.
