### ISSUE TITLE
8 beta 1 error

### ISSUE THREAD

**Issue by rctneil** [hotwired/turbo#1076]
I keep getting this error when trying Turbo 8 beta 1:

NoMethodError: undefined method thread_mattr_accessor’ for Turbo:Module (NoMethodError)`

All i did was use gem "turbo-rails", "~> 2.0.0.pre.beta.1" in my Gemfile and "@hotwired/turbo-rails": "^8.0.0-beta.1", in package.json.

Any ideas? Running Rails 7.1.1

**Comment by victorsmoreira** [comment]
That was fixed by [this commit](https://github.com/hotwired/turbo-rails/commit/ec74485895df8889c0f15e4c99c370851f78248f) on turbo-rails but was not released yet
I am using the main branch for now
```
gem "turbo-rails", github: "hotwired/turbo-rails", branch: "main"
```

**Comment by jorgemanrubia** [comment]
Thanks @victorsmoreira, closing this one
