### ISSUE TITLE
`advanced` and `restore` visits keep current scroll position with `scroll: :preserve`

### ISSUE THREAD

**Issue by maxnovee** [hotwired/turbo#1081]
a restoration visit with back button no longer scrolls back to saved position when `scroll: :preserve`
not sure if that's now a bug or a feature, but breaks a previous nice user experience on mobile views with advanced links and left slides.

**Comment by maxnovee** [comment]
some use case sample:
a long list of orders on the `/orders` page. scroll down to the bottom. click a link to `/orders/101` and on the show page slide left on a mobile to get back to previous page.
`scroll: :reset` comes with a nice scroll to saved position turbo-7 way, while `scroll: :preserve` stays on the top left position.

or this should be tweaked with a custom per-page `scroll` setting on both `/orders` and `/orders/101` pages?

**Comment by brunoprietog** [comment]
The new configuration should only affect page refreshes, not restoration visits, so I think it could be considered a regression

**Comment by maxnovee** [comment]
probably, there is an edge case and this breaks only when you navigate from a scrollable page to a page that fits the screen and then back to scrollable, that's when the scrollToTop happens on restore visit.

but it works just fine when you move back and forth between pages that are both bigger than 100vh.

but another silly thing, when moving between scrollable pages and a next page gets loaded and scrolled straight to position you were going away from on a previous page.

**Comment by maxnovee** [comment]
The initial bug report was actually related to the autofocus effect and not relevant anymore.

The actual bug covers `advanced` and `restoration` visits between pages where the new page, opened with the current scroll position, differs from turbo-7 behavior. This issue is particularly noticeable when navigating between pages larger than `100vh`. The functionality works correctly with a `scroll: :reset` but is broken when the `:preserve` option is enabled.

https://github.com/hotwired/turbo/assets/1827741/db22cd7e-2a4b-4a19-a809-954ebcbd8dbf


https://github.com/hotwired/turbo/assets/1827741/fafd552b-2c9b-49ee-bea8-3a62285d684d

**Comment by jorgemanrubia** [comment]
@maxnovee thanks for the report. I think this is a bug indeed: the `scroll: :preserve` option should only affect page refreshes, but current implementation will preserve scroll in any navigation as long as the option is in place.

**Comment by jorgemanrubia** [comment]
[Fix here](https://github.com/hotwired/turbo/pull/1096).
