### ISSUE TITLE
Turbo 8 refresh debounce in frontend

### ISSUE THREAD

**Issue by edwinv** [hotwired/turbo#1093]
We are testing with the Turbo 8 beta in our application. Many pages in our application contain information about multiple models in our application. Because the models are related and updating eachother, we often get multiple page refreshes shortly after each other:

![CleanShot 2023-12-01 at 11 41 50@2x](https://github.com/hotwired/turbo/assets/563294/ee7491cf-a09a-4d2e-b55e-c4a95d83848b)

Both refreshes will fire a page refresh right away. Turbo already handles multiple concurrent visits and will cancel the running visit request. Even though the first refresh request is cancelled in the browser, the server will still handle the request. In our case, some pages need quite some resources to render everything. Rendering the page twice in a short period of time, knowing one render will never be used by the browser, is a waste of resources.

Maybe Turbo should also include debouncing in the frontend to prevent subsequent refreshes? A short delay in the refresh would already catch many subsequent refreshes. @jorgemanrubia do you think this is worth a PR?

**Comment by afcapel** [comment]
@edwinv we already added some [debouncing to refresh broadcasts](https://github.com/hotwired/turbo-rails/blob/4eb4e928e30be8cd537af8073f98b80ddea4a578/app/channels/turbo/streams/broadcasts.rb#L71-L75). It's not documented yet, I'm afraid, we still have to add the documentation before the final release. 

For the debouncing to kick in you just need to ensure that all the related models are broadcasting refreshes to the same `stream`.

**Comment by afcapel** [comment]
@edwinv I see. I think the best approach would be to not subscribe to the children streams from the parent page. If the child has a `belongs_to :parent, touch: true` relation, then the parent will be updated when the child is updated. This way you can keep the debouncing on the server side and you don't need to worry about overloaded streams on the parent page.

**Comment by edwinv** [comment]
@afcapel Thanks, that would indeed fix this issue and is a feasible way forward for our project. 

I'm still in favor of client side debouncing. It is not a lot of code and for performance there are hardly any downsides. The downside of doing many refreshes is large: you can easily cause a small burst of requests to a server without knowing this. In my experience the interaction between ActiveRecord touches, jobs and ActionCable is magic for many engineers. They can easily create a combination of refreshes and streams that can cause many refreshes to happen shortly after each other. Debouncing would be a valuable safeguard to prevent this.

**Comment by jorgemanrubia** [comment]
I think debouncing page refreshes in the client is something that makes sense and that we'll eventually add. But even if we had that in place, I think what @afcapel suggests is a better approach here.
