### ISSUE TITLE
Turbo 8 Beta 1: Button with formmethod="patch" sends form method in lower case

### ISSUE THREAD

**Issue by klenis** [hotwired/turbo#1100]
When using `formmethod="patch"` on a button in Turbo 7.3.0 the form was sent with method in upper case. In Turbo 8 Beta 1 the method is sent in lower case. Is this a regression?

Example

```
<html>
  <head>
    <script type="module">
      import * as Turbo from 'https://unpkg.com/@hotwired/turbo@7.3.0/dist/turbo.es2017-esm.js';
      //import * as Turbo from 'https://unpkg.com/@hotwired/turbo@8.0.0-beta.1/dist/turbo.es2017-esm.js';
    </script>
  </head>

  <body>
    <turbo-frame id="form">
      <form action="">
        <input type="submit">

        <button type="submit" formmethod="patch">Patch</button>
      </form>
    </turbo-frame>
  </body>
</html>
```

Turbo 7.3.0

![image](https://github.com/hotwired/turbo/assets/343720/6834439d-d89d-4a05-9b6f-64d7553f51da)

Turbo 8 Beta 1

![image](https://github.com/hotwired/turbo/assets/343720/2a527efb-7027-4f4c-9b6f-102489b749f1)

Chrome (Mac)
Version 119.0.6045.199 (Official Build) (arm64)

**Comment by npezza93** [comment]
Yea this is resulting in 400 requests for me

**Comment by dinandmentink** [comment]
Same issue for links with `data-turbo-method="patch"`.

**Comment by thedanbob** [comment]
If you're using Rails resource routing (where PATCH and PUT are mapped to the same controller action) you can substitute with `data-turbo-method="put"` as it still works.

**Comment by rainerborene** [comment]
I can confirm this issue.
