### ISSUE TITLE
Turbo.visit with POST method

### ISSUE THREAD

**Issue by collimarco** [hotwired/turbo#1106]
I am trying to initiate a post request programatically from a Stimulus controller.

Something like this (not working):

```
Turbo.visit('/path/to/page', { data: { 'turbo-method': 'post' } });
```

Is there any solution?

For example, in my specific case, I need to build a Stimulus action that first performs some requests to an API, then, when those requests are completed successfully, uses Turbo.visit with POST method.

**Comment by brunoprietog** [comment]
That is not supported, you can only pass the action or a frame. You could use [request.js](https://github.com/rails/requestjs-rails) for that use case if you are using Rails.

**Comment by collimarco** [comment]
Yes, I know about request.js, but that is like a background fetch request, it is not like clicking a link

**Comment by brunoprietog** [comment]
Links should only be GET. You can also use something like `form.requestSubmit()`.

**Comment by collimarco** [comment]
> Links should only be GET.

I know, but in Turbo it's sometimes useful to use other methods... I was looking for something like `data-turbo-method="post"`. For consistency I expected that I could do the same from a Stimulus controller.

**Comment by brunoprietog** [comment]
Yes, I understand. Case apart, but deep down I regret that there is a `data-turbo-method` when we can use a `<form>` element. This has introduced accessibility problems unnecessarily and although the Turbo documentation recommends against it, it is still widely used by the community.

HEY, for example, has a Stimulus controller, `form_controller`, which has the `submit` action and calls `this.element.requestSubmit()`. They usually invoke it in switchers, for example, when they want the form to submit automatically when the user presses the checkbox.

So, you could build an invisible form in the HTML, fill it with data coming from the response you make before if you need it and submit it. These are just suggestions
