### ISSUE TITLE
v8.0.0-beta1: Preloader: `Sec-Purpose` header is ignored by `fetch(..)`

### ISSUE THREAD

**Issue by pfeiffer** [hotwired/turbo#1107]
Previously the header for indicating that a resource was preloaded was named `VND.PREFETCH`. The dot in the header name caused it to be stripped by reverse proxies, including CloudFlare, as discussed in #924 

It was discussed that it should be renamed, originally the PR I made in #925 suggested `x-purpose`. However, it was suggested that the header should instead be named `sec-purpose` to match a newer spec. This was done in #925 and merged and released as part of v8 beta.

However, it seems that `fetch(..)` - at least in Chrome - strips this header from the request being made.

To reproduce, fire a manual `fetch(..)` from the console:

```
fetch("https://.../", { headers: { "sec-purpose": "preview", "x-something": "foo" })
```

Inspecting the request headers, the `sec-purpose` is not sent, while the `x-something` is:

![image](https://github.com/hotwired/turbo/assets/195925/574f755b-d4c3-46c6-84bb-2972b47d14f0)

I guess the `sec-...` are reserved headers and that fetch strips these out before sending.

I propose that we rename the header to `x-purpose` which seems to be the header used by Safari and Chrome (for the preview on the launch pages), as well as Facebook in-app browser. I'll wrap up a PR.

**Comment by pfeiffer** [comment]
As discussed in [#1101](https://github.com/hotwired/turbo/pull/1101#discussion_r1454780688) the `Sec-` prefixed headers are intentionally not allowed to be set via `fetch(..)`:

In the [Fetch Standard](https://fetch.spec.whatwg.org/#forbidden-header-name) under the "Forbidden Header Name" section, the following paragraph explicitly mentions that any header starting with `Sec-` should not be allowed to be set by client (eg. via JS), but rather be fully controlled by the user agent:

> A [header](https://fetch.spec.whatwg.org/#concept-header) (name, value) is forbidden request-header if these steps return true:
> ...
> * If name when [byte-lowercased](https://infra.spec.whatwg.org/#byte-lowercase) [starts with](https://infra.spec.whatwg.org/#byte-sequence-starts-with) `proxy-` or `sec-`, then return true.

The linked spec also mentions _why_ these are reserved, even in the future:

> Note: These are forbidden so the user agent remains in full control over them.
> [Header names](https://fetch.spec.whatwg.org/#header-name) starting with `Sec-` are reserved to allow new [headers](https://fetch.spec.whatwg.org/#concept-header) to be minted that are safe from APIs using [fetch](https://fetch.spec.whatwg.org/#concept-fetch) that allow control over [headers](https://fetch.spec.whatwg.org/#concept-header) by developers, such as [XMLHttpRequest](https://xhr.spec.whatwg.org/#xmlhttprequest). [[XHR]](https://fetch.spec.whatwg.org/#biblio-xhr)

The current implementation in Turbo 8 is a no-op.

Ping @davidalejandroaguilar

**Comment by psyipm** [comment]
It would be great to have this addressed. Could you guys please have a look? 

Ping @rik @hey-leon @seanpdoyle @davidalejandroaguilar @afcapel

**Comment by hey-leon** [comment]
Hey @psyipm I am not part of any team on the Turbo repository but I did read the PR body and elaborating comment and it seems pretty clear cut to me. If its explicitly called out that `Sec-*` is not allowed in the whatwg speicifications for fetch it would make sense to change it 👍.

**Comment by afcapel** [comment]
Fixed in https://github.com/hotwired/turbo/pull/1108

We're now using `X-Sec-Purpose` instead.
