### ISSUE TITLE
websocket pending while I don't want to use websockets

### ISSUE THREAD

**Issue by kasperkamperman** [hotwired/turbo#111]
I'm trying Turbo on some plain html pages. I don't want to make use of websockets (as far as I understood only used by Turbo Streams). 

However, I see that it's trying to setup a WS connection in network:

<img width="746" alt="Screenshot 2021-01-15 at 23 55 29" src="https://user-images.githubusercontent.com/1760616/104786596-a5e22a80-578d-11eb-9a07-8a2b8aa4757d.png">

I import the module as follows and used v7.0.0-beta3:
```
<script type="module">
        import hotwiredTurbo from 'https://cdn.skypack.dev/pin/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/min/@hotwired/turbo.js';
    </script>
```

**Comment by dhh** [comment]
Can't replicate this with latest:

```html
<html>
<head>
  <script type="module" src="https://unpkg.com/@hotwired/turbo@7.0.0-rc.5/dist/turbo.es2017-esm.js"></script>
</head>
<body>
</body>
</html>
```
