### ISSUE TITLE
data-turbo-confirm on form does not work when action includes extension

### ISSUE THREAD

**Issue by jackc** [hotwired/turbo#1112]
```html
<!doctype html>
<html>
<head>
<script type="module" src="https://cdn.skypack.dev/@hotwired/turbo@7.3.0"></script>
</head>
<body>
  <form data-turbo-confirm="Are you sure?" method="post" action="/test">
    <button type="submit">Turbo confirm works when action does not have extension</button>
  </form>
  <form data-turbo-confirm="Are you sure?" method="post" action="/test.1">
    <button type="submit">Turbo confirm fails when action has extension</button>
  </form>
</body>
</html>
```

When action is `/test` the confirm alert box is triggered. When action is `/test.1` the confirm alert box is not triggered. You can reproduce with the complete HTML document above or https://jsfiddle.net/uncannyjack/befunscy/2/.

I encountered this issue with Rails when trying to delete a singleton resource. Rails includes the ID as the extension (e.g. `/user/subscription.1234`).

**Comment by dhh** [comment]
Turbo isn't active on urls with extensions. You're getting dot id because your URLs are wrong. Fix the latter and it won't be a problem.

**Comment by jackc** [comment]
> You're getting dot id because your URLs are wrong. Fix the latter and it won't be a problem.

Thanks. Indeed, I was generating the URL improperly, though the Rails part actually still worked. Fixing this did resolve the issue.

> Turbo isn't active on urls with extensions.

May I suggest adding this to the documentation? Perhaps I missed it, but I have read the Turbo handbook several times and was not aware of this behavior. I also searched for key words like "extension" when I was trying to figure out this issue and didn't find it. I've just now also looked through the Turbo source code and ultimately found this behavior implemented in `locationIsVisitable` and `isHTML` but there were no comments or explanation.

**Comment by dhh** [comment]
Yes I believe there’s an open PR on the turbo-site repo.
