### ISSUE TITLE
Very new to turbo --- log filling with hundreds of stream

### ISSUE THREAD

**Issue by weiserma** [hotwired/turbo#1115]
I am running in a development environment (localhost) on windows with redis running on WSL with 2 browsers.. 

I checked both pages only have one id="user_status".

Any idea what is going on?

gem version: 
  * turbo-rails (1.5.0)

using example appearance_channel 

I get hundreds of log messages like:

Turbo::StreamsChannel transmitting "<turbo-stream action=\"replace\" target=\"user_4\"><template>\n<div class=\"status-circle black\" id=\"user_4\"></div>\n</template></turbo-stream>" (via streamed from user_status)
Turbo::StreamsChannel transmitting "<turbo-stream action=\"replace\" target=\"user_4\"><template>\n<div class=\"status-circle black\" id=\"user_4\"></div>\n</template></turbo-stream>" (via streamed from user_status)
Turbo::StreamsChannel transmitting "<turbo-stream action=\"replace\" target=\"user_4\"><template>\n<div class=\"status-circle black\" id=\"user_4\"></div>\n</template></turbo-stream>" (via streamed from user_status)
Turbo::StreamsChannel transmitting "<turbo-stream action=\"replace\" target=\"user_4\"><template>\n<div class=\"status-circle black\" id=\"user_4\"></div>\n</template></turbo-stream>" (via streamed from user_status)

**Comment by dhh** [comment]
Please direct usage questions to the forum or discord. We use issues to track bugs only. Thanks.
