### ISSUE TITLE
`turbo-visit-control` isn't respected with morphing

### ISSUE THREAD

**Issue by northeastprince** [hotwired/turbo#1116]
In my app, I'm using SimpleCSS which adds styles to HTML elements themselves (not their classes). In development, when new code causes an error impacting the route I'm already on, Turbo mistakenly morphs to Rails' error info page, even though [Turbo visits are disabled there](https://github.com/rails/rails/blob/efce114ddea89110bdee7af7a8c65377a53182b7/actionpack/lib/action_dispatch/middleware/templates/rescues/layout.erb#L6), thus putting me in a weird limbo where exception backtraces are semantically styled 💀

**Comment by brunoprietog** [comment]
Related #1105

This is because MorphRenderer doesn't inherit from PageRenderer, so all these things are lost.
