### ISSUE TITLE
Page refreshes: Selected option issue when morphing with changing select options

### ISSUE THREAD

**Issue by meceo** [hotwired/turbo#1119]
"Selected option" gets incorrectly displayed once server side returns new select options using morphing. After morphing the DOM contains the correct option with "selected" tag, but displayed one is incorrect. When forcing page refresh the selected option is properly displayed.

![morph issue](https://github.com/hotwired/turbo/assets/56053/f62a47e8-97fa-4e72-a790-b78597cd97a3)

Minimalistic code to reproduce the issue:
https://github.com/meceo/morph_testing/pull/2/files

**Comment by brunoprietog** [comment]
This is a bug in Idiomorph that has been fixed in the latest version. We need to bring these changes to Turbo

**Comment by meceo** [comment]
@brunoprietog do you already know when the changes will be bring to Turbo? Can I help?

**Comment by brunoprietog** [comment]
It was made in #1122 and is now in main. It would be great if you can test if that solves the problem. If it doesn't, we should report this to Idiomorph.

**Comment by meceo** [comment]
@brunoprietog I tested the main branch and looks good.

![CleanShot 2024-01-13 at 16 13 24](https://github.com/hotwired/turbo/assets/56053/913872d0-2496-404c-a77e-7ed21bf70f2e)

**Comment by brunoprietog** [comment]
Great! So can you close this?
