### ISSUE TITLE
Suggestion: "data-turbo-target" attribute to specify elements to update within frame

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#112]
Currently turbo-frame's update the entire frame with any turbo request coming from within frame. This works great in a lot of cases, however it would be great to have more control over which elements you would like to update within the frame.  

I propose we could introduce an **optional** "data-turbo-target" attribute where we could specify what elements will get updated within the frame.

eg.

```
<turbo-frame data-turbo-target=".results">
    <%= form_for @criteria,  as: :criteria,  method: :get, url: locations_url,  data: { controller: "search" } do |f| %>
        <%= f.search_field :query, placeholder: "Search...",  data: { action: "debounced:input->search#trigger" } %>
    <% end %>
    <div class="results">
       <ul>
           <% for result in @results %>
           <li><%= result.name %></li>
           <% end %>
       </ul>
     </div>
</turbo-frame>
```

data-turbo-target could also be comma separated to specify multiple targets eg. data-turbo-target=".results, #pagination"

Thoughts?

**Comment by dhh** [comment]
You can wrap the results in another frame, then use data-turbo-frame="name_of_that_frame" on the search result form to replace them.
