### ISSUE TITLE
Turbo Drive redirect doesn’t send cookies

### ISSUE THREAD

**Issue by erick-tmr** [hotwired/turbo#1121]
Hi, my application is using some OAuth login provider, so it needs to redirect to a URL with querystrings every time a token expires.
When Turbo Drive is enabled, this redirect occurs without sending the cookies for the Location URL.

Is there a way to enable cookies to be sent in this request?

We need to do something like this:
https://developer.mozilla.org/en-US/docs/Web/API/fetch#include

Make it configurable through some API would suffice.

**Comment by seanpdoyle** [comment]
Have you tried declaring a [turbo:before-fetch-request](https://turbo.hotwired.dev/reference/events) event listener, then modifying its `detail.fetchOptions.credentials` value?

```js
addEventListener("turbo:before-fetch-request", (event) => {
  event.detail.fetchOptions.credentials = "include"
})
```

**Comment by erick-tmr** [comment]
> Have you tried declaring a [turbo:before-fetch-request](https://turbo.hotwired.dev/reference/events) event listener, then modifying its `detail.fetchOptions.credentials` value?
> 
> ```js
> addEventListener("turbo:before-fetch-request", (event) => {
>   event.detail.fetchOptions.credentials = "include"
> })
> ```

Hey @seanpdoyle , will try that, thanks

**Comment by erick-tmr** [comment]
it worked @seanpdoyle , Thanks
