### ISSUE TITLE
Turbo stream links proper handling when users middle click, open new window, CTRL click on links

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#1137]
I am finding our users complain a lot due to just turbo stream links being clicked into new tabs, either by accident or just trying to open in new tab.  This causes just the stream response to appear in the new tab window, rather than being handled safley.

One solution that I came up with is trying to just replace the a tags on page load and swapping on click with a void(0).   Its getting there, but still feels hacky and think there should be standard approach with these situations.

Anyone doing anything differently?

```
const replaceTurboStreamLinksWithVoid = () => {
  const voidHref = "javascript:void(0);";
  document.querySelectorAll("a[data-turbo-stream='true']").forEach((el) => {
    if (el.getAttribute("href") !== voidHref) {
      el.setAttribute("data-href", el.getAttribute("href"));
      el.setAttribute("href", voidHref);
    }

    if (el.dataset.listened !== true) {
      el.addEventListener("click", (event) => {
        if (event.ctrlKey) {
          event.preventDefault();
          return;
        }
        event.currentTarget.setAttribute("href", event.currentTarget.getAttribute("data-href"));
        event.currentTarget.dataset.listened = true;
      });
    }
  });
};
```

**Comment by KonnorRogers** [comment]
I just use a `<button>` wrapped in a `<form>` that returns the `<turbo-stream>`.

Using a `form + button` will only ever affect the current window (as long as its not `target="_blank"`

https://codepen.io/paramagicdev/pen/poYOaLJ

**Comment by brunoprietog** [comment]
Hi @acetinick, I second @KonnorRogers's words. Actually, links should only be used to navigate to other pages and that would be going too much against the grain and spirit of the web and browsers. It's also considered an accessibility error to use them for this kind of purposes. So closing this for now
