### ISSUE TITLE
Turbo.navigator.submitForm inside from, submits without the header

### ISSUE THREAD

**Issue by jbonnier** [hotwired/turbo#1149]
When submitting a form that is in a frame with `Turbo.navigator.submitForm()` the `Turbo-Frame` header is not in the request.

This is a problem when you need to do some processing before you actually send the form.

**Comment by seanpdoyle** [comment]
@jbonnier `Turbo.navigator.submitForm()` isn't intended to be used outside of the package. Could you share more about your use case?

Have you tried [HTMLFormElement.requestSubmit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) instead?

**Comment by jbonnier** [comment]
I have a form inside a turbo-frame which has a `data-controller="form-submit"` and a `data-action="submit->form-submit#submitForm"`. I want to validate that the user is not a robot with recaptcha upon submit, so I `preventDefault()` do some processing and then I want to be able to submit the form.

If I do a `event.target.submit()` the entire page reloads. So I'm looking for a way to submit the form, but at the same time let "Turbo intercept the request" and do its thing.

Here's my stimulus controller.

```
import {Controller} from '@hotwired/stimulus';
import recaptchaInit from '../components/recaptcha-init.js';
import {flash} from '../components/utilities.js';

/* stimulusFetch: 'lazy' */
export default class extends Controller {
  static values = {
    captchaInitFailure: String,
    unknownFailure: String,
    formReady: Boolean,
  };

  // async submitStart(event) {
  async submitForm(event) {
    console.log('submit form')
    if (!this.formReadyValue) {
      event.preventDefault();
      event = await this.prepareForm(event);
      // event.target.submit();
      Turbo.navigator.submitForm(event.target)
    }
  }

  async prepareForm(event) {
    this.element.classList.add('loading');

    if (document.querySelector('body')
      .getAttribute('data-not-a-robot') !== 'true'
    ) {
      const recaptchaSiteKey = document.getElementsByTagName('body')[0]
        .getAttribute('data-recaptcha-site-key');

      try {
        await recaptchaInit();
      } catch (_) {
        flash(this.captchaInitFailureValue, ['alert', 'alert-danger']);
      }

      if (typeof grecaptcha === 'object') {
        await grecaptcha.ready(async () => {
          try {
            await grecaptcha.execute(recaptchaSiteKey).then(token => {
              const action = this.element.action;
              const url = new URL(action);
              url.searchParams.set('reCaptchaToken', token);
              event.target.setAttribute('action', url.toString());
            });
          } catch (_) {
            flash(this.unknownFailureValue, ['alert', 'alert-danger']);
          }
        });
      }
    }
    this.formReadyValue = true;

    return event;
  }
}
```

**Comment by seanpdoyle** [comment]
Calling `HTMLFormElement.submit()` won't fire events, which is what Turbo hooks into.

Have you tried calling [HTMLFormElement.submit](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) instead of `Turbo.navigator.submitForm(event.target)`?

```js
event.target.requestSubmit()
```

**Comment by jbonnier** [comment]
For some reason `event.target.requestSubmit()` does nothing, or at least, it doesn't submit nor it triggers back my `submitForm()` function.

**Comment by jbonnier** [comment]
Nevermind, the problem was somewhere else in the code, thanks for your replies though.
