### ISSUE TITLE
`turbo_stream` request with updating url

### ISSUE THREAD

**Issue by loqimean** [hotwired/turbo#1151]
I found a nice example on the Medium website that shows us that it is really nice to have the ability to request turbo_stream in a turbo_frame, it will update the `src` of a frame, but even when I USE `data-turbo-action="advance"` it doesn't change the browser URL.

```ruby
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end
```

```erb
<%# index.turbo_stream.erb %>
<%= turbo_stream.update(:test) do %>
  <%= link_to("Time now is #{Time.now}", home_path(time: Time.now.to_s.parameterize), data: { turbo_stream: true }) %>
<% end %>

<%# index.html.erb %>
<h1>Hello</h1>
<% turbo_frame_tag :test, data: { turbo_action: "advance" } do %>
    <%= link_to("Time now is #{Time.now}", home_path(time: Time.now.to_s.parameterize), data: { turbo_stream: true }) %>
<% end %>
```

**Comment by loqimean** [comment]
Section #8
https://dev.to/chwistophe/rails-7-pagination-with-turbo-frame-streams-infinite-scrolling-stimulus-js-3fih

**Comment by loqimean** [comment]
So, I gues this thing should be fixed or added feature instead of this workaround

**Comment by brunoprietog** [comment]
Hi @loqimean, Turbo streams aren't intended to update a visit, they are only intended to perform more complex dom operations in a response.
