### ISSUE TITLE
Autofocus tests are flaky

### ISSUE THREAD

**Issue by afcapel** [hotwired/turbo#1154]
The often fails on CI, for example https://github.com/hotwired/turbo/actions/runs/7723792974/job/21054601474

**Comment by afcapel** [comment]
Another failure https://github.com/hotwired/turbo/actions/runs/7755348058/job/21150514185

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/1219 to try and address this.
