### ISSUE TITLE
Frame navigation broken when Turbo is used without framework integration

### ISSUE THREAD

**Issue by sixtyfive** [hotwired/turbo#1159]
See https://git.weitnahbei.de/sixtyfive/throughput/-/blob/main/index.html?ref_type=heads#L12 for a more or less MRE.

Although `Turbo.visit` with 1 parameter works as expected, with 2 parameters it doesn't. While stepping through the JS side with a debugger, nothing ever seems to even make an attempt to replace the `<turbo-frame ...>`'s contents.

**Comment by afcapel** [comment]
@sixtyfive trying to reproduce, but this works for me https://gist.github.com/afcapel/be046236d1b824e5510634431a92cc89
