### ISSUE TITLE
refresh="morph" in a turbo-frame morphs on a full Page Reload but fails to morph with frame.reload()

### ISSUE THREAD

**Issue by krschacht** [hotwired/turbo#1161]
@jorgemanrubia acknowledge the issue over on this PR comment: https://github.com/hotwired/turbo/pull/1068#issuecomment-1925877557

To elaborate on the issue for whomever may tackle this. Imagine this page setup:

```
<body>
   Contents outside of frame
   
   <turbo-frame id="post" refresh="morph" src="/post/1">
      Loading... (preload contents)
   </turbo-frame>
</body>
```

If something triggers a full Page Reload causing <body> to be morphed rather than replaced, the presence of `refresh="morph"` is smart and it also re-requests the src and *morphs the response from src* so that the contents within side turbo-frame only updates what is needed.

However, if you instead trigger a refresh to the frame using javascript, e.g. `document.getElementById('post').reload()` the turbo-frame ignores the `refresh="morph"` and does a full replacement within the turbo-frame.

**The ideal behavior:**
When `refresh="morph"` is present on a turbo-frame then anything that triggers a refresh of that turbo-frame (e.g. `element.reload()`) should be a morphing refresh.

**Comment by krschacht** [comment]
Hi @jorgemanrubia I went ahead and tee'd up a PR to fix this issue. Check #1192

**Comment by seanpdoyle** [comment]
@krschacht was this issue resolved by https://github.com/hotwired/turbo/pull/1192 and https://github.com/hotwired/turbo/pull/1028? 

If it has been resolved, should it be closed?
