### ISSUE TITLE
Script doesn't initialized again using form of SendPulse

### ISSUE THREAD

**Issue by loqimean** [hotwired/turbo#1166]
HI :-), it's me again), I have a problem of loading subscription form from send puls, so, I tried to find solution by myself, but.., I'm here)), so, can you help me? When I disable turbo on a HTML tag (for all page) - it works fine, but of course it's a really bad solution, so, help me find a light in the darkest night!
Scripts of SendPuls:
https://web.webformscr.com/apps/fc3/build/default-handler.js

and this script I put into my HTML body anywhere:
```html
<script src="//web.webformscr.com/apps/fc3/build/loader.js" async sp-form-id="545b78a3bf672fc262c8b0b0b945e6f529119b2ff70cc83cf6cd1870ea37653b"></script>

**Comment by pinzonjulian** [comment]
Hey @loqimean !
It seems like the kinds of questions you have been asking aren't proper issues with the library (e.g. bugs). I think it's better if you redirect your questions to other kinds of forums made to ask for help. 

The official Hotwire discuss is a great place to start

https://discuss.hotwired.dev

Or this Discord workspace which has a bunch of nice people willing to help you out

https://discord.gg/stimulus-reflex

**Comment by loqimean** [comment]
> Hey @loqimean !
> It seems like the kinds of questions you have been asking aren't proper issues with the library (e.g. bugs). I think it's better if you redirect your questions to other kinds of forums made to ask for help. 
> 
> The official Hotwire discuss is a great place to start
> 
> https://discuss.hotwired.dev
> 
> Or this Discord workspace which has a bunch of nice people willing to help you out
> 
> https://discord.gg/stimulus-reflex
> 

Yes, might be it is, so I asked here because it is related to this lib and I hope here are people that had such problems and found-know solution 🙂

**Comment by bluestorm21** [comment]
@loqimean have you tried to put the script before the body ending tag: </body> that way it will be re-evaluated I think.
also you may or may not add https: before //web.webformscr.com/apps/fc3/build/loader.js

**Comment by brunoprietog** [comment]
Hi @loqimean, I'm going to close this because it's not a Turbo issue. Anyway, have you tried putting the script in the head, using the defer attribute?
