### ISSUE TITLE
InstantClick always fetches page when hovering same link within the turbo-prefetch-cache-time window.

### ISSUE THREAD

**Issue by jean-francois-labbe** [hotwired/turbo#1176]
Hi, thanks for this amazing Turbo 8.
Regarding InstantClick.

The default `turbo-prefetch-cache-time` is 10000 (I'm not sure of the unit, seems to be milliseconds).

I've noticed that the current InstantClick behavior is to fetch the page on each link hover (even when hovering multiple times within the 10 seconds cache window).

![CleanShot 2024-02-08 at 16 41 37](https://github.com/hotwired/turbo/assets/1558372/2e9d196a-ddf0-462a-8f0b-2104bdde3892)

I thought on link hover InstantClick would fetch the page from the server store it to cache for 10 seconds.
If the user hovers the link again within 10 seconds it would not fetch a new page (because it's in cache, and why would we cache it if we'd fetch a new page on each link hover).

I may misunderstand the feature.

**Comment by janklimo** [comment]
Observing the same behavior.

**Comment by marcelolx** [comment]
> The feature is also missing documentation.

Missing something here https://turbo.hotwired.dev/handbook/drive#instantclick?

**Comment by janklimo** [comment]
@marcelolx it's missing any info about the `turbo-prefetch-cache-time` meta tag

https://github.com/hotwired/turbo/blob/fccb3a4e5b2a47e63b50efe8333ec7a3265006c1/src/observers/link_prefetch_observer.js#L136

**Comment by mansakondo** [comment]
From my understanding, this behavior was introduced in this [commit](https://github.com/hotwired/turbo/commit/52c8533c83bf02b428ddab6140ddfb663208cb06) where the cache is considered obsolete as soon as a `mouseleave` event is triggered. So, I guess the intent was to clear the cache if a user has hovered over a link but decided not to click it.
https://github.com/hotwired/turbo/blob/fccb3a4e5b2a47e63b50efe8333ec7a3265006c1/src/observers/link_prefetch_observer.js#L51

**Comment by jean-francois-labbe** [comment]
Behavior has been explained in this comment https://github.com/hotwired/turbo/pull/1181#issuecomment-1936505362
