### ISSUE TITLE
Morphed Turbo frame keeps loading the same content when `turbo_frame: :_top` is used to exit it

### ISSUE THREAD

**Issue by davidalejandroaguilar** [hotwired/turbo#1182]
# Description

Given this basic controller:

```rb
class PostsController < ApplicationController
  def index
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title)
  end
end
```

Page morphs enabled on `application.html.erb` layout via:

```erb
<%= turbo_refreshes_with method: :morph, scroll: :preserve %>
<%= yield :head %>
```

This `index.html.erb` page:

```erb
<div>
  Posts max updated_at:
  <%= Post.maximum(:updated_at) %>
</div>

<ul>
  <% Post.all.each do |post| %>
    <%= turbo_frame_tag post do %>
      <li>
        <%= post.title %>
        <%= link_to "Edit post", edit_post_path(post) %>
      </li>
    <% end %>
  <% end %>
</ul>
```

And this `edit.html.erb` page with a form using `turbo_frame: :_top`:

```erb
<%= turbo_frame_tag @post do %>
  Editing post <%= @post.title %>

  <%= form_with model: @post, data: { turbo_frame: :_top } do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.submit %>
  <% end %>
<% end %>
```

This is the expected behavior: by clicking "Edit post", the post is replaced with that post's edit page, then clicking "Update Post" closes that post's edit page and goes back to the posts page.

https://github.com/hotwired/turbo/assets/15317732/f0b86799-1a9e-4f66-ac63-4e3365f2dba8

Yet this happens, the frame is reloaded after morphing, loading the edit page again:

https://github.com/hotwired/turbo/assets/15317732/f3fdf1bd-8aa2-4842-ad2c-4f4b92fca1e1

If we add `refresh: :morph` to the initial Turbo frame on `index.html.erb`, we never exit the edit page back to posts.

```erb
<div>
  Posts max updated_at:
  <%= Post.maximum(:updated_at) %>
</div>

<ul>
  <% Post.all.each do |post| %>
    <%= turbo_frame_tag post, refresh: :morph do %>
      <li>
        <%= post.title %>
        <%= link_to "Edit post", edit_post_path(post) %>
      </li>
    <% end %>
  <% end %>
</ul>
```

https://github.com/hotwired/turbo/assets/15317732/6a0cd11d-4cd9-46d2-877f-b421ec60309b

# Note

A very small, one-commit repo is here with the above code: https://github.com/davidalejandroaguilar/turbo-frame-reload-problem

**Comment by davidalejandroaguilar** [comment]
Just realized this is not the `turbo-rails` repo. My bad, it was very late at night. 

Should I move this issue there?

**Comment by Intrepidd** [comment]
I made a PR for this exact issue in #1175

**Comment by davidalejandroaguilar** [comment]
This was indeed fixed by https://github.com/hotwired/turbo/pull/1175 😃
