### ISSUE TITLE
Responding to a form submit with a 422 raises a SEVERE log in the console

### ISSUE THREAD

**Issue by jdbann** [hotwired/turbo#120]
I've been adding [turbo-rails](https://github.com/hotwired/turbo-rails) to my app. With form updates (when validations fail for example) I can return a 422 with the rendered page. Everything functions correctly and the page is redrawn with my new content. However, I get a SEVERE log in the console:

```
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
```

To confirm this, I setup a fresh Rails app with the following versions and had the same issue:

```
turbo-rails: 0.5.3
rails: 6.1.1
@hotwired/turbo-rails: 7.0.0-beta.3
```

Ideally turbo would prevent the browser from logging this, as we are expecting to be able to handle a 422 in this instance. But the error seems to be thrown by the browser itself rather than anything in the JS. This has happened in Safari 14.0.2 and Chrome 87.0.4280.141

**Comment by smridge** [comment]
I believe this is intended behavior. However, if you add a `turbo_frame_tag` before the `form_with` instead of `status: :unprocessable_entity` in the controller, `422` goes away.

For example:
```ruby
<%= turbo_frame_tag @foo %>
  <%= form_with(model: @foo) do |form| %>
  ...
  <% end %>
<% end %>
```

**Comment by jdbann** [comment]
@smridge Thank you for the suggestion! There's a couple of problems still though:

1. The 422 error still appears in the console
2. When the POST is successful, the controller is meant to `redirect_to` the show action but Turbo raises an error saying `Response has no matching <turbo-frame id="new_post"> element`

I can set `<form data-turbo-frame="_top">` and the redirect is fine, but it doesn't prevent the console error.

Are you seeing the error as well?

**Comment by smridge** [comment]
OO you're right. I was so focused on error handling, I spaced on when things are successful 🤦‍♀️ .

I think the `turbo_frame_tag` without `status: :unprocessable_entity` would only work properly with a `turbo_stream_from` tag. I haven't actually tested that out though.

The best example of turbo implementation I've found is https://gorails.com/episodes/upgrade-from-turbolinks-to-hotwire-and-turbo

Seems like we would need to accept `status: :unprocessable_entity` as a new default https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission . Or re-think how we do some of our forms in that may not need to re-direct to a show page after all.

**Comment by jdbann** [comment]
> Seems like we would need to accept status: :unprocessable_entity as a new default

Oh yes, I'm completely in favour of using `:unprocessable_entity`! It's just the error I'd like to remove, as the 422 and the form re-render are all expected behaviour.

It looks like the error message is a default behaviour of the browser though, and I'm struggling to find anything that documents this.

**Comment by n-studio** [comment]
I encountered the same issue and fixed it by adding in my controller:

```ruby
format.html { render :new, status: :unprocessable_entity }
format.turbo_stream { render turbo_stream: turbo_stream.replace(@user, partial: 'users/form', locals: { user: @user })}
```
