### ISSUE TITLE
[QUESTION] Plans for turbo handle routes?

### ISSUE THREAD

**Issue by rafaeldev** [hotwired/turbo#1212]
Hi everyone!

I'm seeing a good movement on rails to support more and more PWA Apps.
I have one using rails 7 and always think to move to react stack only to (mainly) use route manager feature.

For users using PWA (or TWA), use native back button is natural to navigate on a native app.
When the user open a modal, is natural to him press native back to "return" and it fires a back page, in this way losing form filled or other object state.

I'm talking about "routes" but can be a state stack, perhaps...

I don't know where to do this question but I'll let here.

Thanks for your work!

**Comment by brunoprietog** [comment]
I doubt that Turbo will ever implement something like this. It is not in their spirit to maintain a state other than in HTML.

I guess the modal example is a good use case to solve with Stimulus.
