### ISSUE TITLE
Morph action for streams not part of 8.0.4 but in docs

### ISSUE THREAD

**Issue by avwie** [hotwired/turbo#1229]
Following the docs to install Turbo, but `morph` is not defined for streams in 8.0.4 resulting in an error.

Now I see the docs are _ahead_ of the actual latest release:
https://github.com/hotwired/turbo-site/commit/99401c208e21c77297db25149fa3bbeb7a0afbfd

Please sync the doc releases with the actual releases, I was pulling my hair out on why it was not working.

**Comment by brunoprietog** [comment]
We've reverted this PR in [hotwired/turbo-site#197](https://github.com/hotwired/turbo-site/pull/197). The API changed a bit in #1240, we'll merge the new documentation when releasing the new version
