### ISSUE TITLE
attribute that will cancel the page request on hover

### ISSUE THREAD

**Issue by pqvel** [hotwired/turbo#1232]
When migrating from version 7.3.0 to 8, I encountered the following problem: There are many links on the site that when clicked on, for example, deleting the cart, setting the reservation status, etc. In version 8, when you hover over these links, the turbo makes a request at this url. I think that we need to add an attribute that will prohibit making a request when hovering.

**Comment by inspire22** [comment]
Those requests should use data-method='post' as well, since they're changing something, which I believe would stop prefetch from happening.

**Comment by brunoprietog** [comment]
You can see additional information about this feature and how to disable it [here](https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover).
