### ISSUE TITLE
turbo didn't get noticed of new content

### ISSUE THREAD

**Issue by matias-carpintini** [hotwired/turbo#1236]
i'm adding links with a stimulus controller and the `insertAdjacentHTML` function. when i click on those links, the request is made with HTML, not Turbo. prefetch does works tho.

i tried with a turbo_frame_tag, and doing `frame.reload()` after `insertAdjacentHTML`, same result.

any idea on how can i make this work?

the inserted html has no tricks:
```
populateDropdown(event) {
  const professionalId = event.target.getAttribute("data-professional-id");
  const dateTime = event.target.getAttribute("data-datetime");

  // Use professionalId and datetime to fetch or generate the dropdown content
  const dropdownContent = `
    <a href="/appointments/new?professional_id=${professionalId}&starts_at=${dateTime}" data-turbo-frame="slideover" data-action="click->agenda-opts#handleTurboClick">
      Click here
    </a>
  `;

  this.dropdownElement.insertAdjacentHTML("beforeend", dropdownContent);
}
```

**Comment by brunoprietog** [comment]
Hi @matias-carpintini, could you give more information on what you are trying to do? Actually, that doesn't seem to be a Turbo issue, but maybe with more information I could help you better.
