### ISSUE TITLE
Turbo.setConfirmMethod is not working

### ISSUE THREAD

**Issue by RsMan-Dev** [hotwired/turbo#1242]
Hi, using turbo v.8.0.4, Turbo.setConfirmMethod is not working like in v.7, keeping using browser's native "confirm"

my link is like: 
```html
<a class="btn" data-turbo-confirm="Are you sure" data-turbo-method="get" href="#">Open Modal</a>
```

tried:
Turbo.setConfirmMethod(() => true)
Turbo.setConfirmMethod(myUsualMethodWorkingOnOlderProjects)

both are just acting like they was not called, showing the native "confirm"

**Comment by pokonski** [comment]
Where do you call `Turbo.setConfirmMethod` in your app?

**Comment by RsMan-Dev** [comment]
@pokonski 
I found the problem
In some projects the method worked, bot in other projects, there was a bug...
All was caused by turbo-rails that was not updated.
I was running turbo and turbo rails, so some issues happened
