### ISSUE TITLE
button with `popovertarget` not triggering in form (Safari 17)

### ISSUE THREAD

**Issue by leevigraham** [hotwired/turbo#1245]
Given the following code (https://codepen.io/leevigraham/pen/RwOYEGM):

```html
<script src="https://www.skypack.dev/view/@hotwired/turbo"></script>
<form>
  <button  type="button" popovertarget="test">Pop in a form</button>
  <div id="test" popover>Test</div>
</form>

<button  type="button" popovertarget="test2">Pop not a form</button>
<div id="test2" popover>Test2</div>
```

*In Safari* (Version 17.3.1) The button in the form does not trigger the popover. 

My guess is the turbo form is catching the button event and not allowing it to bubble up to the browser.

Firefox and Chrome work as expected.

**Comment by paoloricciuti** [comment]
I think this is a bug in safari rather than turbo you can remove turbo and it still doesn't work

**Comment by leevigraham** [comment]
@paoloricciuti Yep you're correct. https://codepen.io/leevigraham/pen/GRbygGj
