### ISSUE TITLE
Blurred input refocusing when turbo replaces blurred input

### ISSUE THREAD

**Issue by ajsharp** [hotwired/turbo#1248]
I'm running into an issue where I'm using a stimulus controller to submit a form based on an input's blur event, and then replacing that form using turbo frames. The problem is when the element is replaced, it **refocuses the input that was just blurred**.

What appears to be happening is:
1. Input is blurred, triggering a stimulus action (form submission)
2. A POST request is submitted via stimulus using `fetch` (requesting a turbo frame response)
3. The server responds with a turbo frame
4. The original dom element is replaced/updated (I've tested both `replace` and `update`, both have the same effect)
5. The form input is re-focused

Note: on the screen on which the `answers/_form` partial is rendered, many instances of this partial are rendered, which means there are many stimulus controllers, forms and turbo frames being update. In other words, there is one html form per `Answer` instance, if that makes sense. I don't see why that would cause this behavior, but thought I'd mention it.

In this video, I'm tabbing out of a field to trigger the blur event, but same thing happens for other methods of blurring. 

https://github.com/hotwired/turbo/assets/12774/fda114eb-8af4-47d9-ae8d-e28cc3edec17

Here's what I'm doing:

```javascript
# answer_controller.js
import { Controller } from "@hotwired/stimulus";
import { post } from "@rails/request.js";

export default class extends Controller {
  connect() {
    this.form = this.element.closest("form");
  }

  submit(e) {
    const body = JSON.stringify({
      value: this.element.value,
    });

    // Set the responseKind to turbo-stream to properly wire up the turbo streams stuff in the controller.
    post(this.form.action, { body, responseKind: "turbo-stream" })
      .then((response) => {
        // handle response here
      })
      .catch((error) => {
        // handle error here
      });
  }
}
```

```ruby
# create.turbo_stream.erb
<%= turbo_stream.update(
  "#{dom_id(@answer.question)}-answer",
  partial: 'answers/form',
  locals: { question: @answer.question, answer: @answer }) %>


# answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  # POST /questions/:question_id/answers
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answer_for(current_user)

    @answer.value = params[:value]
    if @answer.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      # handle errors
    end
  end
end


# answers/_form.html.erb
<%= turbo_frame_tag "#{dom_id(question)}-answer", class: "answer-form" do %>
  <%= form_with model: question,
    url: question_answers_path(question),
    method: :post do |form| %>
    <%= form.label question, question.title %>

    <%= form.text_field :value,
      class: "#{"saved" if answer.saved}",
      data: {
        controller: "answer",
        action: 'blur->answer#submit'
    } %>
  <% end %>
<% end %>
```

**Comment by pinzonjulian** [comment]
> it refocuses the input that was just blurred.

I believe there is a conceptual gap here. Visually, it's appears as if nothing happened, but what's really happening is that the old DOM node is ditched entirely and a new one is put in place. There is no "input that was just blurred" because the whole thing was replaced. In other words, you're expecting Turbo to remember the position of something after it's being "destroyed". 

What you probably want in this case is to use morphing. Give this whole page a read and you may find a way to fix your issue. 

https://turbo.hotwired.dev/handbook/page_refreshes.html#turbo-frames

Also, you can also make a better use of turbo and stimulus. This might help:
- https://stimulus.hotwired.dev/reference/targets
- use `requestSubmit()` to submit the form 


This seems to not be an issue with the library. I recommend closing this issue and asking for support in the community forum at https://discuss.hotwired.dev

**Comment by ajsharp** [comment]
I get what you're saying, but the input _is blurred_ -- that's what kicks off the submit that creates a turbo response that replaces the element. I don't think I'm expecting turbo to remember UI state (I've seen a few issues related to that, this seems like the opposite) -- in effect I'm wanting turbo to respect the DOM event that already happened. It seems like what's happening is it's resetting the DOM state to try to keep what it thinks the state was before it did the replace.

Page morphing seems to be thing with whole page refreshes -- I'm updating a specific part of the dom with turbo frames in response to an xhr request.

**Comment by brunoprietog** [comment]
Hi @ajsharp, replacing one element with another will remove the old element, so there is no longer any reference to it, and that is why the focus is lost. This is how replacing one element with another works natively. The only way to fix this is to use morphing, as suggested by @pinzonjulian.

**Comment by ajsharp** [comment]
> replacing one element with another will remove the old element, so there is no longer any reference to it, and that is why the focus is lost.

The focus is lost because I'm tabbing out of it, manually blurring the input. That's the event that kicks off the submit. The lost focus is not the problem. It's when turbo frames replaces that element, **it refocuses the new element that it just replaced.** I've tested this using both replace and update and the result is the same.

**Comment by nduitz** [comment]
I have the same issue using version @hotwired/turbo 8.0.3; 8.0.4 and 8.0.5

I monkey patched the js package to support `morph` as an action as it was introduced pre `8.0.5` releases since that is the way `turbo-rails` decided to implement and release it in the last version.

So i switched to `morph` instead of `update` and the issue persists. 

Furthermore the behaviour is even more crooked then @ajsharp described. It does not only refocus the previously blurred input but for me it focuses the very first input of the page.

My structure is a bit different though.

I have lot's of forms rendered on my page like this:
```
= turbo_frame_tag id do
  render 'form'

# form.html.haml
= form_for @form do |f|
   = f.input :target, label: false, input_html: { value: number_with_precision(sales_target.target, precision: 2), onblur: 'this.form.requestSubmit()' }
``` 

I switched back to turbo 7.1.1 and everything works like i would expect

**Comment by botandrose** [comment]
@ajsharp @nduitz @brunoprietog Welp, there's yer problem right there: https://github.com/hotwired/turbo/blob/0cc950891adb8075298faa99c34b5e5f988b4fc2/src/core/drive/page_renderer.js#L45

**Comment by edolix** [comment]
I'm experiencing quite the same issue as @nduitz [above](https://github.com/hotwired/turbo/issues/1248#issuecomment-2261115678).

I have a setup like: 

1. Different rows and, for each row, multiple forms and one element that will be replaced
2. On `change` of each form i replace the element on the row with a turbo-stream response
3. When turbo-stream replaces the element (note: is not the submitted form but another element) Turbo automatically puts the focus on the nearest form (_not the very first input of the page_)

**Comment by sauloefo** [comment]
> ### Update
> 
> Ended up the issue was caused by not having unique `id`s for each form' field in the DOM. Didn't realise at first because i got confused by something else on my page 🤦
> 
> I used `dom_id` on those inputs and now the issue is solved! Sorry for the noise here
> 
> Read the issue

I've just solved this issue by proceeding as per @edolix response: ensuring all input elements in my page have unique ids!
Thanks man!!

**Comment by inspire22** [comment]
I've also run into this issue several times.  IMO this.focusFirstAutofocusableElement()  should be removed, I can't think of a use case where this is intended and it definitely causes issues.
