### ISSUE TITLE
Form not displaying errors on page

### ISSUE THREAD

**Issue by indigotechtutorials** [hotwired/turbo#1275]
I have a simple rails form where I am selecting dates for a reservation when I submit I do some validations on the model and then in the controller if the model is not saved then it does a `render :new` I'm expecting the errors to show up on the form but Instead I receive an empty array and see this error in the console
![Screenshot 2024-06-08 164525](https://github.com/hotwired/turbo/assets/63070125/489079bd-c455-4bb3-9628-98d0437a8bd5)

This is the code in my controller
```
def create 
      @booking = @listing.bookings.new(bookings_params)
      @booking.user = current_user
      if @booking.save
        redirect_to payment_listing_booking_path(@listing, @booking), notice: "Your stay was booked at #{@listing.title} for #{@booking.checkin_date.strftime("%d/%m/%Y")}"
      else
        render :new
      end
    end
```

**Comment by indigotechtutorials** [comment]
I was able to resolve this by adding `status: :see_other` on the `render :new` but this is weird because I have never had to do this before with turbo.

**Comment by brunoprietog** [comment]
Hi @indigotechtutorials, Turbo expects a form submission to be responded to with a redirect, or with some 4xx or 5xx error. In this specific case, you should actually respond with something like this:

```ruby
render :new, status: :unprocessable_entity
```

It's explained in more detail [here](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission). Also, if you try generating a scaffold in Rails you will see that it's done in the same way.
