### ISSUE TITLE
It's unfortunate that Turbo overloads the concept of "action", is it too late to rename "Turbo actions"?

### ISSUE THREAD

**Issue by krschacht** [hotwired/turbo#1293]
Multiple times now as I'm helping a Rails developer make sense of Hotwire, I've seen them get tripped up on the "update" and "replace" actions of Turbo. One of the core reasons is because these are called "actions" but they have nothing to do with controller actions, this is referring to how the browser history is changing. But in the same view you can have `<form action="..."` right near a `<a link=".." data-turbo-action="...` so we're referring to actions quite a lot.

As we are discussing and reasoning about an application, it's unfortunate that the word "action" now means two very different things. We end up using this word a lot. What is another concept which subsumes the three Turbo advance, replace, restore? We already use `method` to refer to get vs post. Maybe "Turbo transitions" so `data-turbo-transition="replace"`. Possible other words: Turbo behavior, Turbo procedure, Turbo operation, ...

It's probably too late to change this, but I thought it was at least worth bringing up before Rails 8 if finished. It's unfortunate how much confusion I see this causing with new developers.

**Comment by dhh** [comment]
Yeah, some words like that, same with object or record, is used for many different things. But the ship has sailed on naming. Not going to change this now.
