### ISSUE TITLE
Please allow rendering after successful POST form submissions

### ISSUE THREAD

**Issue by omitter** [hotwired/turbo#1297]
Currently Turbo ignores renders after a form submission, unless it is accompanied by a 4xx/5xx status code.

The reason for this is (afaik) that the URL could be reloaded by the user as a GET request, which could potentially result in a "page not found" error. Maybe there's even more to it?

But there are other valid reasons to have a POST request render rather than redirect, besides error handling!

For instance a confirmation screen for a booking should be submitted by POST, since I don't want the user to copy the URL and paste it later again. So the idea is a POST request, that renders a page with the confirmation details and a new form that will submit to the final booking page. Even more, if the form was to contain images, it wouldn't even be possible to use a GET request. Custom non-sharable preview pages with file uploads would be a similar use case.

So, could you maybe give us an option to disable the `mustRedirect` logic? You already have [the code](https://github.com/hotwired/turbo/blob/664695762f152b744002f83f76d196d458f9030f/src/core/drive/form_submission.js#L30), but I can't find a way to disable the `mustRedirect` logic from the outside. Currently I have to a manual non-Turbo request for confirmation/preview screens, which defeats the idea of writing no JavaScript, or send an wrong status code, which makes log analysis harder and makes me feel really uncomfortable.

**Comment by 4lllex** [comment]
you could render with status `201` as a workaround.

**Comment by omitter** [comment]
Oh, I didn't think of this. Currently they check only for =200, so >=201 works great.
Thanks!

**Comment by fa11enangel** [comment]
@omitter please close the issue

**Comment by omitter** [comment]
Hm, I'm not sure this workaround is really the best solution.
But it's okay for me, as long as it doesn't stop working in the future.
