### ISSUE TITLE
No history state pushed when adding turbo frames

### ISSUE THREAD

**Issue by gunnarmorling** [hotwired/turbo#130]
When adding `<turbo-frame id="shell">...</turbo-frame>`, HTTP requests are issued via Turbo, but no state is changed to the browser history, i.e. the contents of the address bar doesn't change.

**Comment by seanpdoyle** [comment]
Is this related to https://github.com/hotwired/turbo/issues/50?

**Comment by gunnarmorling** [comment]
Yes, perhaps it is. I was thinking #50 is different due to all the video-related things it mentions, but reading it again, this is exactly what I'm observing:

> Use the new Turbo Frames feature (which works), but then the URL doesn't get updated

So is this a known limitation then? Using `<turbo-frame>` makes a huge difference for me with Firefox in terms of perceived performance (in fact, initially I thought Turbo isn't working at all when using it without `<turbo-frame>`  in FF, as it didn't seem to make a difference), so it'd be very desirable to use. But the lack of history update makes it not really usable atm.

**Comment by seanpdoyle** [comment]
> So is this a known limitation then? 

I believe this behavior is a design decision. 

I'm closing this issue in favor of #50. If you have further thoughts, please share them there.

**Comment by gunnarmorling** [comment]
Ok, thanks for clarifying.

> I believe this behavior is a design decision.

I wonder why, though? This makes Turbo essentially unusable for me on
Firefox, as I have the choice between not using a frame, thus having the
correct history but same experience as without Turbo, or using Frames, much
better experience, but incorrect history :( In any case, thanks a lot for
your efforts on working on this library, appreciate it.
