### ISSUE TITLE
`data-turbo-permanent` does not work on Favicon

### ISSUE THREAD

**Issue by sotasan** [hotwired/turbo#1313]
Hey,

on my [Website](https://sotasan.com/), I have a favicon (`rel="icon"`) that gets replaced with an animated version with JavaScript, but after a Page navigation it gets reset to the static version. I have tried using `data-turbo-permanent` with an `id` attribute, but it gets replaced nonetheless.

Is there any other way to ignore this element with Turbo?

**Comment by pedroaugustofsilva** [comment]
Hi @sotasan.

The favicon (the icon on the browser's tab) is not being replaced here. It stays static since the first page load.

Could you confirm?

**Comment by sotasan** [comment]
Hey,

yes I am sorry, my fault. I had temporarily removed those lines. I added them now back in. Ah and favicon gifs only work in Firefox.
