### ISSUE TITLE
Hotwire static site/ blogging framework

### ISSUE THREAD

**Issue by anthonycorletti** [hotwired/turbo#1320]
I'd like to gauge interest in a hotwire based static site/ blogging framework.

I've been using bun, turbo, remark, rehype, and tailwind for [my blog/ website](anthonycorletti.com) and I am absolutely loving how simple it is.

I'm curious if anyone has done something similar, and if anyone is interested in using a simple static site framework?

Cheers.

**Comment by dhh** [comment]
That sounds like a fun idea. Have fun exploring it! But using the discord or similar discussion forum for further elaboration is better than the issue tracker we use for bug tracking.
