### ISSUE TITLE
Morphing not working on search form with the default `advance` action

### ISSUE THREAD

**Issue by jdrosales17** [hotwired/turbo#1339]
Hi,

I was recently playing with morphing on a Rails application, specifically with a search form which made a GET request to the same `index` action of the page. I found that morphing was not working unless I defined the attribute `data-turbo-action="replace"` on the form element.

Going through the source code, I found that Turbo considers a page refresh only when the `visit.action` is `replace`.

https://github.com/hotwired/turbo/blob/ea54ae5ad4b6b28cb62ccd62951352641ed08293/src/core/drive/page_view.js#L59

I was wondering if that made sense, since in the search request I was doing I may want to preserve the current location and push a new one so that I'm able to go back to previous searches, and that is not possible with the `replace` action.

This problem could also happen when applying filters on an `index` page as it would have the same form doing a GET request with the filter params to the same `index` action.

To give some context these were the versions I was working with:

- `rails` -> 7.0.8
- `turbo-rails` -> 2.0.11

**Comment by seanpdoyle** [comment]
Thanks for opening this issue. This feels related to https://github.com/hotwired/turbo-site/pull/178, particularly: https://github.com/hotwired/turbo-site/pull/178#issuecomment-1971125469 (which includes a reproduction script).

I'm not sure of the best path forward. @jdrosales17 would you mind closing this issue, then chiming in on the discussion thread in https://github.com/hotwired/turbo-site/pull/178#discussion_r1507567905?
