### ISSUE TITLE
Why no compatibility with Laravel? 

### ISSUE THREAD

**Issue by toxifiedmatrix** [hotwired/turbo#134]
I am trying to use @Hotwired/Turbo in my Laravel project instead of Turbolinks. I have successfully installed the package, but am unable to  `import * as Turbo from "@hotwired/turbo"`. Is it even compatible with the Laravel framework?

**Comment by shadowtime2000** [comment]
What is the error you are getting?

**Comment by toxifiedmatrix** [comment]
When I am using `import * as Turbo from "@hotwired/turbo"` instead of the `require("turbolinks").start()` and running `npm run dev` to re-compile my assets, I am getting the following error.

> ERROR in ./resources/js/app.js 5:0-41
Module not found: Error: Can't resolve '@hotwired/turbo' in 'C:\xampp\htdocs\Management\resources\js'

**Comment by toxifiedmatrix** [comment]
I guess the problem is that the following code is in typescript language `import * as Turbo from "@hotwired/turbo"`, I need to write it in javascript. What can I do to make this work in Laravel?

**Comment by shadowtime2000** [comment]
@toxifiedmatrix Thats not the problem, you need to configure Laravel to allow you to import modules from NPM

**Comment by toxifiedmatrix** [comment]
@shadowtime2000 I used `npm i @hotwired/turbo`, in my package.json `"@hotwired/turbo": "^7.0.0-beta.3"` has been added under dependencies. What should I do further, in order to make it work, please guide me as I am new to laravel. Help is really appreciated. 🤔

**Comment by shadowtime2000** [comment]
@toxifiedmatrix I don't know how to use Laravel. Your going to have to look through the Laravel docs urself on how to bundle JS which is what you need to do to get it to work

**Comment by toxifiedmatrix** [comment]
@shadowtime2000 In laravel we use `npm run dev` to bundle the js and css, as I am on webpack. I am running the same command, still the error.

**Comment by shadowtime2000** [comment]
I think Laravel uses a custom build of Webpack or something. Anyways, the problem seems to arise fromt he fact that it isn't looking in the `node_modules` folder. Still, I think this is a Laravel bundler problem and not really relating to Turbo so I think this should be closed and you should open an issue on their repo.
