### ISSUE TITLE
Passing a submitter to form.requestSubmit has no effect when Turbo is active

### ISSUE THREAD

**Issue by janklan** [hotwired/turbo#1343]
As per https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit, if a submit button is passed to `requestSubmit()` method, this button is deemed to be the button the user clicked. 

For context: 

---

In my use case I have two submit buttons, one carrying value "save" and the other "preview". The server varies the form data processing depending on what is the submit button the user clicked. 

The form also includes a checkbox with `onchange="var button = this.form.querySelector('button[type=submit][value=preview]'); console.debug(button); this.form.requestSubmit(button);)"`. Its purpose is to submit the button when the checkbox state changes, as if the user clicked the preview button.

The `var button = ...; console.debug(button)` is there to make sure the button node is found and therefore passed to `requestSubmit`.

---

When the entire form is in a Turbo Frame, clicking the Preview button works fine, but invoking `requestSubmit` via the checkbox onchange event doesn't. 

With everything else unchanged, if I turn Turbo off by adding `data-turbo="false"` to one of the parent elements, clicking the checkbox submits the form correctly, as if the user clicked the preview button. 

This makes me think that Turbo intercepts the requestSubmit event just fine, but failes to pass the submitter further. 

Am I missing something or is it broken? 

My current workaround is calling `button.click()` instead of `this.form.requestSubmit(button)`, which works, but doesn't feel right. 

---

I'm using Turbo 7.3.0

**Comment by seanpdoyle** [comment]
Thank you for opening this pull request. 

The behavior you've described is surprising. There's test coverage in the suite that aims to exercise a similar use case.

For example, there is some fixture HTML elements that declare a similar attribute-based listener (the test uses `onclick` instead of your example's `onchange`):

https://github.com/hotwired/turbo/blob/ea54ae5ad4b6b28cb62ccd62951352641ed08293/src/tests/fixtures/form.html#L325-L326

Here's the corresponding test case:

https://github.com/hotwired/turbo/blob/ea54ae5ad4b6b28cb62ccd62951352641ed08293/src/tests/functional/form_submission_tests.js#L328-L335

If you're familiar with Ruby and Rails, could you please modify the [following script](
https://github.com/hotwired/turbo-rails/blob/main/bug_report_template.rb) so that it passed when executed with `ruby bug.rb`:

<details>
  <summary>Download as `bug.rb`, modify, then execute with `ruby bug.rb`</summary>

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "propshaft"
  gem "puma"
  gem "sqlite3", "~> 1.4"
  gem "turbo-rails"

  gem "capybara"
  gem "cuprite", require: "capybara/cuprite"
end

ENV["DATABASE_URL"] = "sqlite3::memory:"
ENV["RAILS_ENV"] = "test"

require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
require "action_view/railtie"
# require "action_mailer/railtie"
# require "active_job/railtie"
require "action_cable/engine"
# require "action_mailbox/engine"
# require "action_text/engine"
require "rails/test_unit/railtie"

class App < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f

  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"
  config.consider_all_requests_local = true
  config.action_cable.cable = {"adapter" => "async"}
  config.turbo.draw_routes = false

  Rails.logger = config.logger = Logger.new($stdout)

  routes.append do
    root to: "application#index"
  end
end

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :messages, force: true do |t|
    t.text :body, null: false
  end
end

class Message < ActiveRecord::Base
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers

  class_attribute :template, default: DATA.read

  def index
    render inline: template, formats: :html
  end
end

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :cuprite, using: :chrome, screen_size: [1400, 1400], options: {js_errors: true}
end

Capybara.configure do |config|
  config.server = :puma, {Silent: true}
  config.default_normalize_ws = true
end

require "rails/test_help"

class TurboSystemTest < ApplicationSystemTestCase
  test "reproduces bug" do
    visit root_path

    assert_text "Loaded with Turbo"
  end
end

__END__
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <script type="importmap">
      {
        "imports": {
          "@hotwired/turbo-rails": "<%= asset_path("turbo.js") %>"
        }
      }
    </script>

    <script type="module">
      import "@hotwired/turbo-rails"

      addEventListener("turbo:load", () => document.body.innerHTML = "Loaded with Turbo")
    </script>
  </head>

  <body>Loaded without Turbo</body>
</html>
```

</details>

**Comment by janklan** [comment]
@seanpdoyle I went on to do a reproducer and couldn't reproduce it. Now I went back to the code where it didn't work yesterday, assuming something else in that context is interfering with Turbo's behaviour, and, facepalm, I can't reproduce it there either. It all works good now. I have no idea what's going on, sorry to waste your time. I'll re-open if I have something better for you.
