### ISSUE TITLE
Accept in form submissions should include at least "text/html"

### ISSUE THREAD

**Issue by derkoe** [hotwired/turbo#141]
This commit 09c0f4acd4410ca4e48d9dc89db2526a46de30d4 breaks content negotiation on the server. 

Before the `Accept` header was `text/vnd.turbo-stream.html, text/html, application/xhtml+xml` - now it is only `text/vnd.turbo-stream.html`. 

This breaks servers not explicitly coded to Turbo Streams looking at the `Accept` header and finding no acceptable content type.

@seanpdoyle was this intentional?

**Comment by sstephenson** [comment]
Thank you for the report!
