### ISSUE TITLE
v7.0.0-beta.3 throws Response has no matching <turbo-frame> on console

### ISSUE THREAD

**Issue by brunodrugowick** [hotwired/turbo#144]
I had a working sample that stopped after this `v7.0.0-beta.3` release. I'm using the latest over CDN so I noticed.

If I change back to any prior `v7.0.0-beta` version my code works. On the `v7.0.0-beta.3` I get:

```
Response has no matching <turbo-frame id="beverages_list"> element turbo.js:740:13
    extractForeignFrameElement https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:740
    loadResponse https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:641
    formSubmissionSucceededWithResponse https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:700
    requestSucceededWithResponse https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:483
    receive https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:351
    perform https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:337
    start https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:445
    formSubmissionIntercepted https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:669
    submitBubbled https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:538
    (Async: EventListener.handleEvent)
    start https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:546
    connect https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:606
    connectedCallback https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:55
    <anonymous> https://cdn.skypack.dev/-/@hotwired/turbo@v7.0.0-beta.3-tvFsO8IW4m2YjmlcLZZq/dist=es2020/@hotwired/turbo.js:931
```
I'm not sure if I'm doing something wrong (I followed https://turbo.hotwire.dev/handbook/streams) that I didn't notice but I wanted to report early on.

My page looks like this:

```html
<!-- omitted irrelevant stuff -->
<section>
    <h1>Showcase how to add to part of a page</h1>

    <turbo-frame id="beverages_list">
        <form action="/beverages/any" method="post">
            <button type="submit">Add beverage</button>
        </form>
        <div id="beverage_1"><p>1 - Coffee</p></div>
    </turbo-frame>

</section>
```

And my server response to the POST method is: 
```html
<!-- omitted irrelevant stuff -->
<body>
<h1>A Beverage (page or Turbo component)</h1>
<turbo-stream action="append" target="beverages_list">
    <template>
        <div id="beverage_8">
            <p>
                <span>8</span> - <span>Coffee</span>
            </p>
        </div>
    </template>
</turbo-stream>
</body>
```

_Originally posted by @brunodrugowick in https://github.com/hotwired/turbo/issues/31#issuecomment-761569577_

**Comment by brunodrugowick** [comment]
A sample of the problem I mentioned above: https://hotwire-v7b3-error.herokuapp.com/

**Comment by seanpdoyle** [comment]
Thank you for opening this issue @brunodrugowick.

Does your response include a `<turbo-frame id="beverages_list ">` to match the element in the page making the request?

**Comment by khash** [comment]
@brunodrugowick I believe you'd need to wrap your response in the same `turbo_frame_tag` as well

**Comment by tleish** [comment]
The error is valid.  If you intend to replace the `turbo-frame` content with the response, then then html response needs to include `turbo-frame` with a matching ID.  If you want to append to an element on the page (which appears you do), then add  add a different target to `turbo-frame` (e.g. `target="_top"`).

```html
<turbo-frame id="beverages_list" target="_top">
```

**Comment by brunodrugowick** [comment]
Ok, I'll answer one by one.

@seanpdoyle :

> Does your response include a <turbo-frame id="beverages_list"> to match the element in the page making the request?

No. I thought I was supposed to reference the target element on the `<turbo-stream action="append" target="beverages_list">`. You can also see this response on the browser, on the sample I added. I based this on the [handbook](https://turbo.hotwire.dev/handbook/streams) and, again, it works on any version prior to `v7.0.0-beta.3`. Here's my `index.html` to the left and the response to the right:
![image](https://user-images.githubusercontent.com/7481200/106388620-2aec5700-63be-11eb-9483-33b3acfa72bc.png)

> Is this a Rails application?

No. A Spring Boot (Java).

> What is the response content type that's rendering the HTML that contains the <turbo-stream> element? Is the response a full HTML document, or is its structure limited to the stream element? What is the HTTP status code in your response?

The following pictures may answer all those questions:
![image](https://user-images.githubusercontent.com/7481200/106388872-2ffdd600-63bf-11eb-85c1-91e8aa378c55.png)
![image](https://user-images.githubusercontent.com/7481200/106388908-51f75880-63bf-11eb-8668-13ceca3012f8.png)

**Comment by brunodrugowick** [comment]
> @brunodrugowick I believe you'd need to wrap your response in the same `turbo_frame_tag` as well

That's not what I get from the [documentation](https://turbo.hotwire.dev/reference/streams) and, also, that's not what I get from any version before `v7.0.0-beta.3`.

See:

![image](https://user-images.githubusercontent.com/7481200/106389926-bc5ec780-63c4-11eb-94c3-fbb94f7c20b5.png)

"Appends the content within the template tag to the container designated by the target dom id."

**Comment by brunodrugowick** [comment]
> If you want to append to an element on the page (which appears you do), then add add a different target to `turbo-frame` (e.g. `target="_top"`).

That doesn't work. See the [documentation](https://turbo.hotwire.dev/reference/streams#append). That's what I'm doing and, again, works on `v7.0.0-beta.2` and doesn't work on `v7.0.0-beta.3`

**Comment by tleish** [comment]
> That doesn't work. See the [documentation](https://turbo.hotwire.dev/reference/streams#append). That's what I'm doing and, again, works on `v7.0.0-beta.2` and doesn't work on `v7.0.0-beta.3`

I don't know about `v7.0.0-beta.3`, but I tested a slight modification of your example using `target="_top"` with `v7.0.0-beta.4` and it works for me.

**Comment by seb-jean** [comment]
I have the same issue :

`Response has no matching <turbo-frame id="my_stuff"> element`

**Comment by brunodrugowick** [comment]
@seb-jean and others having the same issue, this may help you.

I fixed my problem investigating and debugging [another project](https://github.com/odrotbohm/spring-playground/blob/main/hotwire-spring-boot/hotwire-spring-boot/src/main/java/de/odrotbohm/spring/hotwire/webmvc/Hotwire.java#L30-L31). 

But the "solution" is also stated on the documentation [here](https://turbo.hotwire.dev/handbook/drive#streaming-after-a-form-submission). This was changed on [this commit from Jan 18](https://github.com/hotwired/turbo-site/commit/699f9fc15a2ad8a9837925b859edd95459d5c5b6). And is mentioned on the [beta-3 changelog](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.3) on Jan 12.

I basically changed my content-type from `text/html; turbo-stream` to `text/vnd.turbo-stream.html` on my view resolver, which is required on `v7.0.0-beta.3+`:

```java
@Bean
public ThymeleafViewResolver viewResolver(SpringTemplateEngine templateEngine) {
    ThymeleafViewResolver viewResolver = new ThymeleafViewResolver();

    viewResolver.setContentType("text/html; turbo-stream");
    viewResolver.setCharacterEncoding(StandardCharsets.UTF_8.name());
    viewResolver.setOrder(0);
    viewResolver.setViewNames(new String[] { "*stream*" });
    viewResolver.setTemplateEngine(templateEngine);

    return viewResolver;
}
```

And everything works fine now.

Thanks! And remember, folks: [RTFM](https://en.wikipedia.org/wiki/RTFM). <-- also a note for myself :laughing:
