### ISSUE TITLE
Support data-turbo-frame attribute along with a custom tag

### ISSUE THREAD

**Issue by ivangretsky** [hotwired/turbo#148]
Good day!

Thanks for this project. It brings so much fun back into the game!

Could turbo work not only with custom tag markup, but with the data- attributes as well? I know some people in this niche would feel themselves being "too tightly coupled" to the framework when having to use these non-standard tags. Myself included. So this little thing could be very important psychologically)

**Comment by brunoprietog** [comment]
Hi @ivangretsky, I don't see that it provides enough value to justify the additional complexity of maintaining a new API. Closing for now
