### ISSUE TITLE
turbo-frame with src attribute is loaded multiple times

### ISSUE THREAD

**Issue by jcoyne** [hotwired/turbo#150]
My page has 3 `turbo-frame`s each with a src:
```
<turbo-frame id="delete_work_3" src="/works/3/delete_button"></turbo-frame>
<turbo-frame id="delete_work_1" src="/works/1/delete_button"></turbo-frame>
<turbo-frame id="delete_work_3" src="/works/2/delete_button"></turbo-frame>
```

Each of these return a sensible response.  However the page immediately loads each of these 5 times (removed some from the screenshot for brevity).

<img width="389" alt="Screen Shot 2021-02-02 at 11 25 24 PM" src="https://user-images.githubusercontent.com/92044/106702467-06ef6800-65ae-11eb-9a1c-c2996dd4a62a.png">

An example response looks like this:
```xml
<turbo-stream action="replace" target="delete_work_3"><template><turbo-frame id="delete_work_3"></turbo-frame></template></turbo-stream>
```

**Comment by jcoyne** [comment]
I tried this on a new rails app from scratch but I couldn't duplicate this problem, so I'm thinking I must have something misconfigured, but I can't figure out what it might be.

**Comment by stgm** [comment]
Does the new rails app serve the exact same response?

It seems you're mixing streams and frames (given the example above), which I wouldn't normally expect. Is that intentional?

**Comment by stgm** [comment]
The minimum response should be `<turbo-frame id="delete_work_3"></turbo-frame>` to allow Turbo Frames to replace the content of the current frame (that's what Frames is able to do). You can place any content between those tags and it will be shown instead of the previous content.

**Comment by jcoyne** [comment]
@stgm I made that change and that is much simpler (Thank you! ❤️ ), however that doesn't resolve the problem of multiple requests.

**Comment by stgm** [comment]
Two things that spring to mind that could cause extraneous requests:

- I'm not sure what behavior results should you manage to import Turbo twice (maybe this?), and
- setting the `src` attribute of the frame from JS will also initiate a new request

**Comment by stgm** [comment]
But if you tell a bit more about the context it may be easier to spot misconceptions ;-) E.g. your code mentions a button but you are currently using the Turbo Frames feature that automatically "lazy-loads" a frame.

**Comment by jcoyne** [comment]
The buttons are in the lazy loaded frame iff the current user has the authorization to do the action the button provides.

We are using this approach because we can stream updates to the page to everyone, but not everyone is authorized to do the actions.

**Comment by stgm** [comment]
It might be related to #145 and it could be a regression from the previous beta 3 of Turbo. You might have a try with that version to be certain that you're not chasing your own tail!

**Comment by codearbor** [comment]
Not sure if this is related, my page has a turbo-frame with src that loads a sub section.

`<turbo-frame id="sub" src="Sub.html"></turbo-frame>`

Then navigating to a different page that does not have any turbo-frame elements still triggers the request for sub.html.

![Page1](https://github.com/codearbor/turbo-frame-test/raw/master/screenshots/Page1.png)
After loading the Page1, the Sub.html is loaded async. Clicking on Page2 loads:

![Page2](https://github.com/codearbor/turbo-frame-test/raw/master/screenshots/Page2.png)

Notice the last Sub.html request after Page2.html is loaded. Page2.html does not contain any turbo-frame elements.

Here is repo: https://github.com/codearbor/turbo-frame-test/

My understanding after debugging is that this extra request triggers during snapshot creation phase of the current loaded page, Page1. I may be wrong.

This occurs on beta 4, but the same is not present in beta 3

**Comment by tleish** [comment]
Oh wow.  Fetching turbo-frame URL on every turbo leave would result in quite a few additional server responses.

It appears the problem occurs inside of the `PageSnapshot#clone`. 

Turbo Beta3

```javascript
// Snapshot
clone() {
  const { bodyElement } = Snapshot.fromHTMLString(this.bodyElement.outerHTML);
  return new Snapshot(this.headDetails, bodyElement);
}
```

Turbo Beta4

```javascript
// PageSnapshot
clone() {
  return new PageSnapshot(this.element.cloneNode(true), this.headSnapshot)
}
```

Using  `cloneNode` reloads turbo-frame, whereas the previous `outerHTML` does not.

It also appears a similar problem was found before and was fixed with a commit in 2019 using `Snapshot.fromHTMLString` and `outerHTML`.

see: [Prevent snapshots from loading media and upgrading custom elements un… · hotwired/turbo@5dfc79e · GitHub](https://github.com/hotwired/turbo/commit/5dfc79ee2feba441ea9c9b486009d08336e78d76)

```diff
clone(): Snapshot {
-    return new Snapshot(this.headDetails, this.bodyElement.cloneNode(true))
+    const { bodyElement } = Snapshot.fromHTMLString(this.bodyElement.outerHTML)
+    return new Snapshot(this.headDetails, bodyElement)
}
```

Then it was then change from `outerHTML` back to `cloneNode`:

See: [HeadDetails -> HeadSnapshot · hotwired/turbo@caa3bba · GitHub](https://github.com/hotwired/turbo/commit/caa3bba0d6326d867d598e9d53068f308609072f)

```diff
clone() {
- const { bodyElement } = PageSnapshot.fromHTMLString(this.bodyElement.outerHTML)
-   return new PageSnapshot(this.headDetails, bodyElement)
-  }
+ return new PageSnapshot(this.rootNode.cloneNode(true), this.headSnapshot)
}
```

@sstephenson  — is there a specific reason you replaced `outerHTML` with `cloneNode` that changing back to outerHTML might break?

**Comment by tleish** [comment]
Um, what happened to the comment by @codearbor?

**Comment by javan** [comment]
This issue is fixed in the yet-to-be-merged [*prevent-frames-from-loading-in-snapshots* branch](https://github.com/hotwired/turbo/compare/prevent-frames-from-loading-in-snapshots).

**Comment by tleish** [comment]
Got it, thanks for the heads up.  I closed my pull request.

**Comment by codearbor** [comment]
I had taken out my comment as I realised that there was already a PR fixing the issue.

**Comment by sstephenson** [comment]
This is fixed in main and will go out in the next beta release.
