### ISSUE TITLE
multiple turbo-frames on page with same id

### ISSUE THREAD

**Issue by blynx** [hotwired/turbo#151]
Hi,

currently we are using a custom element which does some similiar tricks as turbo-frame does. Though, when switching to turbo-frame, in one case we'd have two turbo-frames with the same id. There is a long list and we'd like to provide two entry points for a sequence of forms.

It basically works, but one would rather like to avoid having duplicate ids on a page.

Do you think this is something worth considering for an update?

kind regards
Steffen

**Comment by mxlje** [comment]
Related to #56 ?

**Comment by blynx** [comment]
Not quite, as I understand #56, there are two turbo-frames in the response and in the origin - and the response shall update both turbo-frames in the origin.

My example would be simplier actually: There are two identical turbo-frames on the origin page. They point to the same target. Yet, the target only has one turbo-frame. Thats why the origin turbo-frames have to share the same id.

Technically it works fine! The "problem" ist just that you have 2 identical ids used in the same page. Which is ... "kinda not allowed". 
A solution could be to change the id in the target page via query parameter or so.

But I am really not sure if this is a significant enough drawback to change anything - hence my question if you think this is even worth considering

**Comment by tleish** [comment]
You should generally avoid duplicate ids.  Not sure why you have a duplicate on the same page, but what about creating 2 different ids and having the return HTML response include 2 turbo-frames which reference the 2 ids but contain the same content?

Or a stimulus controller which watches for changes and syncs the content after change.

**Comment by blynx** [comment]
Yes, the duplicate ids were my concern. It just arose from the circumstances when switching to the new Turbo.
The second turbo-frame might actually be a good hint! Not actually displaying the second turbo-frame, but hiding it in a <template> !? 🧐

**Comment by seb-jean** [comment]
Hello, have you found a solution to this issue?

**Comment by blynx** [comment]
Not yet, that topic is not top prio here right now. I might have a look into it some time again but cant really tell or make any promises unfortunately.

Maybe for a better understanding, the situation in something like a diagram:

```
 Current Page            │  Remote Pages...                         
┌──────────────────────┐ │ ┌─────────────┐ │ ┌─────────────┐ │      
│ <a id="_">Entry</a>  │ │ │             │ │ │             │ │      
└──────────────────────┘ │ │             │ │ │             │ │      
                         │ │<form id="_">│ │ │<form id="_">│ │      
   Lots of Content...    │ │   Step 1    │ │ │   Step N    │ │      
                         │ │   </form>   │ │ │   </form>   │ │      
┌──────────────────────┐ │ │             │ │ │             │ │      
│ <a id="_">Entry</a>  │ │ │             │ │ │             │ │ ...  
└──────────────────────┘ │ └─────────────┘ │ └─────────────┘ │      
                         │                 │                 │                                  
```
Two Entrypoints for the "same path". The bordered rects are the turbo frames.
(Though, a completely different solution could be to solve this with another UX or so)

I would still just leave this here in case you/anyone consider this a worthy issue. : )

**Comment by jbennett** [comment]
I think I'm in a similar situation. I have a page that displays multiple lists of the same resource with different filtering params (pinned and not pinned). So on `/feed` I have two turbo frames loading `/items` and `/items?pinned=true`. On `items#index` I am wrapping the items in a `turbo_frame_tag :items`

On the feed page I think I want be able to do a `turbo_frame_tag :pinned_items, src: '/items?pinnned=true', connect_to_remote_id: :items`. This would let us optionally map different id's in.

(I think from the source)[https://github.com/hotwired/turbo/blob/4593d06ce58d17af5b17495ad8524eaa9bc2f5d2/src/core/frames/frame_controller.ts#L469], it's currently hardcoded to always use the id.

Would this be a good thing to allow people to customize? I'd be happy to look into this deeper. Any suggestion on for a param name or would everyone be happy with `connect_to_remote_id` 😜

**Comment by pfeiffer** [comment]
> I think I'm in a similar situation. I have a page that displays multiple lists of the same resource with different filtering params (pinned and not pinned). So on `/feed` I have two turbo frames loading `/items` and `/items?pinned=true`. On `items#index` I am wrapping the items in a `turbo_frame_tag :items`

In this case, why not make the ID of the wrapping frame on the index action dynamic and based on if ` pinned=true`, and have two turbo frames with distinctive IDs on the summary page?

**Comment by jbennett** [comment]
The index page would have to know what the id would have to be in every situation. This lets the index be dumb and the called do something if needed. And this is just the simple example. What if you are filtering based on multiple values? #pinned_and_named_bob_but_not_completed_items doesn’t roll off the tongue 😜On Mar 24, 2023, at 1:08 AM, Mattias Pfeiffer ***@***.***> wrote:﻿

I think I'm in a similar situation. I have a page that displays multiple lists of the same resource with different filtering params (pinned and not pinned). So on /feed I have two turbo frames loading /items and /items?pinned=true. On items#index I am wrapping the items in a turbo_frame_tag :items

In this case, why not make the ID of the wrapping frame on the index action dynamic and based on if  pinned=true, and have two turbo frames with distinctive IDs on the summary page?

**Comment by brunoprietog** [comment]
> On the feed page I think I want be able to do a turbo_frame_tag :pinned_items, src: '/items?pinnned=true', connect_to_remote_id: :items. This would let us optionally map different id's in.

You could do something similar using a parameter in the Turbo frame url, for example: `/resources/1?frame?someframe`.

Then you could read it from the server and know what id the Turbo frame to be rendered should have.

**Comment by brunoprietog** [comment]
Anyway, having 2 elements with the same ID is malformed HTML.
