### ISSUE TITLE
data-turbo-preview not working in beta.4

### ISSUE THREAD

**Issue by vwong** [hotwired/turbo#159]
In beta.4, the attribute `data-turbo-preview` is never present on `document.documentElement` even when visiting a cached page. It was working fine in beta.3.

For example, I create a Stimulus controller as follows. Whenever I visit a cached page in beta.3, I would get `true` followed by `false`. But in beta.4, I would get `false` twice.

```
import { Controller } from "stimulus"

export default class extends Controller {
  connect () {
    console.log(document.documentElement.hasAttribute("data-turbo-preview"))
  }
}
```

The caching mechanism itself works fine though.

**Comment by seanpdoyle** [comment]
@vwong thank you for opening this.

Is the behavior restored by https://github.com/hotwired/turbo/pull/162?

**Comment by vwong** [comment]
@seanpdoyle Yep, that did it. Looking forward to the fix released. Thanks!

**Comment by seanpdoyle** [comment]
I believe this was fixed as part of https://github.com/hotwired/turbo/pull/169/, which shared implementation change overlap with https://github.com/hotwired/turbo/pull/162.
