### ISSUE TITLE
Appending rows into HTML table via frames/streams is breaking the table markup

### ISSUE THREAD

**Issue by oleksandr** [hotwired/turbo#160]
Example of a table:

```
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
            </tr>
            </thead>
            <tbody>
            <turbo-frame id="categories-list" src="/categories">
                <tr class="table-light">
                    <td colspan="2">Loading categories...</td>
                </tr>
            </turbo-frame>
            </tbody>
        </table>
```

The fetch response contains the following:

```
<turbo-frame id="categories-list">    
 <tr>
    <th scope="row">3</th>
    <td>Larry the Bird</td>
</tr>
<tr>
    <th scope="row">3</th>
    <td>Larry the Bird</td>
</tr>
</turbo-frame>
```

This results in a table as show on the image below - the frame moves up the table as it was initially.

![image](https://user-images.githubusercontent.com/183183/106966857-67b1a880-6746-11eb-8f77-f97d6c74ab7b.png)

**Comment by seanpdoyle** [comment]
Is this related to https://github.com/hotwired/turbo/issues/48?

**Comment by oleksandr** [comment]
@seanpdoyle indeed! I'm using hotwire without RoR actually, so didn't notice... Exactly the same issue!

**Comment by seanpdoyle** [comment]
Thank you for opening it. I'm going to close it in favor of the guidance provided by #48. `<table>` elements are very particular about their descendants.
