### ISSUE TITLE
Back button not working on a specific page (with query parameter)

### ISSUE THREAD

**Issue by Hrishikesh-K** [hotwired/turbo#163]
Hello.

Turbo seems to be working exceptionally fine for me and I've managed to optimise by JS a bit as as to not flood the browser with event listeners and other stuff. However, I seem to be having problem on a specific page. I've made a client-side search using FlexSearch.js and it renders a link to the search result using JS. Clicking on the link takes me to the page which is all good, but clicking on back button doesn't work. The title of the page is reverted correctly and even the URL is changed, but the page's content remains same. What might be happening?

Here's a demo to test: https://602005f57b473c0008fe6bd5--hrishikeshk.netlify.app/search/?q=Dropbox. A search query has already been added. So, now if you click on 'Read more' button and then press the Back button, you can see the thing I'm describing. One thing might be a possibility that since the URL uses query parameters, it's causing an issue. Because if you remove the query parameter (https://602005f57b473c0008fe6bd5--hrishikeshk.netlify.app/search/) and navigate to some other page, and then press the back button, the page loads fine.

Kindly let me know how I can fix this and if any more info is needed from my end to help you guys.

**Comment by Hrishikesh-K** [comment]
Just an addition: The query parameter is added using `history.replaceState('', '', './?q=' + searchInput.value.trim());` which seems a possible cause of this problem.

**Comment by bep** [comment]
@Hrishikesh-K I had the exact same issue, came here searching ... :-) By strike of random I tried the construct below, and ... drum vortex, it works:

```js
history.replaceState({ turbo: {} }, null, href);
```

**Comment by Hrishikesh-K** [comment]
Sorry about the delay. Just tested this and wow! That does work! Thank you so much!
