### ISSUE TITLE
Compiled JS without CDN

### ISSUE THREAD

**Issue by afonari** [hotwired/turbo#172]
Hi All,

I want to host turbo JS on my own. From the website:

In Compiled Form

You can download the latest distributable script from the GitHub releases page, then reference that in your <script> tag on your page.

Where is this "distributable script", I cannot find it? In the releases, there is only source.

Thanks!

**Comment by javan** [comment]
Sorry, the website is incorrect. You can download the distributable (`dist/`) files from services like:
- https://unpkg.com/@hotwired/turbo/
- https://yarnpkg.com/package/@hotwired/turbo?files

Or, you can install the npm package locally and copy the files into your application.

**Comment by afonari** [comment]
Thanks for the reply, out of these files what I should place in the <script src=? :
```types
turbo.es2017-esm.js
88.35KB
turbo.es2017-esm.js.map
177.75KB
turbo.es2017-umd.js
99.38KB
turbo.es2017-umd.js.map
178.19KB
turbo.es5-umd.js
152.99KB
turbo.es5-umd.js.map
```

Do I need `types` folder?

**Comment by javan** [comment]
```html
<script src="turbo.es2017-esm.js" type="module"></script>
```
or:
```html
<script src="turbo.es2017-umd.js"></script>
```
or, if you need to support old browsers like IE 11:
```html
<script src="turbo.es5-umd.js"></script>
```

**Comment by afonari** [comment]
Thanks, can you explain the difference between -esm and -umd if you have a chance?

**Comment by stgm** [comment]
This would be great to include in the docs! I've been on Rails for many years but never needed a lot of JS. I haven't been able to (quickly) find out why Turbo would include es5 and es2017 builds. I do have the `turbo-rails` package but when debugging Turbo itself it was much easier to drop the JS builds into my assets folder. That took a while to do right, and I still can't figure out why you would prefer the UMD or ESM version ;-) Long story short, I would (also) be very happy with a brief description of the basics that affect Turbo deployments!

**Comment by asheroto** [comment]
Thanks for that. I proposed a change with a pull request #732 .
