### ISSUE TITLE
How to install without using module

### ISSUE THREAD

**Issue by iamdriz** [hotwired/turbo#18]
We use Turbolinks in our Jekyll website and compile the JS using Jekyll Assets (which uses Sprockets).

However because Turbo now expects you to reference the JS file as a module (if you're not using NPM/Yarn) you can't include it in the `application.js` without getting the error `Uncaught SyntaxError: Unexpected token 'export'`.

Is there a way to include Turbo the same way we could Turbolinks? e.g. `//= require ./vendor/turbo-7.0.0-beta.1`

To solve this we've had to remove it from our compiled JS and have Turbo loaded in separately with:
```
<script type="module">
  import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
</script>
<script src="./application-1234.js"></script>
```
Additionally by importing the module like this we can't access `Turbo.` so we can't for example change the progress bar delay with: `Turbo.setProgressBarDelay(0);` or  clear the cache with `Turbo.clearCache();` as `Turbo` isn't defined...

**Comment by javan** [comment]
There are UMD builds (as ES5 or ES2017) you can use: https://unpkg.com/browse/@hotwired/turbo/dist/

**Comment by iamdriz** [comment]
@javan Ah thanks. I didn't see any references to non-module versions in the documentation. That works great! Tahnks!
