### ISSUE TITLE
Execute head script tag

### ISSUE THREAD

**Issue by kiuKisas** [hotwired/turbo#180]
When I have turbo enable, my script tag in head doesn't execute.
Is there anyway to "force" it ?
Thank's !

**Comment by michalsznajder** [comment]
No directly. 

But you can use Stimulus to detect page visits and force you code to run.

**Comment by xtr3me** [comment]
You can execute your function by listening on events:

```
document.addEventListener('DOMContentLoaded', () => {
  yourFunction()
})

document.addEventListener('turbo:render', () => {
  yourFunction()
})
```

The `DOMContentLoaded` is triggered on the initial page, and the `turbo:render` is triggered when the Turbo drive kicked in (clicking on links etc.)

**Comment by Ahmed-Elrayes** [comment]
> document.addEventListener('turbo:render', () => {
>   yourFunction()
> })
but using this method makes the page like (not responding) until it runs the js, even tho the js isn't so big and doesn't need much time to load, which is unacceptable, or maybe i've done something wrong...
