### ISSUE TITLE
`cacheSnapshot` causes side effects, eg. links inside frames are re-visited

### ISSUE THREAD

**Issue by ghiculescu** [hotwired/turbo#182]
https://discuss.hotwire.dev/t/trouble-with-unexpected-fetch-request-when-changing-pages reported this issue. I've been able to replicate it, but don't know how to fix it.

```html
<!-- index.html -->
<html><head><script type="module">
  import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
</script></head>
<body>
<turbo-frame>
<a href="/app/get-random-number">this link goes to a 404, it doesn't really matter what it does. it just needs to be a link inside a frame. i've made it 404 so it stands out more in dev tools when replicating.</a>
</turbo-frame>
<a href="other_page.html">Go to other page</a>
</body>
</html>
```

```html
<!-- other_page.html -->
<html><head><script type="module">
  import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
</script></head>
<body>
other page!
</body>
</html>
```

Start a server - `python -m SimpleHTTPServer` - then go to `localhost:8000`

To replicate:

- Click the link inside the frame
- Observe a visit was made to that link (fine)
- Click the link outside the frame
- Observe two visits. One to the link you just clicked (fine). Another to the link inside the frame (bad!!)

![bug](https://user-images.githubusercontent.com/509837/108260733-4d090780-7128-11eb-980d-93313f4fe960.gif)

**Comment by ghiculescu** [comment]
In debugging further, a few things I noticed:

- When the link inside the frame is clicked, Turbo set's the frame's `src` to that URL (`navigateFrame`).
- When you click the second link, it creates a full page navigation. This means that the original page (index.html) is snapshotted (`cacheSnapshot`). 
- This calls `document.body.clodeNode(true)`, which results in the frame's `attributeChangedCallback` firing. Setting a breakpoint there it implies the `src` is being added... maybe this gets done for every new attribute added to the frame when it's cloned?
![image](https://user-images.githubusercontent.com/509837/108261144-ce609a00-7128-11eb-8120-f71f5b4d829c.png)
- `sourceURLChanged` calls `loadSourceURL` which visits the `sourceURL`. Which is whatever was set to the frame's `src` originally.

**Comment by seanpdoyle** [comment]
@ghiculescu are you able to reproduce this when using https://github.com/hotwired/turbo/pull/165?

**Comment by ghiculescu** [comment]
@seanpdoyle looks like that PR is a winner, https://discuss.hotwire.dev/t/trouble-with-unexpected-fetch-request-when-changing-pages/2288/17?u=ghiculescu

**Comment by ghiculescu** [comment]
Can you link this issue to it?
