### ISSUE TITLE
Add 'how to contribute' to README

### ISSUE THREAD

**Issue by mollerhoj** [hotwired/turbo#187]
I want to submit a PR, fixing a bug. I have worked on many js (and ts) projects, but it's not my favorite language. I like ruby, surprise surprise . I can't keep up with the pace in terms of js tooling. Would it be possible to add a few instructions on how to get the project up and running locally and run the specs? Might lower the barrier of entrance :-)

@sstephenson

**Comment by xtr3me** [comment]
I have tried to document the steps I took when fixing a bug on this project. I hope this helps a bit, let me know if you miss anything or you want me to clarify a bit more.

**Comment by brunoprietog** [comment]
Hi @mollerhoj, thanks for your interest in contributing in Turbo! Actually, there's already a link in the README that links to the contribution guide. I'll leave it [here](https://github.com/hotwired/turbo/blob/main/CONTRIBUTING.md) anyway.
