### ISSUE TITLE
Lazy-loading multiple parts of the page from a single response

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo#189]
This issue's somewhat similar to #56, at least in how I've made a stopgap for it.

To lazy-load a single frame, you can apply the `src` attribute and a request will be made to replace its content. You can do this to multiple frames, but you can't populate multiple frames from a single response as far as I'm aware without bringing Streams into the mix. Applying the same `src` attribute to multiple frames makes a request to that `src` per frame.

I've made [this Stimulus controller](https://gist.github.com/boardfish/2b55f511fbb463ac270419b00a202680) which does what I'd like. There's likely some things it could do better, e.g. error conditions and making sure that the incoming response is definitely a Turbo Stream (I got mixed messages on what the `Accept` header should be). I'm not sure I'd like for this to be the only solution, though.

Ideally, `src` should default to replacing multiple frames with one request unless we specify that the element warrants a unique request. I'm not sure what to call that, but I guess we'd pass it through as a `data-turbo` attribute. Perhaps `<%= turbo_frame_tag :messages, src: '/messages', shared_request: false %>` (defaults to `true`)?

**Comment by boardfish** [comment]
To clarify something here, I think the main issue I'm trying to solve is avoiding having to write more Turbo Streams for this purpose. It'd be nice to have two routes and HTML views - one representing the loading state of a page that requires some lengthy serverside business, and one representing the fully loaded state. I think this pattern would be easier to understand than the alternative (using Streams to do the same).

**Comment by seb-jean** [comment]
Hello, have you found a solution to this issue?

**Comment by brunoprietog** [comment]
Hi @boardfish, you can include Turbo streams inside the response if it is inside a Turbo frame, so you have the lazy loading And you can control the replacement of multiple elements within the page as long as you include them as Turbo streams within the loaded Turbo frame response.
