### ISSUE TITLE
Form submit not clearing cache

### ISSUE THREAD

**Issue by jonsgreen** [hotwired/turbo#193]
I have a form that posts to an action that changes the state of an object and then redirects to a different page. If I then hit the back button I am given an old snapshot of the page and I need to refresh to get the correct view based on the updated state. 

I would have expected Turbo to clear the cache in such cases but that appears to not be happening. I am wondering if this is expected behavior? If so then is there something simple I should be doing to get the desired behavior? If not then is this a bug or is there something I might be doing wrong? 

I am happy to create an MVCE but thought I should check first before wasting time on something that is already clearly known.

**Comment by jonsgreen** [comment]
@seanpdoyle I apologize for pinging you directly on this issue but I have seen you show up in a lot on issues I have been watching and your support has been very valuable. I can imagine you are terribly busy and there must be an overwhelming amount of issues to address with Hotwire. For now I would be more than satisfied with just a few words on whether I have named something known or not and whether anything is likely to be changed in Hotwire to address this problem. 

At the moment I am just turning off caching with the no-cache meta tag for the whole application to avoid these undesirable caching effects but that does not seem ideal long term if there are other options. 

I would be happy to dig in and work on a solution if this seems possible and something that others would value.

**Comment by seanpdoyle** [comment]
Thank you for raising this, @jonsgreen.

> I am happy to create an MVCE but thought I should check first before wasting time on something that is already clearly known.

To help narrow down the surface area a bit, a minimal example that reproduces the behavior would be valuable?

If you're able to add one, a [failing functional test case](https://github.com/hotwired/turbo/blob/main/src/tests/functional/form_submission_tests.ts) would be a valuable alternative.

There are lines of code in the Navigator to clear the snapshot cache on a [form submission success](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/drive/navigator.ts#L83) and a [form submission failure](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/drive/navigator.ts#L99).

In the meantime, a [`clearCache()` function is exported from the `@hotwired/turbo` package](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/index.ts#L36-L38), you can call it if the current implementation isn't covering your case.

**Comment by jonsgreen** [comment]
@seanpdoyle I decided to dig into the code a bit to see if I could understand a bit more about what is happening. It is quite the maze for someone from the outside who doesn't know very much about the internals of Turbo. However, from what I can tell, as you mentioned above the cache does get cleared with the [form submission success](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/drive/navigator.ts#L83). However, it seem like a few lines down [a visit is proposed](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/drive/navigator.ts#L88) and that seems to reestablish the snapshot cache. Not sure if that helps but thought I would point it out.

**Comment by javan** [comment]
I just confirmed this by fiddling around the console. Submitting a form clears the cache and then caches the current page (with the form that we don’t want cached) when navigating away.

**Comment by jonsgreen** [comment]
Thanks @javan for confirming this issue. I am curious if in the scope of things whether this would be considered a bug and if so how significant. Is there anyway that I can help in moving this issue forward?

**Comment by weaverryan** [comment]
Hi there!

I just hit this also - and I'm *also* trying to think of whether this is expected or a bug... and *if* a bug how to fix.

The behavior also happens form submitting a form *without* success:

A) Navigate to a page with a form (e.g. `/register`)
B) Submit the form blank, it re-renders with validation errors
C) Click to navigate away from the page
D) Click back to the page with the form (e.g. `/register`)

On (D), the filled form with validation errors will show up briefly (the snapshot) before being replaced with a fresh form. This is... sort of expected: when you navigate on (C), like any other navigation, this takes a snapshot of the page (with the filled form and validation errors). 

This seems tricky to fix. The only fix I can think of is to:

As a policy, disable snapshots on pages with forms. This would need to be done by the user with `<meta name="turbo-cache-control" content="no-preview">`

We *could* try to be smarter... and cache the page only in its "initial" (unsubmitted) form... and then not cache future snapshots. This would fix the "preview" problem (showing the filled out form as a preview when you click back to the page) but it would have the negative effect of showing the blank form on restoration visits (e.g. when I hit back, now the form would be blank, whereas currently, the form contains the filled-fields & errors from my submit).

**Comment by scottjg** [comment]
i'm running into this as well. in our case we're on an "edit" page and disable the button when submitting the form (`data-disable-with`). The rails app returns a redirect. When I hit the back button, i'm back at the edit form, but the submit button is still disabled. this was something that always "just worked" with turbolinks so i'm not sure the right way to fix this?

**Comment by weaverryan** [comment]
To clarify, I think there are 2 possible bugs - and fixing one is pretty clear:

A) On a successful POST, Turbo already clears the cache... but then *re-caches* the page that was just submitted - https://github.com/hotwired/turbo/issues/193#issuecomment-797042499 - and that seems like a clear mistake.

B) On unsuccessful POST, Turbo does not clear the cache... which causes problems... but the solution is not clear (unless Turbolinks already has a perfect solution) - https://github.com/hotwired/turbo/issues/193#issuecomment-833727739

Item (A) is probably a "lowish hanging fruit" - I didn't want my introduction of item (B) to cloud things.

Cheers!

**Comment by mtomov** [comment]
I was getting stale cache when using a turbo frame. In this case, added a reusable Stimulus controller to clear it up, as suggested using `clearCache` by @seanpdoyle . Thanks for the pointer!


```javascript
// turbo_clear_cache_controller.js
// Add `data-controller="turbo-clear-cache"` to any form within a turbo frame
// that you'd like to clear the cache for

import { Controller } from 'stimulus'
import { clearCache } from '@hotwired/turbo'

export default class extends Controller {
  initialize() {
    this.afterRequest = this.afterRequest.bind(this)
  }

  connect() {
    this.element.addEventListener(
      'turbo:before-fetch-response',
      this.afterRequest
    )
  }

  disconnect() {
    this.element.removeEventListener(
      'turbo:before-fetch-response',
      this.afterRequest
    )
  }

  afterRequest({ detail }) {
    if (detail.fetchResponse.succeeded) {
      clearCache()
    }
  }
}
```

**Comment by tleish** [comment]
Does adding the following solve the issue?

```javascript
const FetchMethod = { get: 0 };
document.addEventListener('turbo:submit-end', async ({ detail }) => {
  const nonGetFetch = detail.formSubmission.fetchRequest.method !== FetchMethod.get;
  const responseHTML = await detail.fetchResponse.responseHTML;
  if (detail.success && nonGetFetch && responseHTML) {
    Turbo.clearCache();
  }
});
```

**Comment by maxwell** [comment]
> ```js
> const FetchMethod = { get: 0 };
> document.addEventListener('turbo:submit-end', async ({ detail }) => {
>   const nonGetFetch = detail.formSubmission.fetchRequest.method !== FetchMethod.get;
>   const responseHTML = await detail.fetchResponse.responseHTML;
>   if (detail.success && nonGetFetch && responseHTML) {
>     Turbo.clearCache();
>   }
> });
> ```

I had to add a timeout in order to make sure that the cache clearing happened after the errant "recache the page" behavior kicked in.  Maybe ```'turbo:submit-end'``` isn't late enough in the event stack?
