### ISSUE TITLE
Turbo scrolls to first empty id

### ISSUE THREAD

**Issue by jmfederico** [hotwired/turbo#201]
I have noticed the following behavior:

If a site has html tags with empty `id` attributes like this: `id=""`, then turbo will scroll to that element after a new page navigation occurs.

Leaving aside the fact that there should be no empty id's, maybe Turbo should only scroll to elements that actually have an `id`?

**Comment by sebyx07** [comment]
Temporary fix:
```js
document.addEventListener("turbo:before-render", () =>{
  document.querySelectorAll("[id]").forEach((el) => {
    if(el.id === "") el.removeAttribute("id");
  })
});
```

**Comment by dhh** [comment]
This has been fixed.
