### ISSUE TITLE
Reload the content of a turbo-frame

### ISSUE THREAD

**Issue by coorasse** [hotwired/turbo#202]
We would like to trigger the reloading of a turbo-frame which has been lazy loaded with the `src` attribute.

How can we achieve that? If there's nothing built-in, would be something you would consider in a PR?

As a reference: https://discuss.hotwire.dev/t/how-to-auto-reload-frame/1872/5

**Comment by javan** [comment]
You can re-assign a `<turbo-frame>`’s `src` to reload it:
```js
const { src } = element
element.src = null
element.src = src
```

> If there's nothing built-in, would be something you would consider in a PR?

I think wrapping that up as `element.reload()` would be a nice addition. 👍

**Comment by coorasse** [comment]
To me this issue can be closed nevertheless. Your suggestion works, and I opened a PR if we want to implement the `reload()` method. Thanks.

**Comment by coorasse** [comment]
The above mentioned technique doesn't work when `loading="lazy"`

**Comment by marselmustafin** [comment]
Any ideas for reloading content of `loading="lazy"` frames?

**Comment by jorgegorka** [comment]
@marselmustafin You can reload the content manually using `this.element.reload()` inside a stimulus controller attache to that turbo frame or you can do `document.getElementById('turbo-frame-id').reload()`

**Comment by firedev** [comment]
Can I somehow mark a turbo-frame as "incomplete" so it reloads the next time it's displayed?

**Comment by duffyjp** [comment]
@firedev 
> Can I somehow mark a turbo-frame as "incomplete" so it reloads the next time it's displayed?

I just implemented @jorgegorka's suggestion in the stimulus controller I use to hide/show a modal with its content loaded via turbo frame with `src:`  It works great.  Right after display I call the `.reload()` so there's zero delay but new content will indeed get loaded on top after a few ms.

A fancier alternative could be to load the content with a subscribed turbo stream and then broadcast any changes server side.  I'm loading such a small amount of data, and it's only shown temporarily so for me just reloading every time is fine.

**Comment by firedev** [comment]
@duffyjp Hey here is how I did it in the end https://gist.github.com/firedev/cedf0ea3153e790498da5c72b33fcd76

**Comment by scuml** [comment]
Here's a stimulus controller that resets a turbo-frame when it is removed from view.  Awesome for dialog elements. 
```
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  /* 
  A controller that resets a lazy turbo frame when it disappears from view.
  Usage:
      <dialog>
        <turbo-frame id="frame_name" data-controller="reloadframe" src="<url>" loading="lazy">Loading...</turbo-frame>
      </dialog>
  */

  started = false

  connect() {
    this.initialContent = this.element.innerHTML;
    this.src = this.element.src
    this.element.addEventListener("turbo:frame-load", this.frameLoaded.bind(this));
    this.intersectionObserver = new IntersectionObserver(this.intersect)
  }

  frameLoaded() {
    if (!this.started) {
      this.started = true
      this.intersectionObserver.observe(this.element)
    }
  }

  resetTurboFrame() {
    this.element.removeAttribute("complete")
    this.element.setAttribute("loading", "lazy")
    this.element.innerHTML = this.initialContent

    if (this.started) {
      this.started = false
      this.intersectionObserver.unobserve(this.element)
    }
  }

  intersect = (entries) => {
    const lastEntry = entries.slice(-1)[0]
    if (!lastEntry?.isIntersecting) {
      this.resetTurboFrame()
    }
  }
}
```
