### ISSUE TITLE
Turbolinks to Turbo change. Is there an equivalent?

### ISSUE THREAD

**Issue by rctneil** [hotwired/turbo#207]
Hey,

In Turbolinks I had to manually push a history item when using Infinite Scroll. I did this using the below:

    infScroll.on('append', (response, path, items) => {
            // Manually push URL to the Turbolinks history
            Turbolinks
                .controller
                .pushHistoryWithLocationAndRestorationIdentifier(path, Turbolinks.uuid())
        })

I've tried changing the above to use `Turbo` instead of `Turbolinks` but it doesn't seem to work.  Is there an equivalent here?

**Comment by mathieumahe** [comment]
Hello,

I have the same problem.

Have you find a solution to your issue?

**Comment by marcoroth** [comment]
To push something onto the Turbo Drive history you can directly push it to the `history` object on `window`. Turbo is monitoring the events related to modifying the History on `window`. 

In this case something like [`window.history.pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) should do what you want.

**Comment by mathieumahe** [comment]
Thanks, I will try that.
