### ISSUE TITLE
Link and Turbo Stream in Beta 4

### ISSUE THREAD

**Issue by Skrylex** [hotwired/turbo#209]
Hey !

I tried to used Turbo for modals but since Beta 4 all of my links are no longer recognized as `turbo_stream` format in my controllers. I would like to ask you if there is a solution so that my links to be considered as `format.turbo_stream` in my controllers again.

Thank you !

**Comment by MrHubble** [comment]
It is [intentional](https://github.com/hotwired/turbo-rails/issues/120#issuecomment-776731267) that links are no longer sent as `turbo_stream`.
