### ISSUE TITLE
Replacing two distinct parts of the page with a GET request through a link.

### ISSUE THREAD

**Issue by A7madXatab** [hotwired/turbo#217]
HI.

So. basically i have  this 

![image](https://user-images.githubusercontent.com/38360603/112590167-6d0ca480-8e13-11eb-8dff-cd4f8e75c8da.png)

What i want is, that when you click on a conversation of the left side. 

- it will perform a GET request to the server
- Render back two `turbo-stream` tags to replace parts of the DOM.

But, currently i just cant wrap my head around it and can't get it to work.

The requests made via the link are always processed as HTML. Meaning i get a blank page like this

This is what i responed with 

```
  def show
    render layout: false, content_type: "text/html; turbo-stream"
  end
```

![image](https://user-images.githubusercontent.com/38360603/112590607-2bc8c480-8e14-11eb-97bf-3d8ab7faf93b.png)

My problems are 
- i don't know how can i make the links send requests as TuboStreams 
- Dont know how to replace these two elements.

**NOTE**
i know that using `target=_top` will solve that. but the page does some heavy calculations, so unfortunately that's not possible.

I have also looked at https://github.com/hotwired/turbo/issues/56 but with no luck.

Thanks

**Comment by tleish** [comment]
@A7madXatab - I suggest closing this ticket (which isn't a bug or feature request) and posting your question to https://discuss.hotwire.dev/.  You will likely get the help you are looking for.

**Comment by mjc-gh** [comment]
This is a duplicate of #56.

The recommended practice here would be to use Turbo Streams for this replacing more than one frame. See this response here: https://github.com/hotwired/turbo/issues/56#issuecomment-753556469

**Comment by A7madXatab** [comment]
Aggreed, figured that out. Sorry. For future reference.

You can find the same question on https://discuss.hotwire.dev/t/using-turbo-stream-and-turbo-frame-with-get-requests-solved/2603/2.

And the solution https://github.com/hotwired/turbo-site/pull/40#issuecomment-791487001
