### ISSUE TITLE
Error: Form responses must redirect to another location

### ISSUE THREAD

**Issue by cj** [hotwired/turbo#22]
Hi,

I am using https://viewcomponent.org/ and I am handling redirects for forms using stimulus doing the following:

```javascript
  async turboSubmit(event) {
    const { success } = event.detail

    if (success && this.redirectValue) {
      Turbo.visit(this.redirectValue)
    } else {
      this.enableSubmit()
    }
  }
```

But it currently throws this error `Error: Form responses must redirect to another location`, which is due to the following code https://github.com/hotwired/turbo/blob/aae160bed764ca7322be1e3a9e00366787d96f7f/src/core/drive/form_submission.ts#L103, is there a reason this is needed?

Cheers!

**Comment by cj** [comment]
So I ended up creating a patch for now to get it working on my end https://github.com/cj/app-template/blob/main/patches/%40hotwired%2Bturbo%2B7.0.0-beta.1.patch, but it lead to what might be another bug with `Turbo.visit`:

![CleanShot 2020-12-22 at 20 51 06](https://user-images.githubusercontent.com/1819/102953676-79d9cf00-4497-11eb-938c-b16b87411474.gif)

This is where I am calling `Turbo.visit` https://github.com/cj/app-template/blob/main/app/components/form_component/base.js#L121

**Comment by cj** [comment]
So I think ^ is a bug due to the fact I was using render plain https://github.com/cj/app-template/blob/main/app/controllers/test_controller.rb#L11.  When you hit the back button, the full html of `/login` is there but Turbo is not picking that up.

**Comment by cj** [comment]
ah so the `Turbo.visit` is not a bug, it was because I had render plain https://github.com/cj/app-template/blob/main/app/controllers/test_controller.rb#L11!

**Comment by danjac** [comment]
I'm running into this issue as well with simple form submissions that re-render the form (i.e. the HTML page) with errors when server validation fails.  Is there a reason for this behavior? Is it documented?

**Comment by sstephenson** [comment]
We intend to allow HTTP 422 responses for form submissions inside frames, but it didn’t make the cut for the initial beta release.

For now, you can try sending a Turbo Streams response that re-renders your form with errors.

**Comment by sstephenson** [comment]
Browsers record form submissions in history along with the verb. In a standard "postback" scenario, if you reload the page after submission, or navigate away and then back, you'll see a dialog box like this:

<img width="616" alt="Screen Shot 2020-11-30 at 10 41 41 AM" src="https://user-images.githubusercontent.com/2603/103009599-02db1f80-4505-11eb-840d-cef07c9f188a.png">

The forms-must-redirect constraint is what allows us to keep the browser's back, forward, and reload buttons working after any form submission, and without showing a dialog box, since all form submissions result in a visit and all visits are idempotent GET requests.

**Comment by ollieh-m** [comment]
Thanks for the explanation @sstephenson. I’m probably misunderstanding something, but can’t quite see why swapping in HTML returned by the form submission (or even simulating a full page visit using the HTML response) would mess with the browser history... If the form submission is an ajax request, does the browser put the POST or PUT request in its history? If not, why would it be a problem to render HTML returned by a 200 request, in the same 400-500 responses can now be rendered? 🙇‍♂️
