### ISSUE TITLE
Is Turbo "data-turbo-permanent" designed to work differently to Turbolinks "data-turbolinks-permanent"?

### ISSUE THREAD

**Issue by le0pard** [hotwired/turbo#221]
Hello.

Currently I am using Turbolinks for some projects. But after release Turbo and this phrase in Turbolinks README:

> Please note that Turbolinks is no longer under active development. It has been superseded by a new framework called Turbo, which is part of the Hotwire umbrella.

I decided to move projects to Turbo. In the process of migration I find out, that Turbo "data-turbo-permanent" work differently, than Turbolinks "data-turbolinks-permanent" with audio/video tag.

I did example, which contain the same codebase, except one use Turbo and other use Turbolinks (changed data attributes and events listeners only)

Here example with turbolinks: 

https://turbo-permanent.catware.org/turbolinks/ (click play audio and after this travel by "HOME" and "ABOUT" links - audio works without any issues, audio controls still working)

The same code, but with Turbo:

https://turbo-permanent.catware.org/turbo/ (click play audio and after this travel by "HOME" and "ABOUT" links - audio will stop immediately after first page visit)

Here source code for

Turbolinks 
JS: https://github.com/le0pard/turbo-permanent-issue/blob/main/webpack/turbolinks_controllers/audio_controller.js 
HTML: https://github.com/le0pard/turbo-permanent-issue/blob/main/source/layouts/turbolinks.html.erb#L57-L63

Turbo 
JS: https://github.com/le0pard/turbo-permanent-issue/blob/main/webpack/turbo_controllers/audio_controller.js
HTML: https://github.com/le0pard/turbo-permanent-issue/blob/main/source/layouts/turbo.html.erb#L56-L62

Code the same, except for Turbo in HTML used "data-turbo-permanent" instead "data-turbolinks-permanent" and in JS used events "turbo:before-cache" and "turbo:load" instead "turbolinks:before-cache" and "turbolinks:load"

I read about some solutions https://github.com/turbolinks/turbolinks/issues/157#issuecomment-423275861 , but "pause/play" solution is noticeable for the end user.

In the end my question: is this designed to work differently? Is this mean, that Turbolinks still better for use cases, where needed "permanent" element with audio/video tag or it is just bug in Turbo, which do not have Turbolinks?

Versions:
Turbolinks: 5.2.0
Turbo: 7.0.0-beta.4

Thanks

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/222 to add coverage for this to the test suite. Without any implementation changes, the behavior is working in Safari and Firefox, but failing on Chrome.

@le0pard Could you review https://github.com/hotwired/turbo/pull/222 to help me understand how closely it reproduces the issues you're describing?

**Comment by chriscoyier** [comment]
Just popping in to say I was playing with Turbo for the first time today and this was pretty much exactly the use-case I was trying: having a part of the page have an `<audio>` player that doesn't re-render between page loads (like you can image would be useful for a podcast site). In my mind, what would happen is that that area of the DOM just isn't touched at all, but it looks like it does get re-rendered (just with smarts somehow applied). 

To toss in a little extra complexity, I wasn't actually using an `<audio>` element but a custom Web Component that has an audio element inside it. The Web Component does what Web Components do, it mounts itself and slots in stuff and whatnot. But when I clicked on an internal link to change pages, it re-rendered, and the Web Components got VERY confused. In my case, the entire `<style>` got wiped out. [Here's a little video if you're curious](https://d.pr/v/FexIRr
) (the area at the top with the ▶️ button is the Web Component, and clicking the link triggers the Turbo re-render).

**Comment by le0pard** [comment]
@chriscoyier Did you try https://github.com/turbolinks/turbolinks ? It may not have this issue.

**Comment by chriscoyier** [comment]
I was tempted to try it, but...

> Please note that Turbolinks is no longer under active development.

I don't think I wanna build something new on something that's sunset.

**Comment by seanpdoyle** [comment]
I recall reading about this exact use case years ago via [_Why we chose Turbolinks_](https://changelog.com/posts/why-we-chose-turbolinks).

It feels like a bug introduced in Turbo.

**Comment by sstephenson** [comment]
Thanks for reporting this!

**Comment by le0pard** [comment]
Thanks @sstephenson Can we release beta 5, so I can try to migrate again from Turbolink to Turbo ?

**Comment by le0pard** [comment]
Ok, I compiled master and it works. You can try it too @chriscoyier

**Comment by chriscoyier** [comment]
My thing isn't super urgent, I can wait for a release. I'm looking forward to seeing if it works within my `<web-component>`

**Comment by sstephenson** [comment]
Turbo [v7.0.0-beta.5](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.5) is now available. (We're also using this feature for the podcast player on @vampeel's [new REWORK.fm site](https://rework.fm)!)
