### ISSUE TITLE
The src attribute of turbo-frame does not reflect the actual URL when redirected

### ISSUE THREAD

**Issue by sukei** [hotwired/turbo#223]
Hello,

I'm currently building a wizard form. Each step redirect the user to the next one once validated. I follow [this issue](https://github.com/hotwired/turbo/issues/50) with great interest to improve the user experience regarding the browser history. In the meantime, I just used the stimulus controller made by [@Intrepidd](https://gist.github.com/Intrepidd/bb1ffc5944a5c1ec3a9f5582753c4b67) to reflect the navigation context of the frame to my browser history. Unfortunately, the turbo-frame didn't update the src attribute when redirected ; whether it be after following a link or after a form submission. Is there any reason that the turbo-frame src attribute to be out of step with reality?

**Comment by seanpdoyle** [comment]
Thank you for opening this issue. I've opened https://github.com/hotwired/turbo/pull/224 to attempt to correct this behavior.
