### ISSUE TITLE
Events to interact with Turbo Stream

### ISSUE THREAD

**Issue by panda-madness** [hotwired/turbo#23]
Currently, I can hook into Turbo Drive via `turbo:before-visit` and, for example, cancel an immediate visit to perform page transition animations, or whatever else. It would be nice to have a similar set of events to interact with Turbo Stream operations, as well as means to cancel, modify, or pass through the operation via those events.

Something along the lines of:

```js
class Example extends Controller {
    /**
     * @param {TurboStreamEvent} e
     */
    animate(e) {
        e.preventDefault();

        this.element.animate('...perform some animation');
        
        e.detail.processStream();
    }
}
```
```html
<div id="example_target" data-controller="example" data-action="turbo:before-stream->example#animate">
</div>
```

**Comment by nbgoodall** [comment]
There's already a [`turbo:before-stream-render`](https://github.com/hotwired/turbo/blob/aae160bed764ca7322be1e3a9e00366787d96f7f/src/elements/stream_element.ts#L77) event. :)

[Here's a PR](https://github.com/hotwired/turbo/pull/20) to get the new template included in the event so you could do something similar to `processStream()`.
