### ISSUE TITLE
How to make permanent stimulusjs controller

### ISSUE THREAD

**Issue by zmitic** [hotwired/turbo#230]
I checked all other issues and wasn't able to find an answer. Is there some way to have permanent stimulusjs controller?

Right now, I have permanent frame and it works. But if I put stimulus controller inside it, it is reconnected on every page visit.

The thing is that I would like to have permanent websocket connection to server. So controller gets created, makes AJAX call to populate it (or lazy frame) and later use pub/sub library that would be used by other controllers as well.

My version is ``7.0.0-beta.3`` because ``beta.4`` doesn't have  ``text/vnd.turbo-stream.html`` accept header.

**Comment by dbil25** [comment]
Any news on this? It is still relevant. Having a stimulusController inside a `data-turbo-permanent` element resets the controller it on every re-render of the frame.

**Comment by dhh** [comment]
There's not any way to currently create a permanent stimulus controller. `data-turbo-permanent` involves copying the existing DOM to the new page. So the stimulus controller will still reconnect. You should store state in the DOM to be able to deal with this gracefully.

With Rails, the web sockets connection is handled as a permanent connection via Action Cable.
