### ISSUE TITLE
Issue a warning when the server responds with a 200 to a POST request

### ISSUE THREAD

**Issue by kuba-orlik** [hotwired/turbo#246]
It's easy to miss the fact that Turbo expects a 422 or 303 status response when submitting a form with a POST method. When the server responds with a 200 response, the body of the response does not replace the current view, and nothing happens.

For an untrained eye it might look like a bug. I think it'd be a good idea to show a warning in the JS console when this happens, so the dev spends less time figuring out why the view isn't refreshing (like I did ;) )

**Comment by ParamagicDev** [comment]
I thought this was already the case?

https://github.com/hotwired/turbo/blob/main/src/core/drive/form_submission.ts#L140

**Comment by brunoprietog** [comment]
Yes, this already happens. You get the following error:

```
Error: Form responses must redirect to another location
```
