### ISSUE TITLE
[Feature Request] Custom actions for streams

### ISSUE THREAD

**Issue by gahia** [hotwired/turbo#247]
It may be useful to send custom actions by turbo streams like this:

`<turbo-stream action="reload" target="frame_id">`

which I'm currently using for reloading frames with an `src` attribute as response to certain actions. 

So far this is the only case I had to implement but, in order to avoid an overload of possible new stream actions, I think a small implementation where turbo receives a stream with a custom action and triggers an custom event over the target element can make a difference covering any possible case. 

`target_element.dispatchEvent(new CustomEvent('action_name'))`

It is just an idea!

**Comment by seanpdoyle** [comment]
Is this closed by https://github.com/hotwired/turbo/pull/479?

**Comment by gahia** [comment]
I think so! It offers a way to manage custom actions. Thanks!

**Comment by seanpdoyle** [comment]
That's great news! Would you mind closing this issue to reflect that fix?
