### ISSUE TITLE
data-target the nearest frame. Proposal to introduce `data-turbo-target: '_parent'` (or is it `_self` ?)

### ISSUE THREAD

**Issue by coorasse** [hotwired/turbo#252]
I have a use case where the wrapping frame has `data-target: '_top'` set as default.
This is good since most of the links within this frame (it's a modal) should simply reload the page.
This works very well for 99% of my links, but (of course!) it happens that I have a modal with a list and pagination links.

These pagination links should of course target the wrapping frame instead of `_top`.

Now, it happens that when I render the pagination, I don't actually know the id of the nearest, wrapping, frame, so I am in the situation of having a `link_to '2', second_page, data: { turbo_target: ? }`.

Could we have a special keyword `_parent` to target the nearest frame? I mean...[we had it 20 years ago 😄 ](https://www.tagindex.net/html/frame/a_target.html) so I guess it makes sense, right?

**Comment by dhh** [comment]
Would be happy to see this 👍

**Comment by coorasse** [comment]
I blocked one day to work on this next week.
