### ISSUE TITLE
AbortError: The user aborted a request on slow connections

### ISSUE THREAD

**Issue by armanm** [hotwired/turbo#253]
Frequently in Rollbar we are seeing this error which seems to come about from the depths of Turbo's code:

![image](https://user-images.githubusercontent.com/1578748/115503910-80981780-a2ba-11eb-88b4-3e46005e5d6d.png)

The steps for replicating the issue on our site are:

1. open Chrome dev tools and throttle the network speed down to Slow 3G
2. reload the page and start clicking links quickly

Has anyone else seen this issue or knows how it can be handled?

EDIT - Firefox seems to report the same issue with a slight diffrent message `AbortError: The operation was aborted.`

**Comment by brenogazzola** [comment]
Having the same problem.

Safari: `AbortError: Fetch is aborted`
Chrome: `AbortError: The user aborted a request.`
Firefox: `AbortError: The operation was aborted.`

**Comment by lukestuts** [comment]
I can trigger this on a locally-hosted site with my elite clicking skillz. It completely disables the site, too.

**Comment by dharkael** [comment]
Is it because the rejected promise is not handled  in this call to `request.perform()`?
https://github.com/hotwired/turbo/blob/c4891515645880ae1f9b4ee5757a8d730b89ac4e/src/core/drive/visit.ts#L154-L161
At least in the **AbortError** case something like this might work.
```typescript
this.request.perform().catch((reason)=> {
         if(reason?.name !== 'AbortError'){
            throw reason
         }
      })
```

**Comment by en30** [comment]
I found I can reproduce `AbortError` easily by double-clicking a link.
Does anyone find a problematic effect on users caused by this? I could not find any for now.
I am wondering If I can ignore these errors.

> It completely disables the site, too.
@lukestuts Could you tell me what browser do you use?

**Comment by mlunoe** [comment]
This still seems to be an issue in [RailsAdmin v3.1.4](https://github.com/railsadminteam/rails_admin/blob/v3.1.4/package.json#L19) using [@hotwired/turbo v7.3.0](https://github.com/hotwired/turbo-rails/tree/4f5448175b4818519dfad45ee183b889807e4533):

```
 $ cat node_modules/@hotwired/turbo/package.json| grep '"version":' 
  "version": "7.3.0",
```

I get the following stack trace, pointing to here: https://github.com/hotwired/turbo-rails/blob/4f5448175b4818519dfad45ee183b889807e4533/app/assets/javascripts/turbo.js#L647:

```js
turbo.es2017-esm.js:517 Uncaught (in promise) DOMException: signal is aborted without reason
    at FetchRequest.cancel (http://localhost:5000/packs/js/vendor-9448171….chunk.js:36232:26)
    at Visit.cancel (http://localhost:5000/packs/js/vendor-9448171….chunk.js:37520:22)
    at Navigator.stop (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38115:25)
    at Navigator.startVisit (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38098:10)
    at BrowserAdapter.visitProposedToLocation (http://localhost:5000/packs/js/vendor-9448171….chunk.js:37815:20)
    at Session.visitProposedToLocation (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38830:18)
    at Navigator.proposeVisit (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38090:23)
    at Session.visit (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38766:22)
    at Session.followedLinkToLocation (http://localhost:5000/packs/js/vendor-9448171….chunk.js:38820:10)
    at LinkClickObserver.clickBubbled (http://localhost:5000/packs/js/vendor-9448171….chunk.js:36880:27)
```

**Comment by jdelStrother** [comment]
I get a lot of unhandledrejection AbortErrors reported to Sentry and spent a while looking into this.

I think #352 is insufficient to prevent it - it only prevents AbortErrors propagating if the FetchRequest is cancelled before the response is received. However, if you abort the request after the initial response is complete, but before finishing reading the response body, it will still result in an unhandled error.

I'm not sure what a proper fix would look like. Maybe one of:

a) Change FetchRequest.cancel to only call abort if FetchRequest.perform hasn't completed
b) Change anything that awaits for FetchResponse.responseHTML to expect an AbortError and ignore it when one happens
c) Don't know if it might be feasible to raise an AbortError subclass (eg TurboAbortError) just so that we can safely ignore it in error reports. It would only work for browsers that support AbortController's `reason` parameter.

**Comment by justinallenmarsh** [comment]
I also have been experiencing this issue when tracking issues with sentry. It would be good to maybe offer guidance on how we should go about dealing with this in our ruby on rails applications. 🤔
