### ISSUE TITLE
use class instead of id ?

### ISSUE THREAD

**Issue by michelson** [hotwired/turbo#254]
Hotwire is great! I'm just starting with it and I have an observation:

a common use case is to reuse partials on the layout , right?. but, when you deliver partial updates via drive responses or streams you are always dealing with turbo-frame-ids. I believe that that could be a limitation for uses cases where you need to update many items that could be (conceptually) the same view. I've seen here other issues asking similar questions were the solution to them was to handle a multiple frame_tag response or to go via stream with multiple messages per id. right? 

I guess the ideal way to tackle this could be to set a "label" on the frame_tag (a classname for dom) in which I could send one stream to update all pointing to any classname or any css selector. does make any sense?

**Comment by danjac** [comment]
I've found the best approach is to concatenate multiple Turbo Streams (each with a unique target ID) in an update. Obviously if you have dozens such updates you are probably better doing a full (Turbo Drive) page response or redirect, but that's not always desirable.

**Comment by michelson** [comment]
@danjac yup that's my point. get turbo frames with classnames or data attribute would be great. I don't know how much complexity this would add to the library though

**Comment by michelson** [comment]
I think #113 will fix this issue

**Comment by marcelolx** [comment]
@michelson Can you check if #113 resolved your problem since it is already merged?

**Comment by michelson** [comment]
@marcelolx great, is turbo released on npm or should I use the version from github ?

**Comment by marcelolx** [comment]
@michelson I think you can use dev-builds https://github.com/hotwired/dev-builds/releases
