### ISSUE TITLE
[Discussion] Client side form validation

### ISSUE THREAD

**Issue by JonathanLorimer** [hotwired/turbo#256]
Hello, I know that there is builtin html form validation. I am wondering if there are plans for more robust client side form validation? Is the recommendation to just use stimulus and some javascript?

**Comment by marcelolx** [comment]
@JonathanLorimer I think you could create a new topic on https://discuss.hotwire.dev/ 

But I think probably the recommendation will be to use stimulus and some js, since you will need run this same validations on server, right?
