### ISSUE TITLE
[Question] Do turbo streams multiplex?

### ISSUE THREAD

**Issue by JonathanLorimer** [hotwired/turbo#258]
Do turbo streams case on headers to multiplex into different channels that can be subscribed to?

**Comment by dhh** [comment]
Not sure I fully understand the question, but with the turbo-rails integration that sends streams over a websocket, it's using a single websocket connection and sends multiple streams over it. If that doesn't answer the question, https://discuss.hotwire.dev is a good place to continue exploring it.
