### ISSUE TITLE
data-turbo="false" not working with forms

### ISSUE THREAD

**Issue by danjac** [hotwired/turbo#26]
The documentation suggests this works with links only, but it appears that data-turbo="false" does not work with forms:

`<form method="post" action="..." data-turbo="false">...`

When testing it appears forms are submitted through Turbo regardless of this attribute.

https://turbo.hotwire.dev/handbook/drive#disabling-turbo-drive-on-specific-links

Is there a good workaround for this? I need to be able to disable Turbo for some specific forms.

**Comment by seanpdoyle** [comment]
Is this issue resolved by https://github.com/hotwired/turbo/pull/3?

**Comment by danjac** [comment]
@seanpdoyle looks like it could be. For now I'm looking at a custom Stimulus controller to intercept form submit as a temp workaround.

**Comment by boardfish** [comment]
I believe this issue can be closed now. Use any release onward from `dev-builds/latest`, as #3 has now been merged.
