### ISSUE TITLE
Editing a form within a turbo frame - issues

### ISSUE THREAD

**Issue by xhafan** [hotwired/turbo#261]
I edit a form in a turbo frame, on form submit it POSTs the form data and redirects to a url to reload the turbo frame. It works nicely. Now, I'm missing the following:
* on editing cancel, I need to trigger the turbo frames reload from js. So far, this is the only thing which works for me (source [here](https://discuss.hotwire.dev/t/how-to-auto-reload-frame/1872/4)): 
```
    // this makes Turbo reload the frame; it's quite hacky, but don't know how to do it differently.
    var src = turboFrame.attr("src");
    turboFrame.attr("src", "");
    turboFrame.attr("src", src); 
```
I would imagine there would be a Turbo js function to reload the frame.
* When a form submit fails (e.g http status code 500), I was not able to find a way to show an error dialog and execute custom js to clean things up (e.g. remove a spinner and enable the submit button again). I can do these things when I handle the submit in JS manually instead of relying on the browser doing the submit. But when I submit the form manually via ajax, Turbo does not reload the turbo frame. I would imagine I would be able to hook up a custom js code when the browser form submit fails.
* When a turbo frame load request fails, nothing happens - the turbo frame is simply not loaded. I would imagine I would be able to hook up a custom js to handle the error, or the turbo frame would be populated with an error.

So far it feels that Turbo Frames lacks some features for a form editing within a turbo frame.

Example. Turbo frame, readonly mode, showing data:
![image](https://user-images.githubusercontent.com/13038902/116205415-08a87200-a73e-11eb-8d3c-14f0d2190b52.png)
User hits `Edit`:
![image](https://user-images.githubusercontent.com/13038902/116205496-1d850580-a73e-11eb-870a-93bf80e6d14b.png)
`Cancel` goes back to the readonly mode with edits reverted, `Save` saves changes and goes to the readonly mode. Both `Cancel` and `Save` reloads the turbo frame.

**Comment by pocheptsov** [comment]
@xhafan, looks like [Render 400-500 status response HTML](https://github.com/hotwired/turbo/pull/39) should help with your issue then you can render error response HTML and hookup any JS code to it.

**Comment by xhafan** [comment]
@pocheptsov Cheers, I've seen that but it's not clear to me what to do to render HTML error message into the turbo frame. Would you please point me to an example? Thank you.

**Comment by yunggindigo** [comment]
In turbo.8 there is now a frameElement.reload() method to to reload frames also to execute specific javascript on a form error in your controller you would want to do something along the lines of 
`@post = Post.create(post_params)
if @post.save 
  respond_to do |format|
    format.html {}
    format.turbo_stream { # Turbo stream after success }
  end
else 
  respond_to do |format|
    format.html { render :edit }
    format.turbo_stream { # Turbo stream stuff for errors you can replace the whole form with one with errors or just render any sort of partial or html that you could want to show in here }
  end
end`

**Comment by xhafan** [comment]
Thanks @yunggindigo for pointing out [FrameElement.reload()](https://turbo.hotwired.dev/reference/frames#functions), I was able to improve my code using it instead of my previous hacky solution clearing and setting `src` attribute to the same value. 

I'm able to reload the turbo frame when a form is submitted or cancelled, via this stimulus controller:
```
import { Controller } from "@hotwired/stimulus";
import { FrameElement } from "@hotwired/turbo/dist/types/elements";
import { formSubmittedEventName, formEditingCancelledEventName } from "../ViewOrEditForm/ViewOrEditFormController";

export default class TurboFrameController extends Controller {
    static targets = ["turboFrame"];

    readonly turboFrameTarget!: FrameElement;

    connect() {
        this.attachFormEventListeners();
    }

    attachFormEventListeners() {
        this.turboFrameTarget.addEventListener(formSubmittedEventName, this.onFormSubmitted.bind(this), {});
        this.turboFrameTarget.addEventListener(formEditingCancelledEventName, this.onFormEditingCancelled.bind(this), {});
    }

    onFormSubmitted() {
        this.turboFrameTarget.reload();
    }

    onFormEditingCancelled() {
        this.turboFrameTarget.reload();
    }
}
```
So the only thing I'm missing is this: _When a turbo frame load request fails, nothing happens - the turbo frame is simply not loaded. I would imagine I would be able to hook up a custom js to handle the error, or the turbo frame would be populated with an error._ @pocheptsov, any idea? I was not able to dig out any solution from https://github.com/hotwired/turbo/pull/39 . Cheers.

**Comment by brunoprietog** [comment]
Hi @xhafan, Turbo emits several events when this kind of situation occurs. You can add a listener and handle these cases accordingly. You can view the events [here](https://turbo.hotwired.dev/reference/events).
