### ISSUE TITLE
[Discussion] What are best practices for laying out a page and its associated endpoints?

### ISSUE THREAD

**Issue by akatechis** [hotwired/turbo#267]
Apologies if this is already answered in the documentation, but I'm currently setting up a prototype for my company to evangelize the "hotwired architecture", and I'm building it out with a nodeJS backend.

I just discovered the fact (or perhaps re-read, after glossing over a pretty important detail) that for turbo-frames to work, the link that triggers navigation must be within a `<turbo-frame>` itself. While this works well for the example of a message with an edit link inside its own turbo-frame, what are best practices for a top of the page navigation? I currently have it outside of any frame at all (which is why it's not working, at the moment).

Should I create a separate turbo-frame just for the navigation/header partial? I notice that in the docs, the section on cache behavior suggests it's more performant to have an endpoint that just renders this section, since it will have fewer dependent keys (eg, just the user's logged in state, for example, not the entire data of the page).

This also raises the question of how to lay out my backend service's endpoints, and how to compose full-page-rendering-endpoints out of the smaller frame-rendering-endpoints. Eg, if I have a page for "projects" that is composed of a `nav` frame, a `projects` frame and maybe a `footer` frame, should I also have a separate endpoint for `/projects` that renders the 3 partials and glues them together?

I guess my overarching question is: Are there any documents anywhere the lay out how to set up this kind of architecture using a non-Ruby backend (where presumably this stuff has been incubated and the gems are relatively well put-together)?

Followup question: is it OK to have a turbo-frame within another turbo-frame?

**Comment by marcelolx** [comment]
@akatechis I think it would be better open this discussion on https://discuss.hotwire.dev/
