### ISSUE TITLE
Google Interactive Media Ads SDK

### ISSUE THREAD

**Issue by alekszaitsev** [hotwired/turbo#274]
Hi there.
There're the trouble with Google IMA SDK.
Description of issue: there're some block, which should be as permanent through navigating the site (ex. toolbar). And this block are with data-turbo-permanent attribute. There're audio player with ads at this block, and Google IMA SDK created the `<iframe>` with `<video>` tag to play ads.
However, when user browsing the site, ads are broken, because of "Turbo Drive evaluates `<script> `elements in a page’s `<body>` each time it renders the page." - quote from Turbo Handbook. 
It evaluates the `<script>` even if this `<script>` are at the `<iframe>` tag.

**Comment by brunoprietog** [comment]
Hi @alekszaitsev, closing this because it's not a Turbo issue
