### ISSUE TITLE
Doesn't refresh the page content on form submission

### ISSUE THREAD

**Issue by tabuna** [hotwired/turbo#29]
I use to submit the form `" @ hotwired / turbo ":" ^ 7.0.0-beta.1 "`, the code is very simple:

```html
<form action = "/ test" method = "post">
   <input type = "input" name = "name">
   <button type = "submit"> Submit </button>
</form>
```

This works great. But when I get an error, such as a 500 or 200 response, but with different content (debugging page) without 
`<html> <body> ...`, then the page is not actually refreshed, and the form remains (as if nothing was submitted).

![Снимок экрана 2020-12-23 в 21 50 00](https://user-images.githubusercontent.com/5102591/103028562-1324e600-4569-11eb-82c8-72af417af380.png)

**Comment by danjac** [comment]
I'm seeing similar behaviors with turbo streams in some pages - the correct turbo streams content type is used and the content is wrapped in the right tags, but the content is not updated. There are no errors. An identical setup in another page works fine, not sure what the reason is for the inconsistent behavior.

**Comment by thetutlage** [comment]
Turbo streams have to be top level elements. Make sure in your response they are not nested inside any other element.

**Comment by danjac** [comment]
There are some other gotchas as forms are submitted as FormData objects through fetch. I had some legacy forms with server behaviour dependent on submit button named which required adding "value" attributes, which worked with simple browser submission.

**Comment by sstephenson** [comment]
Successful form submissions always need to result in a redirect, but [Turbo 7.0.0-beta.2](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.2) allows you to return HTTP 4xx or 5xx responses in response to failed form submissions.
