### ISSUE TITLE
Having an "action" parameter in form appends "undefined" to URL

### ISSUE THREAD

**Issue by danjac** [hotwired/turbo#30]
If a form has a field/button named "action" e.g.

  `<input type="hidden" name="action" value="signup">`

this will break form submissions by appending "undefined" to the URL e.g. http://localhost/signup/undefined.

**Comment by javan** [comment]
Hello, DOM clobbering 🙃
> **[Issues with Naming Elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Issues_with_Naming_Elements)**
> * `<input name="id">` will take precedence over `<form id="…">`. This means that `form.id` will not refer to the form’s id, but to the element whose name is "`id`". This will be the case with any other form properties, such as `<input name="action">` or `<input name="post">`.

We probably need to prefer `formElement.getElement("action")` over `formElement.action` here:
https://github.com/hotwired/turbo/blob/35ce4aacdd4397092e9bbba682272ae148c8c4d0/src/core/drive/form_submission.ts#L51-L52

**Comment by AboudaSadok** [comment]
i am facing the same issue with odoo 15 , but the problem appears only in the production server, in localhost everything works fine
(i don't have any field with those names )
ERROR: **register/interest/undefined:1 Failed to load resource: the server responded with a status of 404 ()**
can any one guide me to a solution ?

**Comment by CybroOdooDev** [comment]
Hi @AboudaSadok ,
Check if there is a section tag before the form element. I have faced the same issue, on removing the section tag which enclosed the form elements, the issue was solved.
Thanks.
