### ISSUE TITLE
Form interactivity lost on BACK and FORWARD [iOS]

### ISSUE THREAD

**Issue by sudhirj** [hotwired/turbo#302]
If you set up a stimulus controller, on iOS Safari (latest GA) and go back and forward, the element behaves as if the stimulus controller is not attached.

**Comment by sudhirj** [comment]
Managed to attach safari, there was an import map CDN caching problem that was looking for the wrong JS file.

**Comment by sudhirj** [comment]
Nope, caching wasn't the problem. I'm able to reproduce the issue on my app, will try to make a public repro, but sure if any of the codepen style sharing sites will work with back and forward.

**Comment by sudhirj** [comment]
Can confirm that the problem is with form interactivity itself, not just the stimulus controller. I have a stimulus controller to do a confirm on form submit, works fine in all browsers, but hitting back and forward on iOS the submit buttons no longer do anything.

**Comment by tleish** [comment]
I just tested this on iOS safari with a form that has a stimulus attached to the submit event.  I'm unable to reproduce the reported issue.

**Comment by dhh** [comment]
Please reopen if you can boil this down to a reproducible case.
