### ISSUE TITLE
Pauseable rendering breaks after rendering preview

### ISSUE THREAD

**Issue by domchristie** [hotwired/turbo#313]
If the fetch response completes before the paused preview render completes, the visit will attempt to render twice whilst a render is in progress, raising:
https://github.com/hotwired/turbo/blob/49f82135e2a5ec8e3279f78373d69214d06a34fa/src/core/view.ts#L50

A quick fix is to disable previews, but ideally, in the case of animating page transitions, the preview would animate in first, and then be seemlessly replaced by the server response.

**Comment by dhh** [comment]
cc @kirillplatonov

**Comment by kirillplatonov** [comment]
Checking it
