### ISSUE TITLE
data-turbo-method='delete' on following 302 redirect uses same HTTP verb

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#320]
When moving some of our delete links using data-turbo-method='delete' attribute,  I noticed that turbo is following the 302 redirect using the same HTTP verb.  data-turbo-method='post' seems to work fine.

- turbo 7.0.0-beta.8
- chrome 91

**Setup**
![image](https://user-images.githubusercontent.com/571649/126150094-d1e4f2a5-8c4d-4783-b8d9-36d6bed7cbca.png)

Simple rails action:

```
 def destroy_image
    ActiveStorage::Attachment.find(params[:id]).purge_later
    redirect_to settings_recruitment_career_sites_url
  end
```

Response after clicking destroy,

![image](https://user-images.githubusercontent.com/571649/126150269-10f3ada0-bbf3-46a8-9d05-ea2fe30b56e2.png)

**Expected**

Turbo should issue GET request to follow the redirect not keeping the same HTTP verb as the link.

**Comment by ParamagicDev** [comment]
This has to do with the HTTP spec around fetch requests. This is a duplicate of a previous issue with some discussion around it.

Solution:

send back a `status: 303` header to tell all follow up fetches to be a GET request.

https://github.com/hotwired/turbo/issues/84

**Comment by ParamagicDev** [comment]
For anyone looking to tackle this and as a reminder to myself if no one beats me to it, work would happen here:

https://github.com/hotwired/turbo/blob/eae977ceb86ee8e61766ffb40ac3894bdfacc7ef/src/core/session.ts#L144

basically if the linkMethod is POST or GET, leave it alone.

if the linkMethod is anything else, make it a POST and then add a "_method" hidden form value. This is how UJS handles it and why a data-method from UJS works with Turbo.

https://github.com/rails/rails/blob/6442aac195a227455c53c5b5b00c6818268379e5/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L16

**Comment by acetinick** [comment]
As @ParamagicDev correctly suggested using a redirect with status code 303 worked fine.  Closed as there are other issues relating to this.
