### ISSUE TITLE
Expose isSamePage to turbo:visit events

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo#321]
#298 was a very welcome change, as now I can drop `data: { turbo: !current_page?(thing_path) }` from links that are anchors on the current page. However, `turbo:visit` events now fire for visits to anchors on the same page. I'm sure this is potentially useful in some ways, but for now, it's meant that I've had to go from hooking into `turbo:visit` to using `turbo:before-visit` as follows:

```js
import isEqual from "lodash.isequal"

document.addEventListener("turbo:before-visit", function (e) {
  const attributes = ({ origin, pathname }) => ({ origin, pathname })
  if (
    !isEqual(attributes(window.location), attributes(new URL(e.detail.url)))
  ) {
    // do things here
  }
})
```

What I'm doing there is pulling the `origin` (`http://example.com`) and the pathname (`/blog`, without an anchor or any query params) from the window location before the request is processed, and comparing it with those the target URL. If they're identical, then it's safe to say we shouldn't do what would otherwise be triggered under `turbo:visit`.

It'd be nicer to be able to, for example, do this:

```js
document.addEventListener("turbo:visit", function (e) {
  if(e.samePage) { return; }
  // do things here
})
```

**Comment by dhh** [comment]
cc @domchristie Does seem a bit surprising for turbo:visit to fire if you're staying on the same page? Like DOMElementLoaded or whatever it is wouldn't fire for that.

**Comment by domchristie** [comment]
> Does seem a bit surprising for turbo:visit to fire if you're staying on the same page?

I tend to agree. The same-page anchor system does use a `Visit` to do it's thing, but the fired events do seem weird. Here are the events during a same-page visit:

1. `turbo:click`
2. `turbo:before-visit`
3. `turbo:visit`
4. `turbo:before-cache`

This could lead to some odd situations, particularly if people are tearing down JavaScript behaviour on `turbo:before-cache`

I think same-page visits should be "silent" i.e. not fire `turbo:before-visit`, `turbo:visit`, or `turbo:before-cache`. This would also echo the behaviour that the native adapters take.

**Comment by dhh** [comment]
Yes, that makes sense to me. Let's do that.

**Comment by boardfish** [comment]
This would resolve my original issue. And I suppose visits as a feature here are redundant, as the same thing could be achieved with event listeners on the target elements. I'm happy with this approach.

**Comment by boardfish** [comment]
Turns out my original fix for this issue has a bug. I was doing this:

```js
document.addEventListener("turbo:before-visit", function (e) {
  // Subject to hotwired/turbo#321
  const attributes = ({ origin, pathname }) => ({ origin, pathname })
  if (
    !isEqual(attributes(window.location), attributes(new URL(e.detail.url)))
  ) {
    window.ga("send", "pageview", e.detail.url)
  }
})
```

However, since I'm having to use the `before-visit` event to figure this out, I can't track visits to pages from a fresh page load.

This feels like a lot for me to ask, but a bugfix release would be appreciated. I've been trying to install via `yarn add github:hotwired/turbo#d45bf3fa40f9ea284dcd11d6c46b70b22e898c54`, but this hasn't been working, presumably because the package itself isn't built.

**Comment by domchristie** [comment]
Latest builds are available here from https://github.com/hotwired/dev-builds/releases, so I think you could try:

```
yarn add https://github.com/hotwired/dev-builds/archive/refs/tags/@hotwired/turbo/latest.tar.gz
```
