### ISSUE TITLE
Clicking a link with target: "_top" causes a full page reload without turbo

### ISSUE THREAD

**Issue by yunggindigo** [hotwired/turbo#323]
I have a turbo-frame showing posts inside of it, this is using a post partial and that has some post information and a link to the post if you click the link it will use turbo to navigate the posts frame to the url on the link since there is no posts frame on the show page this will remove the posts frame and throw an error no matching frame with id="posts", to get around this I put target: "_top" which should navigate the page and I expect it to use turbo for speed and to preserve permanent elements etc but right now it does a full page reload. 

This was also mentioned on hotwire discussion with no answer https://discuss.hotwired.dev/t/getting-a-link-inside-of-a-frame-to-trigger-a-regular-turbo-visit/2489

**Comment by yunggindigo** [comment]
I was able to fix this problem by writing data: { turbo_frame: "_top" } this will navigate the page with turbo. This is never discussed in the handbook I just saw it in the tests in turbo source code, should that be added there? or should target: "_top" be extended to use similar functionality to navigate with turbo and then if they write target: "_top", data: { turbo: false } they will be able to force it to use default target: "_top"

**Comment by feliperaul** [comment]
@enoch-tamulonis Thank you so much for this. I too find it weird that this wasn't mentioned in the docs more clearly, because it's such a common use-case, and it took me hours to get to this issue. 

I also agree with you that all links should be handled by Turbo by default, unless they are specifically opted-out as `data: { turbo: false }`.

**Comment by dhh** [comment]
Feel free to propose any revisions to https://turbo.hotwired.dev/handbook/frames#targeting-navigation-into-or-out-of-a-frame.
