### ISSUE TITLE
Absence of turbo:load event for 4xx html responses

### ISSUE THREAD

**Issue by fwilkens** [hotwired/turbo#325]
Hi,

For those of us on the turbolinks -> turbo upgrade path, it was great to see https://github.com/hotwired/turbo/pull/39 in response to https://github.com/hotwired/turbo-rails/issues/12 -- thanks for that. One thing I've noticed, however, is that when a 422 html response is rendered by Turbo in cases like this, `turbo:load` is not fired. I just checked in one of our apps with turbolinks, and it looks like Turbolinks _would_ fire `turbolinks:load` in such a case.

The outcome with Turbo is that the 422 html response is rendered, but javascript functionality that hinges on `turbo:load` is broken. My expectation was that `turbo:load` would fire -- is that a reasonable expectation or is there something I'm missing here? One obvious solution is to refactor these cases to use a frame or stream I guess, but my hope after seeing https://github.com/hotwired/turbo/pull/39 was that I could avoid frame/stream refactors until after the initial swap of turbo in for turbolinks and validating that Drive worked more/less ootb with our apps (following the notes in https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md).

Here's a repo demonstrating the lack of the `turbo:load` event in such a case (forked and slightly modified demo chat app) https://github.com/fwilkens/hotwire-rails-demo-chat/tree/demo_422_no_event. To see the issue, submit the New room form without a name, and note that there's no console log for the event listener on `turbo:load`.

**Comment by willnet** [comment]
@fwilkens I know it's inconvenient, but this is an intentional specification.

https://github.com/hotwired/turbo/issues/85#issuecomment-756191950

**Comment by fwilkens** [comment]
Thanks @willnet -- not sure how missed that issue. I guess I'll close this issue, since 85 was closed with an explanation.
