### ISSUE TITLE
Programatically invoking form.submit() does not trigger a turbo submit

### ISSUE THREAD

**Issue by mvdmsoftware** [hotwired/turbo#33]
I've got a Stimulus Controller that automatically submits a form when any input is changed. However, this is not picked up by Turbo. Here is the controller:
```js
/*
   Example usage (Rails):
   <%= form_with(url: articles_path, method: :get, local: true, html: { 'data-controller': 'form-auto-search' }) do |form| %>
      // From contents
   <% end %>

   Example usage (plain HTML):
   <form data-controller="form-auto-search">
      // Form contents
   </form>
 */
import { Controller } from "stimulus";
export default class extends Controller {
   connect() {
      if (this.element.tagName !== "FORM") {
         console.error("The form-auto-search controller should be added to the form element. It is set to: ", this.element.tagName);
         return;
      }

      this.form = this.element;

      const inputs = this.element.getElementsByTagName("input");
      for (let i = 0; i < inputs.length; i++) {
         const input = inputs[i];
         input.addEventListener("change", () => this.handleInputEvent());
      }
   }

   handleInputEvent() {
      this.form.submit();
   }
}
```

To get this to work, I have to `import @rails/ujs` and use `Rails.fire(this.form, 'submit');` instead of `this.form.submit()`.

Am I doing something wrong?

**Comment by seanpdoyle** [comment]
Turbo forms listen for [`submit` events][https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent] fired during the `<form>` element submission lifecycle.

According to the MDN documentation, invoking [`HTMLFormElement.submit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) _does not fire these events:

> The HTMLFormElement.submit() method submits a given `<form>`.
> This method is similar, but not identical to, activating a form's submit <button>. When invoking this method directly, however:
>
> *   No submit event is raised. In particular, the form's onsubmit event handler is not run.
> *   Constraint validation is not triggered.
> The [`HTMLFormElement.requestSubmit()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) method is identical to activating a form's submit `<button>` and does not have these differences.

The `HTMLFormElement.requestSubmit()` is [not yet supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit#Browser_compatibility), so you might want to install a [polyfill](https://github.com/javan/form-request-submit-polyfill).

**Comment by mvdmsoftware** [comment]
Thank you, @seanpdoyle, for the explanation. I also appreciate the `requestSubmit()` suggestion, I didn't know that one yet.

I'll get to work, and I'll close this issue. Thanks again!
