### ISSUE TITLE
Manually trigger a turbo frame request to update a frame

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#330]
Hi,

I am looking for a way without using Turbo Streams to simply replace a target frame using a request object.  In this example I trying to use Request.js where I am doing the following:

`new window.FetchRequest("get", "<%= request.url %>", { headers: {'Turbo-Frame': 'example-frame'}}).perform()`

This returns the expected html with the **example-frame** frame, however Turbo doesn't do anything with it.   

Is there a way to trigger a Turbo frame refresh from a URL using javascript?

Would be super useful to have a function exposed by Turbo to do something like

`Turbo.visitFrame(url, method, "example-frame")`

Use case for me:   I have javscript events that are triggered to refresh data, and would like to force update frames as needed when they come in.   I could use streams, but frames is so much easier.

**Comment by tleish** [comment]
Any concerns with updating the src attribute of a turbo-frame element using javascript?

**Comment by acetinick** [comment]
Mmm never thought of that I’ll try) but will it trigger refresh only if url changes? Will I need to add some time stamp to end as parameter to force refresh?

**Comment by tleish** [comment]
You can try to toggle the src (set to blank and then set to desired url) to force a reload.  

```javascript
  turboFrame.src = null;
  turboFrame.src = url;
```

You can also try the new reload function [#206] releases in v7.0.0-rc.1, which I believe does the same thing.

**Comment by acetinick** [comment]
Ahh wow that just worked! .reload() did the trick.  Thanks so much ,  missed that coming into rc1 release.
