### ISSUE TITLE
Turbo Drive: "Referer" header set to target URL, not current URL

### ISSUE THREAD

**Issue by awh-tokyo** [hotwired/turbo#332]
When using Turbo Drive, the Referer header seems to be set to the target URL, not the current URL:

![Screen Shot 2021-08-03 at 12 33 25](https://user-images.githubusercontent.com/689566/127953799-547aa015-451b-4ce7-af88-49c2c1e02788.png)

This was following a link from /visits/ so I would have expected that to be the Referrer.

Is this by design?  Is there some other way to know the referring page?  I need to redirect back to different URLs once editing is done depending on the referring URL.

**Comment by awh-tokyo** [comment]
EDIT:  I'll note that by adding data-turbo="false" to those links, it works as expected and I receive the appropriate Referer header.  I've done that for now, which isn't my favourite solution, but lets me get back to work.

**Comment by zzeligg** [comment]
I confirm this occurs with v7.0.0-rc.1. It breaks `:back` url functionality in Rails link / url helpers.

It was introduced with the Pausable requests changes: #306 

When commenting out line 82 in `fetch_request.ts` :

https://github.com/hotwired/turbo/blob/main/src/http/fetch_request.ts#L80

which simply disables `await this.allowRequestToBeIntercepted(fetchOptions)` in `FetchRequest#perform()`, then the Referer header sent is the correct one.

**Comment by edwinv** [comment]
In #344 I've added a test to ensure the header is set correctly. The test currently fails and I can confirm what @zzeligg found out about the changes in #306.
