### ISSUE TITLE
Support replacing state

### ISSUE THREAD

**Issue by boardfish** [hotwired/turbo#335]
As highlighted [here](https://discuss.hotwired.dev/t/how-to-change-current-url/1846/4?u=boardfish), if I use `Turbo.navigator.history.replace({ absoluteURL: '/posts/1/edit' })` to replace the current state, I get the following error when clicking a link on the page:

```
Uncaught TypeError: url.href is undefined
    getAnchor turbo.es2017-esm.js:261
    getRequestURL turbo.es2017-esm.js:280
    locationWithActionIsSamePage turbo.es2017-esm.js:3450
    Visit turbo.es2017-esm.js:2229
    startVisit turbo.es2017-esm.js:3289
    visitProposedToLocation turbo.es2017-esm.js:2788
    visitProposedToLocation turbo.es2017-esm.js:4372
    proposeVisit turbo.es2017-esm.js:3281
    visit turbo.es2017-esm.js:4274
    followedLinkToLocation turbo.es2017-esm.js:4339
    clickBubbled turbo.es2017-esm.js:3217
    clickCaptured turbo.es2017-esm.js:3204
    start turbo.es2017-esm.js:3230
    start turbo.es2017-esm.js:4235
    start turbo.es2017-esm.js:5435
```

The link is inside a Turbo frame which has `target="_top"` set.

Since Turbo's own history breaks under native `window.history.replaceState`, it'd be good to have a supported alternative in a similar way to how Turbo callbacks replace `$(document).ready()` in jQuery, for example.

**Comment by tortuetorche** [comment]
Hi @boardfish,

If you try with this command: `Turbo.navigator.history.replace(new URL('http://localhost/posts/1/edit'))`, is it OK?

Cheers,
Tortue Torche

**Comment by boardfish** [comment]
Thanks @tortuetorche, that appears to have worked. I ended up using the following:

```js
window.Turbo.navigator.history.replace(new URL(this.turboFrameTarget.src, `${window.location.protocol}//${window.location.host}`))
```

**Comment by seanpdoyle** [comment]
@boardfish When constructing a [new URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#parameters) instance, have you tried passing the value of [Node.baseURI](https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI) as the second argument?

```js
const { src, baseURI } = this.turboFrameTarget

const url = new URL(src, baseURI)
```

**Comment by boardfish** [comment]
I didn't know that was a thing! Good shout - thanks @seanpdoyle :sparkles:

**Comment by pySilver** [comment]
While it works almost OK, I bet it is not necessarily what a user might expect. Two issues:
* User cannot return to the previous state anymore
* Preview holds outdated state

This is what I've come up with instead: https://github.com/hotwired/turbo/issues/792#issuecomment-1310399203

It feels a little bit hackish and I'd love to have a cleaner way to update URLs from the stream responses.
