### ISSUE TITLE
No interface for listening to Turbo errors

### ISSUE THREAD

**Issue by tomwaddington** [hotwired/turbo#336]
Any errors within Turbo are directly output with `console.errors`, meaning 3rd party exception tracking libraries do not (by default) capture possible failures within the page.

As we migrate to Turbo, I'd like to keep track of any user-facing errors recognised by Turbo,

I'd be happy to try and improve this, possibly by emitting a `CustomEvent` that could be listened to by the host page?

**Comment by dhh** [comment]
Happy to see a PR for this 👍
