### ISSUE TITLE
Turbo drive stream updates, clicking browser back button does not change the page, only changes url

### ISSUE THREAD

**Issue by A7madXatab** [hotwired/turbo#338]
Hello, so today i've had this weird issue, 

https://user-images.githubusercontent.com/38360603/129346329-be8fcb33-f907-446a-9e3b-5e7c52aa6186.mov

If you can see, when i click the browser back button the url changes but turbo does not replace the page again, when i inspect the network tab when clicking the browser back button no request is made to the backend to refetch the old page

<img width="1045" alt="Screenshot 2021-08-13 at 13 51 52" src="https://user-images.githubusercontent.com/38360603/129346491-4d6b6592-8da8-4071-8984-14c5524c3c2f.png">

In the same page i have a `:back` button link that works like a charm!. So, i would appreciate any help. Thanks!.

**Comment by tleish** [comment]
See also [discuss.hotwired.dev - clicking browser back button does not change the page, only changes url](https://discuss.hotwired.dev/t/turbo-drive-stream-updates-clicking-browser-back-button-does-not-change-the-page-only-changes-url/3151)
