### ISSUE TITLE
Is there a way to programmatically invoke a Turbo Stream?

### ISSUE THREAD

**Issue by panda-madness** [hotwired/turbo#34]
Ditto on the issue title. It would be nice to have a programmatic way to invoke a stream URL, same way we currently can trigger a visit with `Turbo.visit()`.

`Turbo.stream('/some/url/here').then(r => console.log('maybe even return a promise'))`.

**Comment by thetutlage** [comment]
Yup, it will open up a room for lot of custom features. One is to have infinite scroll. I detect the page end using Javascript and then load more items

**Comment by danjac** [comment]
You can use visit() to fetch a stream, unfortunately it pushes the URL to your history. I've found axios.get() does not work - Turbo doesn't detect the incoming stream. What about plain fetch() ?

**Comment by danjac** [comment]
I haven't found any obvious way to trigger a stream using fetch(). Of course the server can return a valid stream, but Turbo just ignores it. The only way seems to be through a WebSocket, or by a form or link submission. You can try hacking a form submit with requestSubmit() (plain submit() won't work) but this feels hacky compared to a simple API call.

**Comment by sstephenson** [comment]
There's no such thing as a "stream URL," but there are a few ways to work with Turbo Streams programmatically.

If you have a WebSocket or EventSource object, you can use `Turbo.connectStreamSource(object)` to process stream messages automatically as they come in. (You can actually pass any object which responds to `addEventListener("message", ...)` and dispatches `message` events.)

If you have a stream message in a string of HTML that you received from a fetch request, you can call `Turbo.renderStreamMessage(html)`. Or you can just manually insert the HTML into your document! [That's what Turbo does internally](https://github.com/hotwired/turbo/blob/18b755f6210a270ad6d9eedaf1195a474e82d9cb/src/core/session.ts#L85-L87).

**Comment by zealot128** [comment]
For reference, @sstephenson hint about using Turbo.renderStreamMessage, I was able to use fetch together with Turbo to fetch outside of Turbo's realm and pipe the response to Turbo, which handled the containing turbo-stream actions without problem. Important to note, that you need to pass headers Accept to the fetch, so the controller can respond with a ``turbo_stream`` response format.

```javascript
 fetch(href, {
      headers: {
        Accept: "text/vnd.turbo-stream.html",
      },
    })
      .then(r => r.text())
      .then(html => Turbo.renderStreamMessage(html))
//  optionally reflect the url    .then(_ => history.replaceState(history.state, "", href))
```

**Comment by tonywok** [comment]
Nice one @zealot128. I've been using this same approach to refactor some stuff I was doing with stimulus to turbo streams.

**Comment by chriskroon** [comment]
Hey, I had the exact same problem. I solved it this way.

My chat render got this (haml)
`.single-chat{user_id: chat.user_id, id: dom_id(chat)}`

Now I can add some css via the view (haml):
`:css
  .chat-room-content .chats .single-chat[user_id="#{cu.id}"] .chat-content{
    background: #d8f4d0;
  }
  .chat-room-content .chats .single-chat[user_id="#{cu.id}"] .chat-content .time{
    left: -38px;
  }
  .chat-room-content .chats .single-chat[user_id="#{cu.id}"]{
    text-align: right;
  }`

Now I can tell if the chat is from "current_user" or not (cu is a shortcut for current_user in my application_helper).

Hope it helps!

**Comment by buncis** [comment]
we have this https://github.com/rails/request.js#how-to-use to make it easier to do the things that these guys do

**Comment by aldrienht** [comment]
Thanks to @tonywok 
this line saves my day `.then(html => Turbo.renderStreamMessage(html))`
