### ISSUE TITLE
Links with method not work if used inside another form

### ISSUE THREAD

**Issue by davidgil** [hotwired/turbo#340]
I detect an issue with the data-turbo-method attribute on links that are included inside another form, this is a follow up of:
https://github.com/hotwired/turbo/pull/299

In session.ts: 
`
convertLinkWithMethodClickToFormSubmission(link: Element) {
    const linkMethod = link.getAttribute("data-turbo-method")

    if (linkMethod) {
      const form = document.createElement("form")
      form.method = linkMethod
      form.action = link.getAttribute("href") || "undefined"

      link.parentNode?.insertBefore(form, link)
      return dispatch("submit", { cancelable: true, target: form })
    } else {
      return false
    }
  }
`
the "virtual" form created is injected in the parent node of the link, the problem is that if the link is inside another form this functionality dont work. The solution could be to inject the form at the end of body?

`
convertLinkWithMethodClickToFormSubmission(link: Element) {
    const linkMethod = link.getAttribute("data-turbo-method")

    if (linkMethod) {
      const form = document.createElement("form")
      form.method = linkMethod
      form.action = link.getAttribute("href") || "undefined"

      document.body.appendChild(form)

      return dispatch("submit", { cancelable: true, target: form })
    } else {
      return false
    }
  }
`

**Comment by dhh** [comment]
I like that idea. Do make a PR for it 👍

**Comment by davidgil** [comment]
My first PR so... 
https://github.com/hotwired/turbo/pull/341

**Comment by Intrepidd** [comment]
@dhh Can we reopen this issue ? The commit was reverted so we are still facing this issue. I would be glad to give it a swing, any pointers on the way you would like to see it done ?
