### ISSUE TITLE
head script not updating after first click

### ISSUE THREAD

**Issue by flihub** [hotwired/turbo#347]
<script type="application/ld+json">  has BreadcrumbList data, first click script content data updated.
After first click script appending to head always.

turbo v7.0.0-rc.1

![image](https://user-images.githubusercontent.com/16720735/130346301-863e77bf-a63b-4994-bd5e-246dc1f48a3a.png)

**Comment by dhh** [comment]
Please take usage questions to discuss.hotwired.dev.
