### ISSUE TITLE
Is there a way to persist Turbo cached pages to browser (Localstorage/IndexedDB/Cache Storage)?

### ISSUE THREAD

**Issue by frederikhors** [hotwired/turbo#348]
Is there a way to persist Turbo cached pages to browser (Localstorage/IndexedDB/Cache Storage)?

**Comment by dhh** [comment]
No, but that's an interesting idea. Would basically be like a pseudo service worker setup. Feel free to explore in a PR!

**Comment by frederikhors** [comment]
> No, but that's an interesting idea.

So why did you close it? 😄

**Comment by dhh** [comment]
Because we generally don't use the issue tracker for feature requests without PRs. Feel free to open a PR if you decide to tackle this! ✌️

**Comment by jonahgeorge** [comment]
Linked closed tickets here for easier discoverability:
- https://github.com/hotwired/turbo-android/issues/222
- https://github.com/hotwired/turbo-ios/issues/87
