### ISSUE TITLE
data-turbo-method new functionality breaking out of frame

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#358]
Related I believe to this PR #341,  what I am seeing now is that when using data-turbo-method within a turbo frame instead of doing the normal turbo request, will break out of the current frame.  As the form is created dynamically end of the body now it always does a full page refresh, rather than using the frame in context of the parent frame.

I think perhaps solution here is to also find the immediate parent turbo-frame element (if exists) and use the ID of that frame to inject as a data-turbo-frame attribute into the dynamic form created.  That way I pretty sure will do turbo request as expected within frame.

**Comment by dhh** [comment]
Doh. Yes of course. This is a regression. Cc @davidgil.

**Comment by acetinick** [comment]
@dhh perhaps PR #341 should be reverted in another release of hotwire until it gets resolved?
