### ISSUE TITLE
Lack of source code documentation

### ISSUE THREAD

**Issue by olhor** [hotwired/turbo#373]
Tried to dig in documentation in order to add my ideas into source but I see that the source code lacks documentation HUGELY. 
Is this on purpose?

**Comment by dhh** [comment]
The source is the documentation.

**Comment by ParamagicDev** [comment]
@olhor to put this more delicately, the source code is intended to read as documentation. Turbo isn't littered with source code comments so as to not litter the source code.

I'm not saying this is right or wrong, it's just how the hotwired team chose to approach their source code documentation.

**Comment by olhor** [comment]
@ParamagicDev Thanks for clarification. It was just odd to me after comparing such approach to Rails which is written in (self-documenting) Ruby where still documentation exists. I hope it will not change in the future. Folks got used to it imho.

**Comment by ParamagicDev** [comment]
@olhor I think part of the reason for that is the rails docs leverage the documentation you see in the source code to generate the API docs. In addition Rails is a much larger project with a lot more moving parts, so self documenting code hits a point of diminishing returns when you get to a project size as large as Rails.
