### ISSUE TITLE
TurboDrive fires on forms despite being disabled in Safari 15 beta

### ISSUE THREAD

**Issue by terracatta** [hotwired/turbo#390]
Over the last week I've noticed a big uptick in JS exceptions in my app. All of the exceptions were for browsers running the Safari 15 beta. After investigating, I learned that on a form submission, Turbo Drive would fire even if the submit button had the attribute `data-turbo=false`

After further investigation, I discovered the `submitter` property of the `SubmitEvent` was always null. It seems Safari 15 beta now implements the SubmitEvent, but due to a bug in their implementation, they do not populate the `submitter` property.

Since the `submitter` property is `null` TurboDrive cannot inspect its attributes to see if it should delegate control of the form submission back to the browser. 

[This bug was recently patched](https://bugs.webkit.org/show_bug.cgi?id=229660), but it is unclear when it will hit Safari 15 beta users, it's possible it won't for months.

I'm going to continue looking for the most elegant workaround, but I wanted to raise the issue here in case there was an appetite to extend the existing polyfill to officially fix this unfortunate situation.

**Comment by terracatta** [comment]
If anyone is looking for a workaround, I am including this file in my JS bundle and it seems to fix the problem. 

It's basically a ES6 version of the existing polyfill (since I don't use Typescript in my app) except it forces it on for the broken Safari. Should be safe to run on top of the existing polyfill code.

```javascript
// This Polyfill is almost an exact copy of https://github.com/hotwired/turbo/blob/8eaafd4255a6619bbe3bb7f7ef4f5ceaec6a9a24/src/polyfills/submit-event.ts
// except that it fixes https://github.com/hotwired/turbo/issues/390
// This can be removed when a fixed beta for Safari 15 comes out.

"use strict";
const submittersByForm = new WeakMap;
function findSubmitterFromClickTarget(target) {
    const element = target instanceof Element ? target : target instanceof Node ? target.parentElement : null;
    const candidate = element ? element.closest("input, button") : null;
    return (candidate === null || candidate === void 0 ? void 0 : candidate.type) == "submit" ? candidate : null;
}
function clickCaptured(event) {
    const submitter = findSubmitterFromClickTarget(event.target);
    if (submitter && submitter.form) {
        submittersByForm.set(submitter.form, submitter);
    }
}
(function () {
    if ("submitter" in Event.prototype)
        return;

    let eventType;
    // Certain versions of Safari 15 Beta have a bug where they won't
    // populate the submitter. This hurts TurboDrive's enable/disable detection.
    // See https://bugs.webkit.org/show_bug.cgi?id=229660
    if ("SubmitEvent" in window && /Apple Computer/.test(navigator.vendor)) {
      eventType = SubmitEvent;
    } else if ("SubmitEvent" in window) {
      return; // polyfill already loaded
    } else {
      eventType = Event;
    }

    addEventListener("click", clickCaptured, true);
    Object.defineProperty(eventType.prototype, "submitter", {
        get() {
            if (this.type == "submit" && this.target instanceof HTMLFormElement) {
                return submittersByForm.get(this.target);
            }
        }
    });
})();
```

**Comment by dhh** [comment]
Is this bug in a released version of Safari or only in a tech preview release?

**Comment by terracatta** [comment]
It’s a bug in the beta release of Safari, I’m not sure if it is also in the tech preview.  I downloaded it on the top link on this page. 

https://developer.apple.com/safari/download/

This bug likely will not exist when the final version of macOS Monterey comes out.

**Comment by dhh** [comment]
Gotcha. I think fine to leave this issue open, then, for anyone who needs to deal with the beta situation. But don't think we need to ship anything in the official release.

**Comment by G3z** [comment]
I've just encountered this issue with Safari 15.0 final (16612.1.29.41.4, 16612)  on OS X 11.6

**Comment by michalsznajder** [comment]
I have this on Version 15.0 (15612.1.29.41.4, 15612) on Catalina 10.15.7 and on latest iOS 15. Both versions are not beta, just regular updates from App Store.

In my case all my I had `<button>` with `formaction` and it was ignored so forms were posted to original `form` action. 

My customers on latest iOS could not add items to shopping cart because of this bug. No items in cart = no sales = no revenue. Not funny... 

@terracatta thanks for polyfill works like charm! ❤️

**Comment by terracatta** [comment]
@dhh happy to put this fix a PR since this bug snuck into Safari 15 stable if you'd like. Seems like we are going to be dealing with this problem at a bigger scale than we first thought.

**Comment by dhh** [comment]
Yes, if it's out in Safari 15 stable, I think we should ship a proper fix. Also, I've seen a few other reports about issues regarding Turbo firing when someone believes it should be turned off. If you're inside this part of the code, maybe if you want to have a look. Believe it might have been with data-turbo-method links?

**Comment by terracatta** [comment]
@dhh, I'll quickly get the updated polyfill PR up since that is a known quantity. 

I'll take a peek at the general code as well, if you are able to get a test-case from someone who is having trouble please file an issue and CC me on it.

**Comment by terracatta** [comment]
> maybe if you want to have a look. Believe it might have been with data-turbo-method links?

Oh wait, Are you perhaps referring to this issue? https://github.com/hotwired/turbo/issues/392. If so I think I can sneak that in as well.

**Comment by dhh** [comment]
That was the one!

**Comment by dhh** [comment]
Yeah, let's def do as separate PRs. Thanks for working on this ✌️❤️
