### ISSUE TITLE
Speed up DOM read/writes via Batching

### ISSUE THREAD

**Issue by tleish** [hotwired/turbo#407]
Any thoughts on speeding up turbo and/or stimulus read/write DOM operations using a library like [fastdom](https://github.com/wilsonpage/fastdom).

> Eliminates layout thrashing by batching DOM read/write operations (~600 bytes minified gzipped).

**Comment by dhh** [comment]
Got any compelling benchmarks where what we're doing right now can be sped up in a way that users would really appreciate?

**Comment by tleish** [comment]
Testing this further, this is helpful when performing multiple read/writes at once.  The only place I could see this being helpful would be in turbo-streams, but not sure it's worth adding the code for the payoff. 

Closing.
