### ISSUE TITLE
Setting `TurboFrameElement.src` twice in quick succession can show wrong source

### ISSUE THREAD

**Issue by TastyPi** [hotwired/turbo#417]
If `src` is set twice in quick succession and the second source loads before the first source, then the `turbo-frame` will display the first source instead of discarding that request.

My use case is a kind of reactive preview, where I update the src of a `turbo-frame` on each input event of a form. Typing two characters in quick succession can be fast enough to trigger this issue. I'm currently working around it by using `await TurboFrameElement.loaded`.

```js
export default class extends Controller {
  static targets = ["frame", ...]

  async load() {
    // Wait for the frame to finish loading whatever it is currently loading, but ensure we only wait once.
    if (this.loading) {
      return
    }
    this.loading = true
    await this.frameTarget.loaded
    this.loading = false
    this.frameTarget.src = ...
  }
}
```

**Comment by seanpdoyle** [comment]
Generally, I think [debouncing the event](https://thoughtbot.com/blog/hotwire-typeahead-searching#searching-while-typing) that triggers the `src` navigation could be the most effective step you could take in this scenario to mitigate this issue. I'd even recommend doing that even after a fix for this issue ships.

With that being said, thank you for sharing this context. I believe a fix for this could involve changing the `FrameController` to cancel any pending promises (via a [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) instance) from previous requests, which is triggered after changes to the `src` attribute:

https://github.com/hotwired/turbo/blob/acb003d9879311b7f44fe12499ad333605ad3cdd/src/core/frames/frame_controller.ts#L86

**Comment by TastyPi** [comment]
I agree debouncing would be a good idea for this use case, the bug could present itself if one of the requests took longer than the debounce time. Unlikely, but possible.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/418. I'm not sure how to add a test to the suite to cover this scenario. Could you try it out to see if it addresses your scenario?
