### ISSUE TITLE
Turbo Stream subscription sometimes fails when switching pages using Turbo Drive

### ISSUE THREAD

**Issue by moveson** [hotwired/turbo#422]
I have a view (the "Draw Tickets" view) that subscribes to several Turbo Streams. The app allows the user to quickly switch to another view (the "Setup" view). 

If I am in the Draw Tickets view and quickly switch to the Setup view and back to the Draw Tickets view (all within one second or so), some of my Turbo Stream subscriptions do not work, and I end up with confusing results.

The screen capture attached is from Safari 15.0, but the same behavior can be reproduced in Chrome 94.0.

By way of explanation, in the screen capture attached, the Draw Tickets view is subscribed to 6 turbo streams: One for each division's header, and one for each division's draws. The header streams update the progress bars. The draw streams prepend draws to the lists below the headers. 

The first part of the capture demonstrates expected behavior. The second part demonstrates what happens after the switch back and forth. In this example, three of the subscriptions are not reestablished after the switch. There doesn't seem to be any pattern as to which streams reestablish properly and which do not.

The capture is too long to attach in github, but here's a link: https://youtu.be/WH0j8p9qW3E

**Comment by dhh** [comment]
This is fixed in latest rails/main. It was a general issue with Action Cable.

**Comment by nicowenterodt** [comment]
I have the same with a turbo-drive enhanced Rails 7.1.3 App

When I navigate away an re-visit a page the unsubscribe / subscribe messages are piling up. I briefly described it [here](https://github.com/hotwired/turbo-rails/issues/173#issuecomment-2041356740).

It seems related to the [prefetch on hover](https://turbo.hotwired.dev/handbook/drive#prefetching-links-on-hover) feature which is default as of Turbo v8. 

When deactivated the prefertch-on-hover with:

```<meta name="turbo-prefetch" content="false">``` 

it is working again as expected. I'm still investigating but I think it might be related with the [SubscriptionGuarantor](https://github.com/rails/rails/blob/main/actioncable/app/javascript/action_cable/subscription_guarantor.js) introduced with [Issue 41581](https://github.com/rails/rails/pull/)
