### ISSUE TITLE
Eager/lazy loaded turbo-frames are reloaded after snapshot restoration

### ISSUE THREAD

**Issue by tobyzerner** [hotwired/turbo#429]
Navigating away from a page, then going back, causes all eager/lazy loaded turbo frames to be reloaded on the original page after the snapshot is restored.

Simple example:

```html
<turbo-frame id="page_1" target="_top">
  <a href="/posts/1">Post 1</a>
  <turbo-frame id="page_2" src="?page=2" loading="lazy" target="_top"></turbo-frame>
</turbo-frame>
```

When you visit the page initially, the #page_2 frame lazy loads as expected. If you click on "Post 1" and then go back, after the page snapshot is restored, the #page_2 frame reloads, which is undesirable.

**Comment by tleish** [comment]
One way to do this would be to remove `src="?page=2"` from the turbo-frame after it renders.  There might be some cases where you wouldn't want to do this by default.

As with many other solutions, you could easily control this with a simple stimulus controller.  Something like:

```javascript
class AttributeController extends Controller {
  remove({ params: {name}}) {
    this.element.removeAttribute(name);
  }
}
```

```html
<turbo-frame id="page-2020-12" src="page2.html" data-controller="attribute" data-action="turbo:frame-load->attribute#remove" data-attribute-name-param="src">
  <a href="page2.html">Page 2s</a>
</turbo-frame>
```

Or, if you wanted to do it for all your turbo-frames, you could just add a global event listener:

```javascript
document.addEventListener('turbo:frame-load', function({ srcElement }) {
  srcElement.removeAttribute('src');
});
```

**Comment by tobyzerner** [comment]
@tleish Thanks, that's a great workaround!

**Comment by seanpdoyle** [comment]
@tobyzerner I recognize that the example you shared is pseudo-code, but in the real scenario, is `<turbo-frame id="page_2">` visible in the viewport when you navigate back?

**Comment by tobyzerner** [comment]
@seanpdoyle Yes that's correct – it's an infinite scroll use case. When you navigate back, the page scroll is restored and so the `page_2` frame is immediately in view, and Turbo reloads it.

The `[disabled]` attribute is a nice workaround too. However, I just note I still think of these as "workarounds" – intuitively I would expect the frame to not be reloaded on restoration, without having to intervene, hence why I didn't close this one just yet. Is there an easy/sensible path to preserving the frame's state across restoration visits by default (perhaps by adding something like a `[loaded]` attribute when the frame has loaded), or is it too much complexity for too little benefit?

**Comment by seanpdoyle** [comment]
@tobyzerner I like `[loaded]` as an attribute name, but it collides with the `FrameElement.loaded` property which exposes a reference to the currently loading `Promise` instance.

Before bike-shedding a name, I'd like to make sure that exposing an attribute is worthwhile. While attempting to resolve another issue, I've implemented a `[loaded]` attribute on a branch on my fork: 

https://github.com/hotwired/turbo/compare/seanpdoyle:frame-loaded-attribute

I think it might resolve some of the issues you're experiencing. Could you try it out?

**Comment by kidlj** [comment]
I'm having the same issue while making an infinite scroll page, just like what @tobyzerner did. So why does turbo-frame with src have to reload after snapshot restoration? Or if it needs to, can we add an attribute to turbo-frame to control this behavior?

I saw the ongoing PR, Since `loaded` is used by another property, how about we add an `error` attribute, when auto loading succeeds it's not set, but when things go wrong(400,401,404,500 etc.) it's set to the status code? Thanks.
