### ISSUE TITLE
Missing distributable script? (from installation docs)

### ISSUE THREAD

**Issue by davidbgk** [hotwired/turbo#43]
> You can download the latest distributable script from the GitHub releases page, then reference that in your <script> tag on your page. — https://turbo.hotwire.dev/handbook/installing (§ In Compiled Form)

I think that script is missing from the build in the released archive from the source code download at https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.1

It would be handy and more accessible to make it available without installing all the tooling (or to change the doc accordingly).

**Comment by davidbgk** [comment]
Or maybe at least provide a link to https://unpkg.com/browse/@hotwired/turbo@7.0.0-beta.1/dist/ if that is the “official” way.

**Comment by sstephenson** [comment]
I agree it would be nice if the docs had a note about getting the distributable files from unpkg. Would you please open an issue or PR over at [@hotwired/turbo-site](https://github.com/hotwired/turbo-site)?
