### ISSUE TITLE
Cache-Control HTTP Header

### ISSUE THREAD

**Issue by dwightwatson** [hotwired/turbo#433]
The Turbo docs indicate that the way to [opt-out of a page cache is to use a `meta` tag](https://turbo.hotwired.dev/handbook/building#opting-out-of-caching), similar to it was done in Turbolinks. [Looking at the code as well](https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/drive/page_snapshot.ts#L39-L41) it looks like only the `meta` tag is considered.

Is there a reason it doesn't look at the `cache-control` header? 

I was hoping that it would work with [Rails' `expires_now` method which sets the `cache-control` header to `no-cache`](https://apidock.com/rails/v6.1.3.1/ActionController/ConditionalGet/expires_now) - it seems like that would be expected behaviour, unless I'm missing something?

**Comment by tleish** [comment]
It's an interesting perspective, however consider the following explanation from the [Turbo Handbook - Navigate with Turbo Drive](https://turbo.hotwired.dev/handbook/building#understanding-caching): 

> Turbo Drive maintains a cache of recently visited pages. This cache serves two purposes: to display pages without accessing the network during restoration visits, and to improve perceived performance by showing temporary previews during application visits.
> 
> When navigating by history (via Restoration Visits), Turbo Drive will restore the page from cache without loading a fresh copy from the network, if possible.
> 
> Otherwise, during standard navigation (via Application Visits), Turbo Drive will immediately restore the page from cache and display it as a preview while simultaneously loading a fresh copy from the network. This gives the illusion of instantaneous page loads for frequently accessed locations.

For Restoration Visits (back/forward buttons) I could see how a developer might want either approach:
- Instruct the browser not to cache this page (`cache-control`) 
- but keep Turbo maintain the cache when navigating the history

or

- Instruct the browser not to cache this page (`cache-control`) 
- and disable Turbo history caching

Same with standard navigation:
- Instruct the browser not to cache this page (`cache-control`) 
- but have Turbo show previews when possible to give the user a perceived experience of speed

or

- Instruct the browser not to cache this page (`cache-control`)
- and disable Turbo previews.

If you wanted to make this the default behavior in you’re application, you could add something like the following to your `application.html.erb`:

```erb
<% turbo_exempts_page_from_cache if response.headers["Cache-Control"] == "no-cache" %>
```

**Comment by collimarco** [comment]
I was also struggling with this bug.

When I added `no_store` to the response I expected it to be respected.
