### ISSUE TITLE
I want to integrate turbo, I am unable to build a single js/ts-file. Errors in npm run build

### ISSUE THREAD

**Issue by SteTomov** [hotwired/turbo#434]
Hey, 
turbo sounds great to be combined with Jinja templates in my context.
I am trying to integrate turbo js into my html files via a <script>-tag. 
After downloading a release from github I get the source code without a built distribution.

So I was reading about npm, installed it, installed dependencies, like tsc.
In order to get a single distributable that is integrateable easily I run "npm run build package.json".
Unfortunately, npm run build throws errors.
So as of now I cant find an option to integrate this package.
Even after adjusting package.json tsc command I am unable to make it build properly. 

![image](https://user-images.githubusercontent.com/78948998/140292158-0fe10a01-a88b-4a85-8f08-423657c71838.png)

Anybody any recommendations on how I can make turbo usable ?

**Comment by dhh** [comment]
You don't need to build it yourself to use it. You can use the distribution files via npm, like https://unpkg.com/@hotwired/turbo.
