### ISSUE TITLE
Form with method post and action to external url is erroneously processed by Turbo

### ISSUE THREAD

**Issue by boboldehampsink** [hotwired/turbo#435]
In my case, a form with method POST and an external action is also processed through Turbo. This shouldn't be happening, according to this?:

> By default, Turbo Drive only loads URLs with the same origin—i.e. the same protocol, domain name, and port—as the current document. A visit to any other URL falls back to a full page load.

**Comment by dhh** [comment]
That notice is just for link following. Not form submissions. You should automatically break out of your Turbo session if the POST results in a redirect that isn't going to the same Turbo-powered app. But if it does go back, then it's a feature not a bug that we stay in the Turbo loop.

That should be documented, though. Feel free to open a PR about that (as well as a pointer to how you can use data-turbo=false to break out).

**Comment by boboldehampsink** [comment]
Hi @dhh, it fails with a CORS error instead of breaking out, like with link following. See screenshot

![image](https://user-images.githubusercontent.com/378974/140385204-b7c1c835-7667-4d40-a9f5-2bd4886e09a6.jpeg)

**Comment by dhh** [comment]
Ah right. Forgot about CORS. Then it seems like we indeed must break out.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/437 to attempt to resolve this.
