### ISSUE TITLE
Different essential css files with data-turbo-track

### ISSUE THREAD

**Issue by joker-777** [hotwired/turbo#440]
Hi, we use different essential css files for different pages which have the `data-turbo-track` attribute to make sure that they trigger a page reload when their content change (they are suffixed with an hash).

```haml
= yield(:essential_css).presence || stylesheet_link_tag("essential.css")
```

The problem is that they now always trigger a page load when I go from one page to another which have different essential files. I get it because turbo doesn't realize if just the hash changed or the whole name changed. What would you recommend here?

**Comment by tleish** [comment]
Options I can think of are trying are:
- Move changing `<link rel="stylesheet" href="mystyle.css">` tags from the head to the top of the body (without `data-turbo-track`).
- Combine essential CSS files into one (unless you are replacing classes because of themes)

**Comment by joker-777** [comment]
Thanks a lot for your response. The idea of these essential files is to have them as small as possible. That's why combining them isn't an option here. Wouldn't be the loading process of the CSS slower if I put them into the body?

**Comment by dhh** [comment]
Turbo can't really help here. It has to reload when the tracked element changes. But if you remove the tracking part, it should just be incremental, as @tleish says.
