### ISSUE TITLE
GET forms targeting turbo farmes do not update the `FrameElement#src` on 7.1.0-rc.1

### ISSUE THREAD

**Issue by agrobbin** [hotwired/turbo#446]
Big fan of Turbo! I was in particular excited for 7.1.0-rc.1, specifically #398, so I tried it out with our app, and it appears there might be a small regression.

We have a `<form method="get" data-turbo-frame="foo" action="/search">`, and when that form is submitted, it's no longer updating the `src` attribute of our `<turbo-frame id="foo">`. The same code was working as expected on 7.0.1.

**Comment by dhh** [comment]
cc @seanpdoyle

**Comment by agrobbin** [comment]
My pleasure @seanpdoyle! It happens regardless of the new `[data-turbo-action]` attribute.

**Comment by seanpdoyle** [comment]
Thank you for clarifying. My hunch is that it's related to the changes in https://github.com/hotwired/turbo/pull/424. I'll investigate.

**Comment by agrobbin** [comment]
No problem! Let me know if I can be helpful in any other way to help nail down this issue!

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/449 to address this issue.
