### ISSUE TITLE
turbo:click and turbo:before-visit event handlers accumulating on document

### ISSUE THREAD

**Issue by afcapel** [hotwired/turbo#453]
This happens when turbo frames are dynamically loaded. 

### Steps to reproduce

Given this html:

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="data:,">
    <script type="module">
      import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
    </script>
  </head>
  <h1>Index</h1>

  <turbo-frame id="frame1" src="frame1.html">
    Replaced content 1
  </turbo-frame>

  <turbo-frame id="frame2" src="frame2.html">
    Replaced content 2
  </turbo-frame>
</html>

<!-- frame1.html -->
<turbo-frame id="frame1">
  <p>Dynamically loaded content 1</p>
</turbo-frame>

<!-- frame2.html -->
<turbo-frame id="frame2">
  <p>Dynamically loaded content 2</p>
</turbo-frame>
```

When you turbo visit the first page, you see a new `turbo:click` and `turbo:before-visit` event handler added to the `document` for each dynamically loaded turbo frame, in each visit. These can grow pretty quickly if you have many frames in your app. Clearing the turbo cache doesn't help.

<img width="595" alt="Screenshot 2021-11-18 at 09 55 10" src="https://user-images.githubusercontent.com/150107/142392874-dcd8ea64-4535-407e-b42d-bb16a04b0d3a.png">

**Comment by seanpdoyle** [comment]
Thank you for uncovering this! I've opened https://github.com/hotwired/turbo/pull/454 to prevent this accumulation.

**Comment by afcapel** [comment]
Awesome, thanks!
