### ISSUE TITLE
Upgrading to 7.1.rc3 doesn't pass parameters outside turboframe

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#465]
Since upgrading from rc2 to rc3, it now strips out parameters from the pagy gem so it won't pass parameters to the server.  It removes the page parameter after clicking on it, and the server doesn't recieve any parameters in the request.

FYI , If I wrap my table inside a <turbo-frame>  it will work fine.

![image](https://user-images.githubusercontent.com/571649/142961999-0d3fec38-6d2b-4d45-a922-9427a4752aa7.png)

**Comment by seanpdoyle** [comment]
I have a hunch at what's at the root of this, but I'm very worried this wasn't uncovered by failures in the test suite.

I'll open a PR to resolve the issue and add more thorough test coverage.

**Comment by acetinick** [comment]
Yea looking at it more, it looks like its doing it for all standard links outside of turbo frames.  

Looking at a few of the tests in the PR looks like most assume submit tags inside a form tag, in ths scenario its just an <a> tag outside of any form/turbo-frame, and no data-turbo-method attribute.

**Comment by seanpdoyle** [comment]
That's a good point, I'll expand that coverage to contain links.

What worries and surprises me is that the _rest_ of the suit passed with broken behavior in such an integral feature.

**Comment by Intrepidd** [comment]
I have a similar issue where I have a page with links to itself with query params and clicking on those links don't change the page content anymore with RC3

**Comment by tortuetorche** [comment]
Hi folks,

I've also some issues when opting out cache (`<meta name="turbo-cache-control" content="no-cache">`).
When I go to previous pages with back and forward buttons of my Web browser (Firefox or Chromium).

Have a good day,
Tortue Torche

**Comment by seanpdoyle** [comment]
@acetinick @Intrepidd I've opened https://github.com/hotwired/turbo/pull/466 to try and resolve the searchParams issue.

@tortuetorche what you're describing sounds unrelated to the original issue outlined here. Could you open a new Issue?

**Comment by dhh** [comment]
@acetinick @Intrepidd Lemme know when you've had a chance to test #466. Would like to move to a 7.1.0 final, if this is the last blocker!

**Comment by Intrepidd** [comment]
@dhh works for me on `main` when it didn't on 7.1.rc3 :) Thanks @seanpdoyle
