### ISSUE TITLE
changing turbo frame src manually doesn't update main url

### ISSUE THREAD

**Issue by alexgerber** [hotwired/turbo#468]
Hi, is this a bug or something intentionally left out? On latest turbo release.

When using a turbo frame with the new data-turbo-action="advance" directive ie:
```
<turbo-frame data-turbo-action="advance" data-search-target="frame">
  <a href="/articles?page=2" rel="next">Next page</a>
</turbo-frame>

```
When manually selecting the turbo frame and changing the src in stimulus controller
ie `frameTarget.src = '/'` it only changes the src of the frame, not url.

It would be nice to be able to change the src programmatically and have it sync with the main url as well, like normal link clicks. Thanks, let me know what you think, or if I missed something.

**Comment by seanpdoyle** [comment]
This is a current limitation that is likely to stick around in `7.1.0`. 

In cases where you need to promote a Frame Visit to a Page Visit programmatically (like in a Stimulus Controller), you could synthesize an `<a>` element, declare the desired `frameTarget.src` as the `<a href="...">`, set `[data-turbo-action]` on the element, then click it.

```js
function promoteToFrameVisit(element /*: FrameElement */, src /*: string */, action = "advance") {
  const link = document.createElement("a")
  link.setAttribute("href", src)
  link.setAttribute("data-turbo-action", action) // you can skip this is the <turbo-frame> already declares [data-turbo-action]
  link.setAttribute("hidden", "")
  element.appendChild(link)
  link.click()
  element.removeChild(link)
}

promoteToFrameVisit(this.frameTarget, "/", "replace")
```

Alternatively, the `<turbo-frame>` could have a descendant `<a hidden>` element that the controller clicks.

To share a little extra context, the current internal structure Turbo Frames portion of the codebase makes it challenging to retain contextual information throughout a Frame navigation.

For example, once an `<a>` element is clicked, a `<form>` element is submitted (often times with `<button>` or `<input type="submit">` submitter), or a `<turbo-frame>` element's `[src]` attribute is changed programmatically, the methods that respond to that action cannot access the original elements' `[data-*]` attributes. This is a problem when trying to infer additional information. All that's available is the value of the `[src]`.

There are efforts in-progress to refactor and restructure the Turbo internals , but they're unlikely to ship until a stable `7.1.0` has been released.
