### ISSUE TITLE
Make seperate polyfill packages

### ISSUE THREAD

**Issue by ParamagicDev** [hotwired/turbo#469]
Is there any interest in moving the requestSubmit and event.submitter polyfills into seperate packages so other libraries can make use of it? Mrujs uses it and it would be great to be able to synchronize off of Turbo's polyfills.

**Comment by dhh** [comment]
The requestSubmit polyfill is already a separate package, but not interested in making Turbo itself depend on anything external, if we can at all avoid it.

https://github.com/javan/form-request-submit-polyfill
