### ISSUE TITLE
Event listeners lost on data-turbo-permanent after navigation

### ISSUE THREAD

**Issue by alexander-schranz** [hotwired/turbo#470]
I have a element which is market as `data-turbo-permanent` (navigation). Inside this element event listeners are added to various elements of the DOM. After navigate into to another page with turbo all the event listener are gone. The eventlisteners are registered over on the elements using `addEventlistener`. How can I prevent that turbo is doing anything with the elements inside this container?

**Comment by alexander-schranz** [comment]
Got another problem it seems registering the stimilus component multiple times when using turbo permanent: #471

**Comment by seanpdoyle** [comment]
@alexander-schranz was this closed unintentionally?

**Comment by alexander-schranz** [comment]
@seanpdoyle Thx for the response. I close intentionally as I interpreted the issue wrongly and thought a new issue describing the new problem would be better then editing the whole description and title of this issue. Thx for your answer 🙏 here and in the other issue.
