### ISSUE TITLE
Stimilus component inside data-turbo-permanent are reinitialized

### ISSUE THREAD

**Issue by alexander-schranz** [hotwired/turbo#471]
I have a container with `data-turbo-permanent` on it.

Inside this container there are multiple stimilus components which are registering multiple `addEventlisteners`. After I navigate the stimilus component is being registered again instead of ignored so the method is now called multiple times.

Example:

```html
<div id="main-navigation" data-turbo-permanent">
     <div data-controller="toggler-container"
         <button data-toggle-container-target="button">
             Some Button
         </button>
     </div>
</div>
```

The js code will over some code then bind a click element with `addEventListener`

```js
connect () {
    // some code which will at the end do `button.addEventListener('click', someMethod)`
}
```

This someMethod will now be called multiple times after every navigate additional addEventListener is being registered.

**Comment by tortuetorche** [comment]
Hi @alexander-schranz,

Which version of Turbo are you using?

**Comment by seanpdoyle** [comment]
During a page or frame navigation, permanent elements are disconnected from the original document, then connected to the new document. Throughout that process, Stimulus lifecycle hooks (`[name]TargetDisconnected()`, `disconnect(),  `[name]TargetConnected()`, `connect()`) will fire for controllers on the permanent element or any of its descendants.

The `Element` that's transplanted across elements will be the same instance throughout. 

The [Persisting Elements Across Page Loads](https://turbo.hotwired.dev/handbook/building#persisting-elements-across-page-loads) section of the Turbo Handbook describes the process:

> Before each render, Turbo Drive matches all permanent elements by ID and transfers them from the original page to the new page, **preserving their data and event listeners**.

In the case of Turbo + Stimulus, connecting event listeners without also disconnecting them can lead to accumulating extra listeners. Listeners added through `[data-action]` event routing declarations will be managed automatically, but any `addEventListener` call made within a controller should have a matching `removeEventListener` declared in a `disconnect()` or `[name]TargetDisconnected()` hook.

Am I understanding this issue correctly, or is there something else going on?

**Comment by alexander-schranz** [comment]
Thank you for your fast responses.

@tortuetorche The 7.0.1 is used here.

@seanpdoyle You interpreted the issue correctly and the hint that permanent elements are `disconnected` and `connected` again is cause of my issue. Thank you!

A additonal question can I move the addEventListener to the `initialize` method or is initialize the false place todo this?

**Comment by alexander-schranz** [comment]
Replacing `connect` with `initialize` did fix my issue. Thx for the fast support 👍
