### ISSUE TITLE
Turbo is ignored on any navigation that uses a dot in the URL

### ISSUE THREAD

**Issue by andrewjtait** [hotwired/turbo#480]
As of v7.1.0 form submissions do not use Turbo if the route includes a dot within its dynamic segment (https://guides.rubyonrails.org/routing.html#dynamic-segments)

For example, a form executing a POST to `/domains/example.com`

It looks as though the bug has been introduced as part of https://github.com/hotwired/turbo/pull/437, which introduces an additional check for `locationIsVisitable` in this code:

https://github.com/hotwired/turbo/blob/aa9724dd23309a56b3e7c6ee62c673fa63799038/src/core/session.ts#L202-L208

which is defined here:

https://github.com/hotwired/turbo/blob/18c93e9bfab790f65b447871f183b454c2ec1f2a/src/core/url.ts#L35-L37

and checks the extension on the URL: https://github.com/hotwired/turbo/blob/18c93e9bfab790f65b447871f183b454c2ec1f2a/src/core/url.ts#L26-L28

**Comment by andrewjtait** [comment]
Actually, it seems like this is an issue on any navigation to a URL using a dot, not just form submissions.

**Comment by tleish** [comment]
@andrewjtait — see https://github.com/hotwired/turbo/issues/385 discussion

**Comment by andrewjtait** [comment]
@tleish ah, perfect - thanks!
