### ISSUE TITLE
data-turbo-action="advance" doesn't update browser URL

### ISSUE THREAD

**Issue by wonderix** [hotwired/turbo#489]
The [documentation](https://turbo.hotwired.dev/handbook/frames#promoting-a-frame-navigation-to-a-page-visit) says that the browser URL will be updated if `data-turbo-action="advance"` is set on a link or a turbo frame.
Unfortunately, only the `src` attribute of the turbo frame is updated.
When using `Turbo.visit()`, the `src` attribute and the browser url are updated.

I'm using version 7.0.1.

Is this related to #468?

**Comment by luglio7** [comment]
when i manually update the src attribute of a frame with "data-turbo-action" set to "advance" the url doesn't change. I'm missing something ? When i click a link inside a frame everything is working as expected.

**Comment by timburgan** [comment]
I cannot get this to work either when I set `<turbo-frame data-turbo-action="advance">`. The URL just does not update. It only works if I set that data attribute on all the link `<a>` elements within the frame.

I'm using the `turbo-rails` gem (version 1.0.1) which I can see is already using v7.1 of turbo. 🤷  https://github.com/hotwired/turbo-rails/compare/v1.0.0...v1.0.1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L16

**Comment by leoplct** [comment]
I see the using` data-turbo-action="advance" `it does update the URL but if `controller_name` and `action_name` helpers still return the old controller. Even if the URL is updated and the view rendered.
How can I get the controller_name/action_name of the rendered controller inside a turbo_frame_tag?

**Comment by walterhorstman** [comment]
Are we sure this is working? I'm creating a fresh Rails 7 application, have included `stimulus-rails` and `turbo-rails` in `Gemfile` and `package.json` contains `"@hotwired/turbo-rails": "latest"` under `"dependencies"`. `yarn.lock` indicates I'm using 7.1.3 of `@hotwired/turbo`.

My view contains `<turbo-frame data-turbo-action="advance" id="header" target="main"><a href="..."></a></turbo-frame>` and further a `<turbo-frame id="main"></turbo-frame>`. I would expect the page's URL to change when clicking the link.

**Comment by dmitrue** [comment]
Same for me, I'm using `"@hotwired/turbo-rails": "^7.3.0",` and `Turbo.visit('/...', { frame: 'results', action: 'advance' })` doesn't update URL of the page

**Comment by perlun** [comment]
For me, with Turbo 7.1.0, I see that it's _working_ when navigating to other content within a turbo frame. When trying to combine it with `target="content"` (similar to in your example @walterhorstman), it refuses to update the URL. :thinking: 

I'll try updating to 7.3.0 to see if I can reproduce it there as well.

**Comment by perlun** [comment]
@seanpdoyle - this is of course a bit premature, but it _feels_ like this could be a limitation in the initial implementation in #398. :thinking: Would you like an isolated test case or could you give it a look regardless?

To make things reasonably clear, we're talking about scenarios like this:

```html
<body>
  <turbo-frame id="nav" target="content" data-turbo-action="advance">
    <!-- Links inside this frame are broken; the data-turbo-action properly is not properly honored -->
    <a href="/link-one">Link one</a>
    <a href="/link-two">Link two</a>
  </turbo-frame>

  <turbo-frame id="content" data-turbo-action="advance">
    <!-- Links inside this frame works correctly re. URL/history, with the limitations described in earlier comment -->
    <a href="/link-three">Link three</a>
  </turbo-frame>
</body>
```

**Comment by bopm** [comment]
After debugging it, I am seeing that `this.action` [here](https://github.com/hotwired/turbo/blame/4593d06ce58d17af5b17495ad8524eaa9bc2f5d2/src/core/frames/frame_controller.ts#L409) is null no matter Turbo.visit configuration.

**Comment by bopm** [comment]
I suspect this issue was introduced [here](https://github.com/hotwired/turbo/commit/52c4974f5c61f816378a92705922548729b93410#diff-4fdcafb26950e01d47ac3215a38de2bbb3d4788ca980214293f334cfec78a7c0L110-R117), as before this change `options` were taken into account, but not any longer after that change. And `Turbo.visit` lands here. 
cc @seanpdoyle

**Comment by louiswdavis** [comment]
As a workaround, I added a target to my html that when connected passes data attributes for the page name and path I want to set

```
 <div data-modal-target="overwriteUrl" data-page="Page Name" data-path="/appended_path"></div>
```

```
overwriteUrlTargetConnected(target) {
  window.history.pushState(null, target.dataset.page, target.dataset.path)
}
```

**Comment by merrynhr** [comment]
> As a workaround, I added a controller to my rendered html that when connected passes values for the page name and path I want to set
> 
> ```
>  <div data-controller="url" data-url-page-value="Page Name" data-url-path-value="/appended_path"></div>
> ```
> 
> ```
> export default class extends Controller {
>   static values = {
>     page: String,
>     path: String,
>   }
> 
>   connect() {
>     window.history.pushState(null, this.pageValue, this.pathValue)
>   }
> }
> ```

Used this and added the following so the back button would work: 

  disconnect() {
    window.history.popState()
  }

**Comment by bopm** [comment]
@dhh @seanpdoyle this issue is regressed since 7.3.0, can we get this issue back open?

**Comment by leonvogt** [comment]
> I'd expect the following to update my URL but it doesn't :(
Turbo.visit(url, { frame: 'a', action: 'advance' })

Same. Would be really nice if that worked.

**Comment by jasonswett** [comment]
I had this issue and upgrading to Rails 7.1.3 and Turbo 1.5 seemed to fix it for me. (I don't know which upgrade was responsible for the fix.)

**Comment by seanpdoyle** [comment]
> May or not be related, but I'm experiencing a similar issue even without manually setting `action: 'advance'`:
> 
> ```js
>     Turbo.visit(url, {
>       frame: 'my-frame',
>     });
> ```
> 
> Updates the `src` attribute on the frame but does not update the URL. `"@hotwired/turbo": "^7.3.0"`

I've opened https://github.com/hotwired/turbo/pull/1135 to resolve this issue.

**Comment by seanpdoyle** [comment]
> @seanpdoyle - this is of course a bit premature, but it _feels_ like this could be a limitation in the initial implementation in #398. 🤔 Would you like an isolated test case or could you give it a look regardless?
> 
> To make things reasonably clear, we're talking about scenarios like this:
> 
> ```
> <body>
>   <turbo-frame id="nav" target="content" data-turbo-action="advance">
>     
>     <a href="/link-one">Link one</a>
>     <a href="/link-two">Link two</a>
>   </turbo-frame>
> 
>   <turbo-frame id="content" data-turbo-action="advance">
>     
>     <a href="/link-three">Link three</a>
>   </turbo-frame>
> </body>
> ```

I've added test coverage to https://github.com/hotwired/turbo/pull/1135 to attempt to resolve this issue. Unfortunately, I was able to pass the test without any implementation changes. Could you review that diff (mainly https://github.com/hotwired/turbo/pull/1135/files#diff-1e84a1526802b27615a24efc0f9b75c27b2a9197d855a8ccc5475db14609ed6f and https://github.com/hotwired/turbo/pull/1135/files#diff-4706705ec52e666c36d3cd9410d3aad96354c69f61a18f880b40291836485f36R655-R663 to help me reproduce the underlying issue more closely?
