### ISSUE TITLE
Kaminari page lost when submitting form

### ISSUE THREAD

**Issue by alhafoudh** [hotwired/turbo#494]
I have a paginated list of orders. Each order can be completed by link next to each order like this:

```
link_to 'Complete', complete_order_path(order), data: { turbo: true, turbo_method: :patch }
```

The order is updated in controller like this:

```
...
  def complete
    @order = Order.find(params[:id])

    @order.completed_at = Time.zone.now
    @order.save!

    redirect_back fallback_location: orders_url, status: :see_other
  end
...
```

When I navigate to some page of orders, the params change to for example `/orders?page=3`. After clicking the "Complete" link the turbo-frame updates, but I get first page of orders rendered, because the turbo-frame loses params of the page and the `Referer` header is the original `_top` page URL.

How can I fix this in turbo?

**Comment by pinzonjulian** [comment]
Hey @alhafoudh !

Usually the Github issue tracker is used to report issues and bugs with the library as opposed to asking for help on specific implementation details of your app. 

I recommend you post this question in the official hotwired forum at http://discuss.hotwired.dev or maybe join the StimulusReflex discourse here https://discord.gg/stimulus-reflex. 


If after discussing there you realise you might have found a bug in Turbo, by all means, create an issue.

**Comment by pinzonjulian** [comment]
Tag me in any of those places and I'll give you a hand.

**Comment by brunoprietog** [comment]
Do you think you can close this? We can see it in the discussions forum

**Comment by alhafoudh** [comment]
Yes, sure. Thanks @brunoprietog
