### ISSUE TITLE
disable scroll to top on navigating with data-turbo-scroll="false"

### ISSUE THREAD

**Issue by eladmarg** [hotwired/turbo#496]
this is not a must, but every link trigger the page to top (as normal web behavior - this is expected, so far so good).

however, there are some cases we wouldn't want to scroll top, for instance, when you're filtering multi facets,
the url is changing, new data has arrived and now you have to scroll down again to the previous position

this is really easy to add this, (did this on my repo) , if this is acceptable, i will submit a pr.
thanks

**Comment by markahesketh** [comment]
Would you be able to share your repo? I'm also looking for a solution to this.

In my case, I have a list of basket lines - and when removing one the page scrolls back to the top losing your position.

It works if the basket is put inside a turbo frame - however then other areas of the UI do not update, such as the basket count in the header.

**Comment by mtomov** [comment]
I'd also second the need for this, even if it's just a guide on how to achieve it.

@eladmarg do you mind sharing your solution?

**Comment by janbaykara** [comment]
My usecase is that I'm using a link to toggle an option on a page, which updates a URL parameter, and I want the page scroll position to stay the same.

**Comment by nxmndr** [comment]
#37 duplicate
