### ISSUE TITLE
No one knows how to wait for scripts to load

### ISSUE THREAD

**Issue by janat08** [hotwired/turbo#498]
I did a search, and if you're using just the javascript you'll see a bunch of questions on forums without an answer for how to substitute load event on window. My specific use case that I want to render paypal buttons, I put initialization script with every turbo event of which none wait for paypal sdk to download.

**Comment by adityagadekar1988** [comment]
I had same issue. Just added below line to application.html.erb:
`<meta name="turbo-visit-control" content="reload">`

**Comment by janat08** [comment]
Fair enough, I wish I read the docs.
