### ISSUE TITLE
Redirect to new page after form submission

### ISSUE THREAD

**Issue by DalenW** [hotwired/turbo#502]
I know it's been asked before, but I'm losing my mind trying to get this to work. I feel like I've tried every possible solution.

This is on a brand new rails 7 app with the default installation of Hotwired with import maps left in place.

The official documentation states that redirects should be handled by a status code of 303. If I respond with this, it doesn't redirect. It will try to load the page expecting a turbo-frame, which of course fails because there doesn't need to be one on the page I'm trying to load. No matter what I try it will always expect that turbo-frame.

The only way I got close to getting it to work with turbo is by adding a turbo-frame on the redirected page, but this doesn't work for two reasons: 1. The URL doesn't update. 2. The form is a new product, and the next page is simply showing product details, so I  can't retain the same turbo-frame ID without naming it something generic like "product" which is bad practice based on the other examples I've seen.

Here's my controller action:
```ruby
def create
  safe_params = params.require(:create).permit(:name, :sku, :price, :quantity, :tax_code)

  @product = Product.new safe_params
  @product.market = @current_market

  if @product.invalid?
    return respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  @product.save

  # redirect_to app_product_path(@product.id, format: :html), status: :see_other

  respond_to do |format|
    format.html { redirect_to app_product_path(@product.id, format: :html), status: :see_other }
    format.turbo_stream
  end
end
```
I've tried multiple variations of the redirect and response_to methods, same result each time.

And the new form is contained in the following html:
```erb
<%= turbo_frame_tag 'create_product' do %>

<% end %>
```
I've tried the other suggestions of using stimulus to hack the correct redirect in, but that doesn't seem to work either. That solution is mentioned here: https://github.com/hotwired/turbo/issues/138#issuecomment-802171574

I feel like I'm missing something super obvious but right now after spending hours on this and close to a headache, I don't know what else I could try.

**Comment by dhh** [comment]
Do you mean to use a turbo frame? That's only if you want to contain the interaction to a subset of the page. And when you use turbo frames, all responses have to contain a turbo frame too.

Either way, please use discuss.hotwired.dev for further usage assistance ✌️

**Comment by DalenW** [comment]
Sorry I know it's closed but quick follow up question. 

I'm pretty sure I should use a turbo frame in this case because I want to display errors if the form validation fails without reloading the page. That is the ideal case for turbo frames right?

**Comment by tonysm** [comment]
hey @DalenW not sure if I understood it correctly, but looks like you're wrapping the form inside a Turbo Frame and want it to render invalid messages inside the frame but let the whole page follow the redirect in case everything goes right.

You could achieve that by having a `target="_top"` in the form Turbo Frame. So, responding with a 422 status code would just replace the form, but successful redirects will replace the entire page, not just the Frame. See [here](https://turbo.hotwired.dev/handbook/frames#targeting-navigation-into-or-out-of-a-frame) and [here](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission).

There is also a way to "promote" frame visits to page visits, but not sure if that's what you're looking for (see [here](https://turbo.hotwired.dev/handbook/frames#promoting-a-frame-navigation-to-a-page-visit)).

**Comment by DalenW** [comment]
Yeah that's what I am trying to do. 

I think that would work, thanks!

**Comment by glaszig** [comment]
@DalenW i'm in the same boat. did you manage to figure this out?
