### ISSUE TITLE
[Feature Request] Let's use much faster mousedown instead click event

### ISSUE THREAD

**Issue by priit** [hotwired/turbo#504]
Currently link elements are observed by click event but it's old wisdom to use mousedown event to make user interface actions 2x faster for end users. We have been observing mousdown events to trigger actions over 10 years without big issues. 

With quick Turbo source code study, it seems probably using mousedown event for links observing in Turbo Frames looks safe.

Before digging deep in with a batch/pull request, does anyone have any showstopper argument not using mousdown observing for link element?

**Comment by panoply** [comment]
I have actually tested this quite thoroughly and there is only a minor performance benefit to leveraging mousedown but there is a benefit nonetheless. In addition, reaching for pointer events for browsers that support this and triggering a fetch accordingly is the best way to handle it. Some other aspects that can drastically improve navigations are pre-fetching on hover but such can be a little difficult to wrangle in some environments. 

I have project that is very much inspired by  Turbo. Sort of like a variation (of sorts) that actually does this just that, ie: triggers fetches on mousedown/prefetches upon hover while maintaining a snapshot cache and for my use cases leveraging mousedown did in fact improve navigation speed. Hover pre-fetches pretty much resulted in instantaneous navigation.

**Comment by tleish** [comment]
I've seen issues with mousedown/touchstart events on links/buttons in mobile browsers.  Especially when attempting to touch and scroll the page when the touch starts on a link/button target.

**Comment by dhh** [comment]
Would be happy to see prefetching on hover explored in a PR 👍
