### ISSUE TITLE
Create an interactive hello world example

### ISSUE THREAD

**Issue by synox** [hotwired/turbo#51]
I had trouble running it as plain html with the CDN. 

I could not find a releases github page with plain JS (not Typescript), and the CDNpack only seems to work with   `<script type="module">        import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';</script>` 

After a stable release, it would be great to have some basic examples to see it in action, e.g. on codepen.

**Comment by delitescere** [comment]
Try:
```
    <script type="module" src="https://cdn.skypack.dev/pin/@hotwired/turbo@v7.0.0-beta.1-tPCW1AHTtVGOe5r89LWv/min/@hotwired/turbo.js"></script>
```

**Comment by orefalo** [comment]
Agreed, while I am big fan of the KISS principles, maybe a few sample examples would have been recommended before posting the news about this mighty tool set around the world.

**Comment by delitescere** [comment]
If you're a JVM user: https://github.com/delitescere/hotwire-samples
