### ISSUE TITLE
Double fetch requests for eager-loaded frames

### ISSUE THREAD

**Issue by blrB** [hotwired/turbo#515]
I think I found a bug.

Steps to reproduce:
1) Create page with eager-loaded frame
2) Create link with redirect on this page (HTTP code not important)
3) Click on link for get redirect
4) Watch browser network tab (or sever logs)

Example requests for turbo_frame with id: src_content:
Chrome:
![chrome_duplicate_requests](https://user-images.githubusercontent.com/9513452/150327039-5d657010-f0f9-4bb4-9980-bd5d5054f9b2.png)
Firefox:
![ff_duplicate_requests](https://user-images.githubusercontent.com/9513452/150327045-c3feb0f0-089a-494d-987e-eafe669766a3.png)

All my 'eager-loaded frames' were loaded twice. You can look part of my source code for ruby 3.1.0, rails 7.0.1, turbo-rails 1.0.1 here: https://gist.github.com/blrB/1b0e1d44f31df1d1c9932985471ec3b3

I think, that root case can be in line https://github.com/hotwired/turbo/blame/main/src/core/drive/visit.ts#L274 (commit https://github.com/hotwired/turbo/commit/38b8f138c1e872e8ef2ddf2da32a74916caec305). Now redirect responses use visit action `replace`. This visit create next trace `start` -> ... -> `loadResponse` -> `render` -> ... -> `replaceBody` -> `sourceURLChanged` -> `loadSourceURL` -> fetch request for frame. But fetch request already was created and rendered, before `replace` action had been created. I think we shouldn't render this action twice, so we can just create this action with prams `willRender: false`. I tested this code, and I think it works like I expected. You can look source code here:  #516

**Comment by john-kelly** [comment]
I’m running into this as I’m upgrading from turbolinks.

As a question for the maintainers of the project, is this intended/expected behavior? I imagine others have run into this and I couldn’t find any official statements or documentation regarding this behavior. 

My rough understanding is that things changed once turbo started using fetch - and therefore could handle redirects.


Thanks so much for documenting this issue @blrB. And thank you to the turbo maintainers.

**Comment by dhh** [comment]
Going off memory here, I think the issue is that the snapshot that's showed first before the page is fetched again triggers the frame loading. Thus you end up with the double loads. If that's still the case, then it seems like we need to figure out how to make the snapshots permanent with the frames all loaded. I think maybe @seanpdoyle have had a look at this in the past?

**Comment by seanpdoyle** [comment]
I believe a change like the one made in https://github.com/hotwired/turbo/pull/487 might help resolve this issue. It proposes a `[loaded]` attribute (there are [some additional considerations](https://github.com/hotwired/turbo/pull/487#issuecomment-984160738) regarding the name), which would expose a frame's load state in a cache-friendly way.

**Comment by blrB** [comment]
Hello. I try use turbo-rails (1.3.1), but this issue still presents. I can't understand how #614 resolve this issue. I see that frame has  `complete` attribute, but it is still make two fetch request. 

@seanpdoyle, could you please help me with this?

![image](https://user-images.githubusercontent.com/9513452/196621850-b2bae738-0174-4d46-921d-9b9efd075c2b.png)
![image](https://user-images.githubusercontent.com/9513452/196621965-68842e8f-732c-48a4-ac25-eec6338c5bd8.png)

**Comment by blrB** [comment]
Also this issue can be reproducet in test fixtures page (http://localhost:9000/src/tests/fixtures/frames.html), after click link ["Eager-loaded frame after GET redirect"](http://localhost:9000/__turbo/redirect?path=/src/tests/fixtures/page_with_eager_frame.html):

![turbo](https://user-images.githubusercontent.com/9513452/197216528-f6688727-3b8a-436c-8c60-f75edf93f126.png)

Unfortunately, the written tests did not fail during the regression run(

**Comment by seanpdoyle** [comment]
@blrB thank you for continuing to pull on this thread.

> Unfortunately, the written tests did not fail during the regression run

If cut a branch that resolves the broken assertion issues, and causes the test you wrote to fail:

https://github.com/hotwired/turbo/compare/seanpdoyle:frame-test-broken-assertion

@dhh could you re-open this issue?

**Comment by blrB** [comment]
@seanpdoyle thank you for response

> are you interested in continuing to experiment with a solution?

Yes, I try to check your alternative option described in 256418fee0178ee483d82cd9bb579bd5df5a151f on next week.

**Comment by blrB** [comment]
https://github.com/hotwired/turbo/pull/779#issuecomment-1417747571

Issue doesn't reproduce on the main branch.
