### ISSUE TITLE
Manually push history with action advance

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#518]
I have a situation where I would like to push a history item when I open modal window using a stimulus controller. I have this so far from looking at the code to try push history

`window.Turbo.navigator.history.push(new URL(url))`

This works good for replacing the URL and adding history state to the browser, however when you click the back button in the browser it replaces with the old URL but doesn't visit it. I would also like the back button to work similar to the way we can use data: { turbo_action: "advance" } on a regular <a> tag.  I know this is based on the work that @seanpdoyle worked on,  is there perhaps a way to manually push history and make it still work with back button ?

**Comment by jaryl** [comment]
Try pushing with the current state:

```
history.pushState(history.state, "", new URL(url));
```

**Comment by pySilver** [comment]
I've opened a separate issue for that #792
