### ISSUE TITLE
Turbo frame loads twice when it is in the response of a redirected request

### ISSUE THREAD

**Issue by karthikkasturitg** [hotwired/turbo#526]
Using turbo-rails with turbo-frame :

Assuming there is a page with an anchor that links to "/page" and the /page action redirects to "/main" where we have a response of .html.erb as such: Frame here: <turbo-frame id="data" src="/test/frame"></turbo-frame>

Expected behavior: On clicking the link to /page, main.html.erb should be loaded and since the response has a turbo frame, "/test/frame" should be called once to load the data for the frame

Actual behavior: "/test/frame" is called twice.

Can be replicated on: https://github.com/karthikkasturi/turbo-frame-loads-twice-on-redirect

**Comment by dhh** [comment]
Solved via https://github.com/hotwired/turbo/pull/516
