### ISSUE TITLE
Allow data-href to be used with data-turbo-method

### ISSUE THREAD

**Issue by zmitic** [hotwired/turbo#528]
``data-turbo-method`` is a **great** way to create POST/PUT/DELETE actions but by directly reading ``href``, users can still open them in new tab. And that tab would result in in 405 (method now allowed) which is not very user-friendly.

#### Feature request:

allow something like this: 

```html
<a data-turbo-action="/my-url" data-turbo-method="post">Start processing</a>
```

The order of finding ``action`` for hidden form:

- data-turbo-action
- href
- "undefined"

From my **basic** understanding of JS, feature should be[ easy to add](https://github.com/hotwired/turbo/pull/277/files#diff-3820e6277ecf2eb3f16cbb74c82e6c21c6c8580a7265694c4459cfa63110add4R61):

```ts
form.action = link.getAttribute("data-turbo-action") || link.getAttribute("href") || "undefined"
```

**Comment by seanpdoyle** [comment]
An `<a>` without an `[href]` attribute has no [activation behavior](https://dom.spec.whatwg.org/#eventtarget-activation-behavior).

Have you considered using a `<form>` and `<button>` pairing?

```html
<form action="/my-url" method="post">
  <button>Start processing</button>
</form>
```

**Comment by zmitic** [comment]
The example w/o href was for readability, I would have probably put ``href="#"``. Or maybe an URL to page that specifically says ``You can't do it``, or even better, put a link to general 404 page.



> Have you considered 


I did, but I find single ``<a>`` element much easier to use when I have a table with multiple actions per row.

**Comment by zmitic** [comment]
In this case, it is just a lots of buttons in a table, within protected ```/admin``` pages where google will never be:



![image](https://user-images.githubusercontent.com/1964158/153521615-37fad8b7-f849-4f0d-ba08-ddf50100c19d.png)

Every link inside **extractors** and **actions** columns are these buttons; very easy to set them in HTML and accessibility is not an issue (just one admin).  ```<a>``` elements are easier to customize than buttons and javascript is not an issue due to ```<noscript>``` and the fact admin will never turn it off . 

---

But this idea is breaking too many HTML rules, feel free to close the issue. I am happy with Turbo even w/o this.
