### ISSUE TITLE
turbo:load event not triggered

### ISSUE THREAD

**Issue by jsmirn** [hotwired/turbo#530]
After a vanilla turbo visit, the turbo:load event is not triggered. Also :render, :frame-render, :frame-load don't work. However, turbo:before-fetch-response does work.
To reproduce: 

document.addEventListener("turbo:load", () => console.log('turbo:load'));

Console message is displayed upon initial page load, but not after subsequent TURBO_STREAM visits.

**Comment by adityagadekar1988** [comment]
I had the same issue. Just added below line to application.html.erb
<meta name="turbo-visit-control" content="reload">

**Comment by jsmirn** [comment]
I added that line to the header, but it didn't change the issue.
