### ISSUE TITLE
Small mistake in Turbo Streams introduction section of handbook

### ISSUE THREAD

**Issue by tvanderpol** [hotwired/turbo#532]
In the first code example of [the Turbo Streams introduction](https://turbo.hotwired.dev/handbook/introduction#turbo-streams%3A-deliver-live-page-changes) I'm pretty sure the content in the `<template>` tag is wrong? This is what's there right now:

```html
<turbo-stream action="append" target="messages">
  <template>
    <div id="message_1">My new message!</div>
  </template>
</turbo-stream>
```

I'd expect there to be a container element like a div with an id of 'messages' to append into.

**Comment by marcelolx** [comment]
@tvanderpol Not it isn't because the `turbo-stream` tag is telling to which element Turbo should append the content of the `template` tag.
