### ISSUE TITLE
Incorrect documentation about data-turbo="false"

### ISSUE THREAD

**Issue by iFreilicht** [hotwired/turbo#542]
I tried to put `data-turbo="false` on a form to stop turbo from navigating and rendering the response [like the docs say](https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms), but what actually did the trick was `data-turbo-drive="false"`.

Is this a case of outdated documentation or did I do something wrong? I'm not using any other JS libraries, my server-side framework is written in python using flask.

**Comment by tleish** [comment]
The documentation is correct.  The current version uses `data-turbo="false"`. 

code: https://github.com/hotwired/turbo/blob/main/src/core/session.ts#L323-L342
tests: https://github.com/hotwired/turbo/blob/main/src/tests/functional/form_submission_tests.ts#L621-L635
test fixtures: https://github.com/hotwired/turbo/blob/main/src/tests/fixtures/form.html#L145-L155

I also just tested this manually to confirm.

**Comment by jacobdaddario** [comment]
I think that this issue is probably fine to close given the response, unless @iFreilicht can document a method of reproducing the issue with getting `data-turbo=“false”` to work on the current version of Turbo.

@cc @dhh

**Comment by iFreilicht** [comment]
Yeah you can close it. I checked which version I'm using and it is 7.1.0, so I have no idea why data-turbo won't work for me, but I also can't reproduce it on another page I'm using turbo on. Maybe I'm misunderstanding something? Either way, with data-turbo-drive, it works on that particular page, so I'm alright.

23 Mar 2022 00:52:05 Jacob Daddario ***@***.***>:

**Comment by jacobdaddario** [comment]
I’m glad to hear that it’s working now!
