### ISSUE TITLE
Add a turbo:after-stream-render event

### ISSUE THREAD

**Issue by mpiot** [hotwired/turbo#548]
What about add a `turbo:after-stream-render` event ? Or maybe a `detail` part with the stream and infos about it.

Actually I try to do something on the updated part of the page by `streams`, but there is no event about that, I've just find a `turbo:before-stream-render`. I've try to pass by `turbo:before-fetch-response` then use the detail to wait response, but the stream is not yet triggered.

Maybe I miss a way to do that ? The goal is to applys something on the part updated by the stream.

**Comment by jacobdaddario** [comment]
It doesn't look like there's a first party solution to this right now. Like you said, according to the handbook there isn't an event to hook into a Turbo Stream after it loads.

Off the top of my head, I imagine you could try to hook into this behavior by assigning a Stimulus controller to the stream with a `connect` function that executes the behavior that you're looking for.

**Comment by adrienpoly** [comment]
This was discuss here https://github.com/hotwired/turbo/issues/92. As mentioned above, a connect method in a Stimulus controller is the way to go.

**Comment by jacobdaddario** [comment]
Sweet! I guess this issue is good to get closed up then.

Cc: @dhh

**Comment by mpiot** [comment]
It's okay for me, I'll do that with Stimulus :)

**Comment by woto** [comment]
It helped me https://github.com/hotwired/turbo/pull/20#issue-773325276. Didn't found any drawbacks yet.

**Comment by artur79** [comment]
you can also use this instead connect() https://turbo.hotwired.dev/handbook/streams#custom-actions I'v added boostrap5 popover that way. I had to do this before my controller is not "higher" than turbo frame and I didn't want to add extra controller just for this.

```
    addEventListener('turbo:before-stream-render', (( event) => {
      const fallbackToDefaultActions = event.detail.render

      const that = this

      event.detail.render = function (streamElement) {
        that.renderPopovers()
        fallbackToDefaultActions(streamElement)
      }
```

**Comment by AdrienGiboire** [comment]
Do you confirm there is no other but Stimulus? What about people that don't use it?

**Comment by artur79** [comment]
> Do you confirm there is no other but Stimulus? What about people that don't use it?

I don't know the better way. 
btw, I'v refactored above example to use Stimulus' target connected callback, works for render popover I use https://stimulus.hotwired.dev/reference/lifecycle-callbacks

**Comment by x9sim9** [comment]
I found that when you have lots of turbo elements on the page I was getting way too many 
turbo:after-stream-render

**Comment by x9sim9** [comment]
I found that when you have lots of turbo elements on the page I was getting way too many 
`turbo:after-stream-render`
events firing so I modified the above code so it would only render after the last event had fired

```
let turboAfterStreamRenderTimer = null;
const afterRenderEvent = new Event("turbo:after-stream-render");

addEventListener("turbo:before-stream-render", (event) => {
	const originalRender = event.detail.render

	event.detail.render = function (streamElement) {
		originalRender(streamElement)
		clearTimeout(turboAfterStreamRenderTimer)

		turboAfterStreamRenderTimer = setTimeout(() => {
			document.dispatchEvent(afterRenderEvent)
		}, 500)
	}
})
```

**Comment by tomashomey** [comment]
here is a solution: https://nts.strzibny.name/rails-turbo-after-stream-render/

```
// application.js
const afterRenderEvent = new Event("turbo:after-stream-render");
addEventListener("turbo:before-stream-render", (event) => {
  const originalRender = event.detail.render

  event.detail.render = function (streamElement) {
    originalRender(streamElement)
    document.dispatchEvent(afterRenderEvent);
  }
})
```
