### ISSUE TITLE
Turbo frames and streams on tags

### ISSUE THREAD

**Issue by alexander-schranz** [hotwired/turbo#567]
I have the usecase that i have a table e.g.:

```html
<table>
   <tr>
       <td>1</td>
       <td>Name</td>
       <td><form method="POST"><button type="button">Some Action</button></form></td>
   </tr>
</table>
```

The button submit something and should return just the `<tr>` again.

So currently I would have todo something like this which ends in not valid HTML and requires css hacks to get the things work, but is not very nice for accessibility:

```html
<table>
   <turbo-frame id="list-1"><!-- invalid html / break table -->
       <td>1</td>
       <td>Name</td>
       <td><form method="POST"><button type="button">Some Action</button></form></td>
   </turbo-frame="list-1">
</table>
```

So what would be nice if to have something like:

```html
<table>
   <tr id="list-1" data-turbo-frame>
       <td>1</td>
       <td>Name</td>
       <td><form method="POST"><button type="button">Some Action</button></form></td>
   </tr>
</table>
```

A data attribute over a custom tag make it possible, maybe it is strange as `data-turbo-frame` is used on links for target frame but think a data-turbo-frame without a value would not conflict here.

**Comment by seanpdoyle** [comment]
Is this related to https://github.com/hotwired/turbo/issues/48?

**Comment by alexander-schranz** [comment]
@seanpdoyle thank for the fast response. The issue looks similar, I'm not using ruby so not understanding all the comments examples. I'm using turbo over symfony/ux. Are I'm missing something in the documentation, as the issue seems to be close, so I think there is a solution now? Could not find it in the documantation. What looks promising in the documentation is something like the `is` attribute:

```html
<tr is="turbo-frame"></tr>
```

What is the recommended solution here? Maybe I can add something the the docs here. What would be the correct place?

**Comment by tleish** [comment]
Assuming the form#post causes the update to the DOM, you could response with a turbo-stream response instead.

Original HTML
```html
<table>
   <tr id="name-1">
       <td>1</td>
       <td>Name</td>
       <td><form method="POST"><button type="button">Some Action</button></form></td>
   </tr>
</table>
```

POST response (MIME type of text/vnd.turbo-stream.html)
```html
<turbo-stream action="replace" target="name-1">
  <template>
   <tr id="name-1">
       <td>1</td>
       <td>Name</td>
       <td>Something else</td>
   </tr>
  </template>
</turbo-stream>
```

see [Streaming From HTTP Responses](https://turbo.hotwired.dev/handbook/streams#streaming-from-http-responses)
