### ISSUE TITLE
`data-turbo-confirm` doesn't work if the form action contains a period

### ISSUE THREAD

**Issue by lewiseason** [hotwired/turbo#570]
The simplest way to understand is probably [this Codepen](https://codepen.io/lewiseason/pen/xxpQzmV), but here is a quick rundown:

When building a form with `data-turbo-confirm`, if the last part of the URL contains a period, Turbo does not fire the `confirm`. For example:

```
<form data-turbo-confirm="Are you sure?" action="/domains/example.com" ...>
```

 I assume this has something to do with formats, because `.html` works as expected—i.e.: this is fine:

```
<form data-turbo-confirm="Are you sure?" action="/domains/example.com.html" ...>
```

I assume this is not expected behaviour. I had a quick look at the source code and couldn't see anything explaining why this might be, but I'm new to Turbo, so I'm not too sure I was looking in the right place.

Thanks! 🥳

**Comment by tleish** [comment]
see #385 discussion
