### ISSUE TITLE
Allow turbo-frame to work in cross-site scenarios

### ISSUE THREAD

**Issue by renestalder** [hotwired/turbo#574]
I have a decoupled frontend running on the main domain, while the forms developed with PHP run on a subdomain.

Since a certain Turbo version, `<turbo-form>` doesn't work anymore with cross-site links. I believe this worked back in the Beta versions of v7 at least, as I built a whole website on that architecture, with successful tests and everything.

And I can't figure out how to make this possible again so that my forms hosted on a subdomain work in my decoupled frontend without making a full-page post. At least not from the available documentation so far.

* [A forum posts issuing the same problem](https://discuss.hotwired.dev/t/support-hotwire-over-subdomains/3896)

I desperately need a way to tell Turbo which URLs are fine. The `<meta name="turbo-root">` to my understanding doesn't solve that (and can also only have one value).

**Comment by dhh** [comment]
You're hitting CORS restrictions. You need to manually control for that: https://fetch.spec.whatwg.org/#http-cors-protocol
