### ISSUE TITLE
Dropdown Bootstrap

### ISSUE THREAD

**Issue by ilhamlutfi** [hotwired/turbo#583]
Dropdown can't show submenu when i click it

**Comment by tleish** [comment]
Can you create a [codepen](https://codepen.io/lewiseason/pen/xxpQzmV) example?

**Comment by Gerbaum** [comment]
Got the same error, with bootstrap 5 and flask as backend.
If I refresh the webpage (F5), dropdown works, but if I naviagte to the webpage via a link dropdown won't work.

Browser developer view shows my local 
"**turbo.es2017-esm.js:430**"
 as initiator to load assets.
To be specific 
"**document.body.replaceWith(this.newElement);**"
is the relevat code line.

**Comment by lrjbrual** [comment]
Is this already resolved? I encounter same issue.

**Comment by marcoroth** [comment]
Hey @lrjbrual, this issue wasn't actively resolved. 

But if you are be able to provide a minimal example which reproduces the issue we are more than happy to take a look. Thank you!

**Comment by gary02** [comment]
Move bootstrap js <script> tag into <head> fixed this issue for me.

**Comment by Rebelfront** [comment]
> Move bootstrap js <script> tag into fixed this issue for me.

I have the same issue but I haven't understood your reply @gary02 ... How did you solve the problem ?

**Comment by delucas** [comment]
@Rebelfront Had the same issue, and tried what @gary02 said... and it worked! Just moved the script tags into the head section of the html. I had it in the bottom, previously.
