### ISSUE TITLE
Table and tbody with is="turbo-frame" not reload data after turbo action

### ISSUE THREAD

**Issue by francesco-loreti** [hotwired/turbo#584]
Hi,
I have created a normal table and into tbody I have added that is a turbo-frame.
`<tbody id="events" is="turbo-frame" src="/events/list">`

At first full page load, the async data are loaded(first render table and after data into tbody... perfect). But if I reload the table with turbo-action or link into data-turbo-frame, after render the table, the src action not start and async data not loaded.

Do you know if there is a solution?

Thanks!!

**Comment by francesco-loreti** [comment]
But if I use: `data: { turbo_frame: '_top' } }` it's work

**Comment by tleish** [comment]
Duplicate of https://github.com/hotwired/turbo/issues/547

**Comment by francesco-loreti** [comment]
> Duplicate of #547

Sorry and thanks!
