### ISSUE TITLE
[docs] Two different lists of events

### ISSUE THREAD

**Issue by adamalton** [hotwired/turbo#590]
In the README there's a [Full list of events](https://github.com/turbolinks/turbolinks/blob/24f396de38c6c6f87e86a265e7bd8563103b7d1d/README.md#full-list-of-events) section.

In the docs, there's an [Events reference page](https://turbo.hotwired.dev/reference/events).

These two lists are different.

The list in the README has additional items of:
* `turbolinks:request-start`
* `turbolinks:request-end`

The list in the docs has additional items of:
* `turbo:submit-start`
* `turbo:before-fetch-request`
* `turbo:before-fetch-response`
* `turbo:submit-end`
* `turbo:before-stream-render`
* `turbo:frame-render`
* `turbo:frame-load`

My preferred solution would be to remove that section from the README and just link it to the docs so that only one list needs to be maintained. I would submit a PR, but I'm not sure what the correct list is!

**Comment by marcelolx** [comment]
@adamalton Turbolinks and Turbo are different projects, that's why both lists have different events.
