### ISSUE TITLE
`turbo:visit` is not dispatched then navigating Back whilst a request is in flight

### ISSUE THREAD

**Issue by domchristie** [hotwired/turbo#594]
Reproduction repo: https://github.com/domchristie/turbo_back_test

`turbo:visit` is not dispatched then navigating Back whilst a request is in flight. I think this is because the restoration Visit is deemed to be a same page visit and so is [`silent`](https://github.com/hotwired/turbo/pull/329).

Here's what I think the flow is:

1. Visit `/`
2. Click link to `/one`
3. Request starts
4. Address bar updated to `/one`
5. Navigate Back before request finishes
6. Restoration Visit created
7. Visit checks `isSamePage` by comparing the last rendered location. Because `/one` was never rendered, the Visit is deemed to be same page, and therefore `turbo:visit` is not dispatched.

I wonder if `locationWithActionIsSamePage` should compare `window.location` rather than `this.view.lastRenderedLocation`? I feel like there was a reason we chose `this.view.lastRenderedLocation` but I can't remember :/

**Comment by domchristie** [comment]
> I feel like there was a reason we chose this.view.lastRenderedLocation but I can't remember :/

Thank Git: https://github.com/hotwired/turbo/pull/298/commits/909fdb6c704b552ede0a3a53e0b8ea13637f4ed4

**Comment by dhh** [comment]
Def should fire even if we request is in flight. Please do investigate how we can square this.
