### ISSUE TITLE
History back troubles

### ISSUE THREAD

**Issue by andimg93** [hotwired/turbo#597]
I use turbo with symfony (ux/turbo), but this shouldn't matter. While clicking around all works smooth, but as soon as you make use of the browser related history back functionality pages are broken.

In detail parts which need js are mostly broken, e.g. I use Tabulator for my tables to transform plain html to feature rich ones.
I initialize that tables also with stimulus via the connect method, but not even the headers of the table are visible.
Other abnormalities are e.g. bootstrap modals, which are completely out of functionality while coming from a history back so you can not close them or do anything with them.

Is there any general solution, have I listening for the load event of turbo to do my stuff? Or is there any simple general fix?

**Comment by tleish** [comment]
I've seen this when using 3rd party JavaScript libraries (e.g. bootstrap) that store state in memory instead of in DOM.

> Turbo Drive saves a copy of the current page to its cache just before rendering a new page. Note that Turbo Drive copies the page using [cloneNode(true)](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode), which means any attached event listeners and associated data are discarded.

see [Understanding Caching](https://turbo.hotwired.dev/handbook/building#understanding-caching)

When Turbo restores the DOM, the JavaScript state is not restored (unless using a library like stimulus combined with state data cached to the DOM).

**Comment by andimg93** [comment]
Argh makes it much harder to use… . I already use stimulus but e.g. Tabulator, which i use for my tables, will do his handlings for a given html table and afterwards destroy the origin one. So I have no possibility to get back to the old table unless I always cache the base html tables before initializing them with tabulator. Also there are some other cases I would have to consider so getting an productive bigger project ready is much more work as I initially thought about… .

**Comment by tleish** [comment]
This does not mean you can't use 3rd party libraries, it just means you sometimes need to do a little extra tooling to make them work with turbo.

see: [Bootstrap Modals Using Hotwire In Rails](https://dev.to/dalezak/bootstrap-modals-using-hotwire-in-rails-3pkh)
