### ISSUE TITLE
Turbo Stream operations ignore `[data-turbo-permanent]`

### ISSUE THREAD

**Issue by seanpdoyle** [hotwired/turbo#623]
Related to https://github.com/hotwired/turbo/pull/622#issuecomment-1176759623.

Unlike the [PageRenderer](https://github.com/hotwired/turbo/blob/98cdc4037788f078a741c7fb50412db0101bcb97/src/core/drive/page_renderer.ts#L61-L64) and [FrameRenderer](https://github.com/hotwired/turbo/blob/98cdc4037788f078a741c7fb50412db0101bcb97/src/core/frames/frame_renderer.ts#L12-L14) implementations, the [StreamActions](https://github.com/hotwired/turbo/blob/98cdc4037788f078a741c7fb50412db0101bcb97/src/core/streams/stream_actions.ts#L6-L34) do not preserve [permanent elements](https://turbo.hotwired.dev/handbook/building#persisting-elements-across-page-loads)

You can [experiment with the code on JSFiddle](
https://jsfiddle.net/yf8e6zm0/2/):

```html
<html>                                        
  <head>                                  
    <script type="importmap">                                                                                      
      {
        "imports": {
          "@hotwired/turbo": "https://cdn.skypack.dev/@hotwired/turbo"
        }
      }
    </script>
    <script type="module">
      import "@hotwired/turbo"
      
      addEventListener("click", ({ target }) => {
        if (target.matches("button")) {
          const { content } = target.querySelector("template")
          target.append(content.cloneNode(true))
        }
      })
    </script>
    <script type="module" src="https://unpkg.com/es-module-shims@0.10.1/dist/es-module-shims.js"></script>
  </head>
  <body>
    <p id="permanent" data-turbo-permanent>This should not change when you click the button</p>
      
    <button type="button">
      Click me, and hopefully nothing changes

      <template>
        <turbo-stream action="replace" target="permanent">
          <template><p id="permanent" data-turbo-permanent>Uh oh, this changed when you clicked the button!</p></template>
        </turbo-stream>
      </template>
    </button>
  </body>
</html>
```

Is this intended behavior? [Permanent elements are a Turbolinks concept](https://github.com/turbolinks/turbolinks/tree/v5.2.0#persisting-elements-across-page-loads), and pre-date Frames and Streams.

Personally, I'm not sure what I'd expect to be "correct" behavior.

On one side of the argument, "permanence" is meaningful during navigation, but might not fit the idea of a Stream operation. On the opposing side, "permanence" could implies that it should be sturdy enough to be immutable in the face of page updates.

**Comment by dhh** [comment]
I think it makes sense for permanent elements to survive stream actions. If you DON'T want a permanent element to survive, you can always just not mark it permanent in the stream content.
