### ISSUE TITLE
Uncaught DOMException when clicking a link for the first time.

### ISSUE THREAD

**Issue by MirazMac** [hotwired/turbo#65]
I'm using turbo via NPM import and when I click a link for the first time, the page renders perfectly fine. But the following error is shown in the console:
![image](https://user-images.githubusercontent.com/13865787/103456561-8674e780-4d21-11eb-8667-3b8c39e03861.png)

However, on the subsequent navigations no such exception is thrown.
I don't know if this is a major issue since I'm not a JS developer. I just wanted to let you people know about the error.
Thanks!

**Comment by xtr3me** [comment]
As this can be related to #104 did you check for duplicate loading of the Turbo library?

**Comment by MirazMac** [comment]
Turns out the issue was with browsersync.
