### ISSUE TITLE
BUG: The turbo:frame-load event is fired before window.location is updated when using turbo-action="advance"

### ISSUE THREAD

**Issue by rathboma** [hotwired/turbo#651]
To perform some actions when the turbo frame has finished loading and the URL has changed is currently not possible.

When `turbo-frame-load` fires, the `window.location` has not yet been updated, so checking `window.location.*` still gives the old URL.

Steps to reproduce:

```js
function logEvent(event) {
  console.log("comparing src vs window:", event.target.src, window.location.href)
)

document.documentElement.addEventListener('turbo:frame-load', logEvent)
```

**Comment by rathboma** [comment]
I checked out the issue. It's similar but not exactly the same -- regardless of whether you change `location` before or after rendering, certainly it should be changed before `turbo:frame-load` fires.

That fix might fix it, I have a hard time knowing -- does that change the behavior to address #617? If so it probably will

**Comment by seanpdoyle** [comment]
I've just tested this locally to confirm that it has been resolved by https://github.com/hotwired/turbo/pull/618. 

It's covered by [a test](https://github.com/hotwired/turbo/pull/618/files#diff-7ce9685efd20a2b7372c3cedabd19f1139f50105c18d1bcb3622d37411ae5482R27-R47) that makes the same check during the `turbo:frame-render` event, which is dispatched before the `turbo:frame-load` event.
