### ISSUE TITLE
Turbo putting <script> from head to body, making it duplicate

### ISSUE THREAD

**Issue by janpeterka** [hotwired/turbo#659]
Using:
Backend: Flask + [Turbo-Flask](https://github.com/miguelgrinberg/turbo-flask) library.
Turbo: `v7.1.0` (from CDN)
Browser: Vivaldi 5.3.2679.68 (Stable channel) stable (64-bit), Firefox 103.0 (64-bit) 

I was solving some weird page behaviour, and after looking closely into the code, I found out following happening.

I have an edit page with a form.
Here's its code: [edit.html](https://github.com/hotwired/turbo/files/9227509/before_update.txt)
Important part here is `<script defer type="module">` with Stimulus code.

Submitting form is normal POST to `update` controller method, which, if form is invalid, calls this code:
```python
if not form.validate_on_submit():
  return (
    self.template("edit", id=id, form=form), 
    422,
  )
```
Important part (I think) is using 422 code. I was using redirect strategy before on other places (and didn't notice this sort of problem), but I found this to be prefered way with Turbo according to docs.
So, my controller generates following code:
[response.html](https://github.com/hotwired/turbo/files/9227517/response.txt)
but after Turbo does its tricks, my page code looks like this:
[after_update.html](https://github.com/hotwired/turbo/files/9227519/after_update.txt)

Problem here is that on new page, there's `<script>` code I mentioned both in <head> (as it should be) and in <body> (which it shouldn't).

I have no idea if there something wrong with my using Turbo, or what's happening here.
When I remove Turbo from my project, stimulus is behaving correctly.

Also, maybe connected "issue" I noticed is that links in `head` are rearranged by Turbo - in this case, but also in other.

Thanks for your help with this :)

**Comment by tleish** [comment]
There's a lot going on in these files.  If you remove all non-turbo/non-stimulus javascript, do you see the same issues?

**Comment by janpeterka** [comment]
Ok, so in cleaning my files I probably found what the problem was.
Part of my header was this code:
```html
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['setUserId', "[{{ current_user.id }}] {{ current_user.name }}"]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analytics.kratto.cz/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '4']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript>
  <p style="border:0; height: 0; margin: 0;">
    <img src="//analytics.kratto.cz/matomo.php?idsite=4&amp;rec=1" style="border:0; height: 0;" alt="" />
  </p>
</noscript>
```
It's some copy-paste tracking code, and it seems like it's making mess with Turbo - specifically the `<noscript>` code - if remove that, it seems like everything is behaving correctly.

**Comment by tleish** [comment]
Glad you found the conflict.  When ready, I suggest closing this issue as well.
