### ISSUE TITLE
How to disable turbo on a certain page completely?

### ISSUE THREAD

**Issue by joker-777** [hotwired/turbo#663]
Hi, I want to make sure that turbo isn't used on a certain page when leaving it through any link or browser back button. How is this possible?

**Comment by joker-777** [comment]
I found out that I can prevent the turbo visit when listening to the `turbo:click` or `turbo:before-visit` events but how can do something similar for the history (browser back button)?

**Comment by seanpdoyle** [comment]
Turbo will [ignore any elements nested within an element with `[data-turbo="false"]`](https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms). Are you able to set `[data-turbo="false"]` on the document's `<html>` or `<body>` element?

**Comment by joker-777** [comment]
@seanpdoyle Thanks a lot for your suggestion. How do I manage the browser back button though?

**Comment by brunoprietog** [comment]
Hi @joker-777, you can disable Turbo completely by calling `Turbo.session.stop()`. You should probably have some Stimulus controller that does this when connecting, and you should instantiate it on the page where you want to disable it, for example in the body element.
