### ISSUE TITLE
number_field up and down doesn't work properly with turbo

### ISSUE THREAD

**Issue by laptopmutia** [hotwired/turbo#668]
here is the behaviour without turbo
[number without turbo.webm](https://user-images.githubusercontent.com/43276109/183114927-6b81b30b-c95e-4c5f-8a61-63155254354e.webm)

here is with turbo
[number_with turbo.webm](https://user-images.githubusercontent.com/43276109/183115077-03e93106-1779-4740-96e3-d4ba723db89e.webm)

I think its because the pointer position is slightly changed 

sorry my screen recoder cannot catch my pointer

**Comment by tleish** [comment]
Which browser?  What additional CSS are you using?  Testing it here, seems to work fine

https://codepen.io/tleish/pen/VwXxrQO

**Comment by laptopmutia** [comment]
I'm using tailwind css v 3.1.8 and 
google chrome Version 105.0.5195.102 (Official Build) (64-bit)

**Comment by marcoroth** [comment]
Hey @laptopmutia, would you mind sharing the markup and Turbo version you are using to cause the issue you are seeing?

**Comment by laptopmutia** [comment]
I'm using turbo-rails v 1.1.1

here is my markup https://play.tailwindcss.com/BgKpNYIXmB

is it because I do submit form every time the number field is changed?

**Comment by brunoprietog** [comment]
Hi @laptopmutia, [Smooth page refreshes](https://turbo.hotwired.dev/handbook/page_refreshes) should solve your problem with focus. So closing this for now
