### ISSUE TITLE
Feature request: attribute that allows ignoring a turbo-frame in a loaded page

### ISSUE THREAD

**Issue by pontaoski** [hotwired/turbo#682]
I have a filecard interface, where pages are pushed and popped on a stack of cards.

![grafik](https://user-images.githubusercontent.com/20326855/184468975-ad4e442e-4910-49a7-a75d-577d5841c916.png)

![grafik](https://user-images.githubusercontent.com/20326855/184468965-5b29c703-9082-4527-806c-782f62d62f5e.png)

Every individual filecard here is a turbo-frame, in a structure like this:
```html
<div class="folder-stack" data-controller="folder-stack">
    <turbo-frame class="folder" id="account_page" src="/account/@me">
    </turbo-frame>
    <turbo-frame class="folder folder-nest" id="use_deposit_code_page">
    </turbo-frame>
</div>
```

This works flawlessly, except for a minor graphical issue: if I go from the base page to a subpage, it sees the dummy turbo-frame in the subpage's HTML, replaces the base page with the dummy, loads the base page again, and redisplays the base page, resulting in a flicker of the background base page as it goes from `base page` -> `dummy base page initialised from child page turbo-frame` -> `base page loaded from child page turbo-frame.` I do want the loading behaviour when the page is opened directly to a URL, but not when navigating from the base page to the subpage.

**Comment by seanpdoyle** [comment]
Could the `[disabled]` attribute or `[loading="lazy"]` serve your needs here?

**Comment by pontaoski** [comment]
I don't know what those do.
