### ISSUE TITLE
7.2.0-beta.2 first child must be template for remove action

### ISSUE THREAD

**Issue by DEfusion** [hotwired/turbo#703]
When given a turbo-stream with an action of `remove` I'm getting an error stating that it must have a template element:

 `Error: <turbo-stream action="remove" target="new-form">: first child element must be a <template> element`

**Comment by marcoroth** [comment]
Hey @DEfusion, thanks for opening this issue!

Can you double check if you are running `@hotwired/turbo` and/or `@hotwired/turbo-rails` on `7.2.0-beta.2`. Because this has been fixed via #665 (reported via #664).

**Comment by DEfusion** [comment]
Thanks, I did a search in the issues but didn't find that.
