### ISSUE TITLE
Turbo progress bar not working with CSP enabled

### ISSUE THREAD

**Issue by rbclark** [hotwired/turbo#704]
I have upgraded to `v7.2.0-beta.2` in order to include https://github.com/hotwired/turbo/pull/501, and I have validated that the nonce is being added to the element however I am still receiving an error when turbo attempts to inject the progress bar styles.

**Screenshot showing the nonce being added:**
<img width="790" alt="Screen Shot 2022-08-31 at 12 09 00 PM" src="https://user-images.githubusercontent.com/2308869/187727358-00c7077d-0c39-4507-9ab4-39b7ea52ea38.png">

**Screenshot of the error:**
<img width="1724" alt="Screen Shot 2022-08-31 at 12 10 07 PM" src="https://user-images.githubusercontent.com/2308869/187727349-01f62845-45e0-4f31-b3a8-6a4d5532bd85.png">

This is with the default Rails CSP enabled:

```ruby
Rails.application.configure do
  config.content_security_policy do |policy|
    policy.default_src :self, :https
    policy.font_src :self, :https
    policy.img_src :self, :https
    policy.object_src :none
    policy.script_src :self, :https
    policy.style_src :self, :https
    # Specify URI for violation reports
    # policy.report_uri "/csp-violation-report-endpoint"
  end

  config.content_security_policy_nonce_generator = ->(request) { request.session.id.to_s }
  config.content_security_policy_nonce_directives = %w[script-src]
end
```

**Comment by brunoprietog** [comment]
I believe It is not a problem to allow unsafe_inline style policy in the CSP

**Comment by dhh** [comment]
cc @rience

**Comment by dhh** [comment]
No, whole point of adding the CSP nonce handling is that we shouldn't have to allow unsafe inline.

**Comment by codergeek121** [comment]
I looked into this and opened a corresponding PR (https://github.com/rails/rails/pull/46141) on the Rails repo. My suggestion would be to update the suggested CSP configuration in Rails, because everything is working as expected if the CSP configuration adds `style-src` to the csp-nonce-directives.

**Comment by rience** [comment]
Makes total sense. Thank you for adding this.

**Comment by rbclark** [comment]
I have updated my application to now use `config.content_security_policy_nonce_directives = %w(script-src style-src)` and everything is functioning properly. Thank you for putting the PR against Rails to correct this, hopefully for the sake of future users it is accepted! I'll go ahead and close this issue since the fix is known and there's an open PR to fix it on the appropriate project.

**Comment by akshayKhot** [comment]
> I have updated my application to now use `config.content_security_policy_nonce_directives = %w(script-src style-src)` and everything is functioning properly.

Isn't that a default in Rails? 

https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/content_security_policy.rb#L168

**Comment by rbclark** [comment]
> > I have updated my application to now use `config.content_security_policy_nonce_directives = %w(script-src style-src)` and everything is functioning properly.
> 
> Aren't those directives used by default in Rails?
> 
> [rails/rails@`main`/actionpack/lib/action_dispatch/http/content_security_policy.rb#L168](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/content_security_policy.rb?rgh-link-date=2023-08-01T20%3A56%3A46Z#L168)

Yes thanks to @codergeek121 making a PR to fix it in Rails after this issue was made 😃

**Comment by DavidPetrasek** [comment]
Even with meta tag containing the nonce in the head like this:
`<meta name="csp-nonce" content="EAcP7YZ0Z/753crufRT+Rg==">`
...it still doesn't work and on page refresh in production environment it gives me this error:
`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://www.gstatic.com https://fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-WAyOw4V+FqDc35lQPyRADLBWbuNK8ahvYEaQIYF1+Ps='), or a nonce ('nonce-...') is required to enable inline execution.`

I have checked the source code and inspected the element and couldn't find any nonce.
Temporary solution was to use the hash. 

I am using Symfony 7.1.3 and...
@hotwired/stimulus@3.2.2
@hotwired/turbo@8.0.5

**Comment by DavidPetrasek** [comment]
@4lllex I solved it and I propose changing the name to:
`<meta name='csp-style-nonce' ... `
... which is clearer, because there can be a script nonce as well.

**Comment by 4lllex** [comment]
@DavidPetrasek that's probably a good idea, you should post it as a separate issue.
