### ISSUE TITLE
response `<turbo-stream>` and `HTML`

### ISSUE THREAD

**Issue by seb-jean** [hotwired/turbo#714]
I think it would be interesting to be able to combine `<turbo-stream>` and `HTML`.

Let's imagine that I am on the home page of the email inbox. In a menu there is:

- Primary
- Specials
- Social
- Updates
- Forums (10)

When I click on "Forums (10)", the idea is that it becomes "Forums" and that I am on page "/forums".

I arrive well with a `<turbo-stream>` that "Forums (10)", becomes "Forums", but the problem is that I stay on the same page.

The idea then is to have:
```html
<turbo-stream action="update" target="forums">
  <template>
  </template>
</turbo-stream>
```

but also to return our classic HTML page.

If we work with turbo rails, it will be `format.turbo_stream` AND `format.html`

**Comment by brunoprietog** [comment]
Hi @seb-jean, thanks for your proposal. It's not in our plans to implement something like this at the moment. The potential of this is not very clear and we prefer to keep things simple for the time being.
