### ISSUE TITLE
Turbo stream error

### ISSUE THREAD

**Issue by jason-hobbs** [hotwired/turbo#721]
When on 7.1.3 I have a link in a frame tag:
`=link_to assignee.username, jobrequest_job_request_assign_path(@request, assign: assignee), method: :post, class: 'dropdown-item'`
This then is sent as a turbo_stream like expected:
```
"/jobrequest/job_requests/17/assign?assign=admin-user" for 127.0.0.1 at 2022-09-17 11:07:49 -0500
11:07:49 web.1  | Processing by Jobrequest::JobRequestsController#assign as TURBO_STREAM

```
With rc.2 it errors out saying:
No route matches [GET] "/jobrequest/job_requests/17/assign"

I am not using get but it looks like it is doing both?

```
Started GET "/jobrequest/job_requests/17/assign?assign=admin2" for 127.0.0.1 at 2022-09-17 11:09:32 -0500
ActionController::RoutingError (No route matches [GET] "/jobrequest/job_requests/17/assign"):
Started POST "/jobrequest/job_requests/17/assign?assign=admin2" for 127.0.0.1 at 2022-09-17 11:09:32 -0500
11:09:32 web.1  | Processing by Jobrequest::JobRequestsController#assign as TURBO_STREAM
```

**Comment by marcoroth** [comment]
Hey @jason-hobbs, thanks for opening this issue!

I think what you want in this case is the `data-turbo-method="post"` attribute on your a-tag. The `method: :post` argument is from the UJS days and is most likely interfering here.

**Comment by jason-hobbs** [comment]
Well, that fixed it right up.  Thanks a lot!
