### ISSUE TITLE
`turbo:click` is not fired when navigating using frames

### ISSUE THREAD

**Issue by manuelpuyol** [hotwired/turbo#726]
I think this is happening since `7.2.0-beta.2`

https://user-images.githubusercontent.com/11280312/191311525-52fe38d5-4c08-4f0e-9c81-d07c9dd8883e.mov

**Comment by manuelpuyol** [comment]
looks like this was introduced by https://github.com/hotwired/turbo/pull/412 @seanpdoyle

**Comment by seanpdoyle** [comment]
@manuelpuyol thank you for catching this! I've opened https://github.com/hotwired/turbo/pull/729 to resolve the issue.
