### ISSUE TITLE
`[aria-busy="true"]` activates on turbo-frame element when clicking links with `data-turbo-frame="_top"`

### ISSUE THREAD

**Issue by BakiVernes** [hotwired/turbo#727]
Using the latest **7.2.0-rc.2** branch I have run into an issue (previous version was **7.1.1**). 

I have used the aria-busy property of a lazy-loaded `<turbo-frame>` to enable/disable a spinner. The turbo-frame element loads a bunch of anchors that have the data-turbo-frame="_top" attribute. These anchors are a simple redirect to another page. This works perfectly. 
After upgrading, clicking on every anchor inside the `<turbo-frame>` triggers the aria-busy property on the frame (even though the target is set to "_top"). This, of course, shows the spinner before the redirect which is confusing. 

I looked through the changes and couldn't seem to pinpoint the exact cause. Would love to know if this change is intentional and if so why?

**Comment by seanpdoyle** [comment]
@BakiVernes thank you for opening this issue.

I've created https://github.com/hotwired/turbo/pull/728, but was unable to reproduce this on the latest version of Turbo. Could you review that pull request and help me add test coverage that reflects your circumstances?

**Comment by seanpdoyle** [comment]
@BakiVernes are you able to reproduce your issue on the [7.2.0-rc.3](https://github.com/hotwired/turbo/releases/tag/v7.2.0-rc.3) release?

**Comment by BakiVernes** [comment]
@seanpdoyle Couldn't reproduce the issues with [7.2.0-rc.3](https://github.com/hotwired/turbo/releases/tag/v7.2.0-rc.3). It is weird though as I don't see anything in rc.3 that could have affected this problem.

But anyway thanks for adding a test for this case. Effort was not in vain after all.
