### ISSUE TITLE
Error "Form responses must redirect to another location" when using POST without redirect

### ISSUE THREAD

**Issue by sigsegvat** [hotwired/turbo#73]
when using turbo with forms that don't respond with fetch response.redirected on POST request, turbo throws a "Form responses must redirect to another location" error.

It would be nice (especially for legacy application) that turbo can handle all kind of results of a form posts without throwing an error.

The form in question ist just a html form with POST and responds with 200 every time. expected behaviour would be that turbo does the same as with clicking a link.

Im not even sure how a "correct" POST should look like so that turbo works, documentation is not clear on that. from the source code it looks like response.redirected and response.ok must both be true.

**Comment by sstephenson** [comment]
This is by design. Form submissions should redirect to a new location on success or render a 4xx or 5xx response when there's an error. Support for the latter is available in [7.0.0-beta.2](https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.2).

**Comment by edelvalle** [comment]
I know that responding to a form error with 200 is not OK.
But adding turbo to an old application to enhance it can potentially break it without warning.

**Comment by darkomenx** [comment]
Do you have more informations about this behaviour of Turbo and submitted Form ?
Because not very much examples or explanation

**Comment by 4lllex** [comment]
@darkomenx https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission

**Comment by darkomenx** [comment]
Thank you @4lllex for your advice !

Finally my issue was from my backend engine but not Turbo submission.

Then, my advice is warning about your technologies behind the Turbo before incriminate him.
