### ISSUE TITLE
ERROR: "@hotwired/turbo@v7.2.0" could not be built.

### ISSUE THREAD

**Issue by edwinmartinson** [hotwired/turbo#731]
Am using the skypack.dev CDN and I keep getting this issue. Their CodePen demo also shows this error. This issue started  around  2:30pm GMT.

**Comment by Benoit1980** [comment]
Same here with:
```
        @livewireScripts
        <script src="https://cdn.jsdelivr.net/gh/livewire/turbolinks@v0.1.x/dist/livewire-turbolinks.js" data-turbolinks-eval="false" data-turbo-eval="false"></script>
        @stack('scripts')
```

**Comment by dhh** [comment]
Can't replicate this when building using esbuild on a fresh local Rails 7 app. Maybe just a skypack issue?

**Comment by ryw** [comment]
HTTP response from https://cdn.skypack.dev/@hotwired/turbo indicates a build error... not sure how that is triggered and if it's an internal skypack problem

```
/*
 * [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;
```

**Comment by Benoit1980** [comment]
Yes this is why I have also notified them here:
https://github.com/skypackjs/skypack-cdn/issues/319

Thanks again.

**Comment by ryw** [comment]
Is there a way to re-trigger the build - seems this occurred w/ the latest commit https://github.com/hotwired/turbo/commit/530bde2fd9beb6f62837683ffa0d60192f508c1f

**Comment by marcoroth** [comment]
I think Skypack needs to re-trigger a build from their side, as everything seems fine from the Turbo side of things.

Alternatively, you could temporarily switch to one of the other CDNs:
```
https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.2.0/dist/turbo.es2017-esm.js
https://ga.jspm.io/npm:@hotwired/turbo@7.2.0/dist/turbo.es2017-esm.js
```

**Comment by Benoit1980** [comment]
Its working now, thanks guys!
