### ISSUE TITLE
Turbo build error

### ISSUE THREAD

**Issue by 3ch3r46** [hotwired/turbo#734]
`console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;`

**Comment by marcoroth** [comment]
Hey @3ch3r46, sadly this is an issue on Skypack's part.
 
See [hotwired/turbo#731](https://github.com/hotwired/turbo/issues/731) and [skypackjs/skypack-cdn#319](https://github.com/skypackjs/skypack-cdn/issues/319) for context.

**Comment by 3ch3r46** [comment]
thank's for the answer
