### ISSUE TITLE
Skypack turbo down

### ISSUE THREAD

**Issue by oliwoodsuk** [hotwired/turbo#735]
Just heard a report from one of our customers, it sounds like this may have happened as early as Thursday. Didn't spot it earlier as we use it for a kind of external customer portal section of our app.

We were just using the unversioned link from the Turbo handbook docs: https://cdn.skypack.dev/@hotwired/turbo

Cheers,

Oli

```
/*
 * [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;
```

**Comment by oliwoodsuk** [comment]
Quick fix:
```
<!-- <script type="module"> import Turbo from 'https://cdn.skypack.dev/@hotwired/turbo';  </script> -->
<script src="https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.2.0/dist/turbo.es2017-umd.min.js" async type="text/javascript"></script>
```

**Comment by kotus-app** [comment]
Same thing here.

**Comment by marcoroth** [comment]
Sadly this is an issue on Skypack's part.

See hotwired/turbo#731 and skypackjs/skypack-cdn#319 for context.

**Comment by oliwoodsuk** [comment]
> Hey @oliwoodsuk, were you able to resolve this? The latest version on skypack seems to be working fine again!

Hey @marcoroth ,
Seems to be working again now, but have since moved to using Jsdelivr. 

Great work on the Outlets API for Stimulus by the way!

**Comment by marcoroth** [comment]
Thank you @oliwoodsuk! 

Can we close this issue?
