### ISSUE TITLE
Scrolling getting hijacked in 7.2.0 (page won't scroll)

### ISSUE THREAD

**Issue by akaspick** [hotwired/turbo#736]
Everything works in Turbo 7.1.1, but after upgrading to 7.2.0, my pages are getting "locked" and won't scroll even though the content of the page is longer than the browser (Firefox and Chrome) window.  I'm using Turbo in a Rails app.

My scenario occurs when I'm submitting a form via a "modal dialog" that has it's own turbo-frame.  The form targets the "_top" frame, but "_top" is ignored when the response is a turbo_stream for processing a form error for example. ie. If there's a form error, then just the turbo-frame is updated via the stream, otherwise "_top" is targeted.

```
<turbo-frame id="modal" ...>
  <form data-turbo-frame="_top" ...>
  </form>
</turbo-frame>
```

After a successful update via the modal, "_top" is targeted and the full page is replaced.  At this point, the page no longer scrolls until I refresh the page.

I don't have an example app to show the issue unfortunately, but I'm not familiar enough with the Turbo code base to know under what circumstances Turbo would disable scrolling of the page.  Is there something specific I should be looking for that might get me back on track or is there in fact a new bug in Turbo causing this problem?

**Comment by marcoroth** [comment]
Hey @akaspick, thanks for opening this issue!

Without seeing the code it's kinda hard to guess. But I assume that the modal library you are using is causing the scroll lock. 

Maybe you need to tell the modal library to release the scroll lock after you update the frame/when the element disappears from the DOM?

**Comment by akaspick** [comment]
@marcoroth That actually sounds like a possible cause to the issue I'm having.  Even though I saw no issue in 7.1 and haven't made any changes to the modal related code, there's likely something I'm not handling correctly that 7.2 is now making apparent.

I'll dig further into the modal code to make sure it's releasing the scroll lock.  My first assumption was the turbo upgrade as that was the only thing that changed, but I think your assumption is correct and will put me back on track.

**Comment by akaspick** [comment]
@marcoroth The modal library locking the scroll was indeed the issue. Big thanks.
