### ISSUE TITLE
.haml file extension not working without .html on Turbo

### ISSUE THREAD

**Issue by chmich** [hotwired/turbo#738]
**Hi,**

thanks for the great new feautures!

Detail:

**Env**

Rails 7.0.4
Ruby 3.1.2
haml-rails 2.0.1
"@hotwired/turbo": "^7.2.0"

**Scenario**

Create new app with any scaffold (customers by example)
I have no show view: Edit and create goes from index directly to form and back if successfully saved (i do'nt think that this matters)
Turboframes not applied (all links like before turbo, so that turbo defaults to the body)
Turbo is inited and works, see it in developer console and on the speed on the browser.

**Current Behaviour**

Now change `app/views/customers.index.html.erb` to `index.haml`

Visit `http://localhost:5100/customers/3/edit`
click Submit
=> The Browser History (url) remains on `/customers/3/edit`
=> The Form remains visible (looks like `redirect_to customers_path` did'nt work
=> The new html is doubled: the content of head added below the body and the content of the new body (customers/index) below.

![grafik](https://user-images.githubusercontent.com/31048265/192525913-03143d60-6975-4756-bd3c-9ba8ca67b73a.png)

Then change index to `index.html.haml`

navigate to the form and click submit
it all works like expected:
=> the browser history changes to `/customers`
=> its displaying the customers list like expected

So, for now i can work but would be happy if i can name `.haml` files like usual without the html extension

All the other views (edit, partials like _form) are named just by `.haml` (example: `edit.haml`)  and are working properly. I just had to rename the index view for the form-submission. `index.haml` would work for navigating by link! Mentioned behaviour is only by redirect after Form Submission.

**many thanks!**
**Christian**

**Comment by brunoprietog** [comment]
Hello! I'm afraid this is not a Turbo bug, nor a turbo-rails bug either.
