### ISSUE TITLE
`frame.reload()` triggers `turbo:before-fetch-request` callback twice

### ISSUE THREAD

**Issue by manuelmeurer** [hotwired/turbo#739]
After upgrading to Turbo 7.2.0, I noticed that calling `reload()` on a frame triggers the `turbo:before-fetch-request` callback twice. The request is only performed once, though.

The reason is that `reload()` calls `this.removeAttribute("complete")` and the frame watches attribute changes and calls `this.loadSourceURL()` when the “complete” attribute is removed.
The change was introduced in #487.

**Comment by seanpdoyle** [comment]
Thank you for opening this issue!

I've opened https://github.com/hotwired/turbo/pull/740 to try and resolve it.
