### ISSUE TITLE
7.2 data-remote inside turbo-frame produces double requests

### ISSUE THREAD

**Issue by acetinick** [hotwired/turbo#743]
Since upgrading to turbo 7.2 which we use extensively throughout our project, we have some introduced issues when we have some legacy data-remote="true" UJS being triggered within a turbo-frame.  

When we have a situation where we have a data-remote inside a turbo-frame, things break down.  Example:

```
<turbo-frame id="example">
   <a data-remote="true" href="/customers/new">click</a>
</turbo-frame>
```

What ends up happening is that the remote gets triggered, but for some reason a double request occurs issueing the turbo as well along with the UJS call to the URL.   Attached example from console (from a real situation not above example)

![image](https://user-images.githubusercontent.com/571649/192798644-041f4249-1331-4e8f-8836-78ec9c527b53.png)

- the 406 is the turbo request, which is NOT expected resulting in an UnkownFormat exception which trying to render a .html format, but we only have a .js.erb view
- the 200 is the UJS request, which is expected to return JS to open a modal window

I can conifrm that when we downgrade to 7.1 everything works fine,  but as soon as we upgrade issue is reproduced.  VERY strange tho, for some reason it only happens in non-local environments.   Locally it works, but in staging it breaks.

It also doesn't seem to matter if its data-method="post" or data-method="get",  it occurs always with data-remote when inside a turbo-frame.

My gut feel it must be related to #612 or #645, which is a huge benefit we already making use of this, but somehow its conflicting with data-remote somehow.   @kevinmcconnell @seanpdoyle perhaps you got some ideas?

**Comment by seanpdoyle** [comment]
Thank you for opening this issue @acetinick. I've opened https://github.com/hotwired/turbo/pull/744 to try and resolve it.
