### ISSUE TITLE
Frames are caching too late

### ISSUE THREAD

**Issue by manuelpuyol** [hotwired/turbo#745]
Kinda related to https://github.com/hotwired/turbo/issues/643

When doing a frame navigation, the frame `src` changes _before_ the page is cached, causing some weird interactions when going back/forwards.

### Example

Frames with `data-turbo-action="advance"`

https://user-images.githubusercontent.com/11280312/192871541-55fcfbac-1845-4caa-bb02-8eb054797a56.mov

**Comment by manuelpuyol** [comment]
@seanpdoyle it looks like when the frame is promoted with `advance`, we start a visit **after** the frame is already loaded, so the PageView snapshot cache is running with the new HTML instead of the original one

**Comment by seanpdoyle** [comment]
@manuelpuyol thank you for opening this issue and providing instructions on how to reproduce.

I've pushed up a breaking test to https://github.com/hotwired/turbo/compare/seanpdoyle:fix-issue-745, and am investigating a resolution.

**Comment by manuelpuyol** [comment]
Thanks for looking into this @seanpdoyle !

I opened a possible solution here https://github.com/hotwired/turbo/pull/746, gonna pull in your tests to check if they pass
