### ISSUE TITLE
using `data-turbo=false` causes Can't verify CSRF token authenticity.

### ISSUE THREAD

**Issue by jasonfb** [hotwired/turbo#757]
When using on a **form submission**, the behavior now leads to `Can't verify CSRF token authenticity.` even when the CSRF token is present (both the headers one and the form token)

consider this example:
```
Normal form, using Turbo:

<%= form_tag 'welcome' do %>
  This is a useless field:
  <%= text_field_tag :useless_field %>
  <%= submit_tag %>
<% end %>

<br>
Another form using <code>data-turbo=false</code>
<%= form_tag 'welcome', 'data-turbo': false do %>
  This is a useless field:
  <%= text_field_tag :useless_field %>
  <%= submit_tag %>

<% end %>
```

Both of these forms are submitting to a controller called `Welcome` (for demo only) on the create action

When you click the first one, turbo does its thing and responds correctly, 

When you click the second one, I get `Can't verify CSRF token authenticity.` even though I can see both tokens on the page's HTML:

![Monosnap Action Controller: Exception caught 2022-10-10 15-15-54](https://user-images.githubusercontent.com/59002/194937370-e46cad2f-1b3f-4504-a3e2-153762f63b18.png)

The reproduction app is here:
https://github.com/jasonfb/DataTurboFalseCSRFTest

check out the above code at 
https://github.com/jasonfb/DataTurboFalseCSRFTest/blob/main/app/views/welcome/index.erb

Actual Result: 
- crashes with `Can't verify CSRF token authenticity.`

Expected Result:
- The authenticity token is passed correctly.

**Comment by brunoprietog** [comment]
This is not a Turbo error.

If you comment the application.js lines and test the example it should work without problems, since Turbo is not interfering with anything, but it still doesn't work.

Uncomment the lines.

Now, in index.erb, modify the path to /welcome and everything works as expected.

Anyway, I recommend you use the Rails form_with helpers instead and use the .html.erb extension in the views filenames.

```erb
<%= form_with url: welcome_index_path, method: :post, data: {turbo: false} do |form| %>
  <%= form.label :useless_field, 'This is a useless field:' %>
  <%= form.text_field :useless_field %>
  <%= form.submit %>
<% end %>
```

**Comment by jasonfb** [comment]
yes thank you this was mis-diagnosed
FYI, for some reason, there is something to do with the leading slash of the path name, which is the root cause. the effect is the same for `form_with` and `form_for`; yes thanks for the tip about using the more modern alternative. 

These both work:
```
A Form using <code>form_with</code>
<%= form_with url: '/welcome', method: :post, data: {turbo: false} do |form| %>
  <%= form.label :useless_field, 'This is a useless field:' %>
  <%= form.text_field :useless_field %>
  <%= form.submit %>
<% end %>

Another form using <code>form_tag</code>
<%= form_tag '/welcome', method: :post do %>
  This is a useless field:
  <%= text_field_tag :useless_field %>
  <%= submit_tag %>
<% end %>
```

these both lead to the `Can't verify CSRF token authenticity.`

```
<br>
A Form using <code>form_with</code>
<%= form_with url: 'welcome', method: :post, data: {turbo: false} do |form| %>
  <%= form.label :useless_field, 'This is a useless field:' %>
  <%= form.text_field :useless_field %>
  <%= form.submit %>
<% end %>



Another form using <code>form_tag</code>
<%= form_tag 'welcome', method: :post do %>
  This is a useless field:
  <%= text_field_tag :useless_field %>
  <%= submit_tag %>
<% end %>
<br>
A Form using <code>form_with</code>
<%= form_with url: 'welcome', method: :post, data: {turbo: false} do |form| %>
  <%= form.label :useless_field, 'This is a useless field:' %>
  <%= form.text_field :useless_field %>
  <%= form.submit %>
<% end %>



Another form using <code>form_tag</code>
<%= form_tag 'welcome', method: :post do %>
  This is a useless field:
  <%= text_field_tag :useless_field %>
  <%= submit_tag %>
<% end %>

```

**Comment by jasonfb** [comment]
maybe somehow Turbo affects the submission masking the problem when it is **on**, not off.

**Comment by saint-james-fr** [comment]
Any news on this issue? This is weird as I only encountered the problem after installing this gem 
https://github.com/tigrish/devise-i18n/

**Comment by Tashows** [comment]
This happened to me too. In my case it wasn't a misconfiguration of the form helper. Inside my form I was rendering a partial, which at some point had a button_to helper. This was then rendered into a form with a separate authenticity_token. I guess with Turbo enabled, Turbo looks at the first authenticity token and submits the form properly, but disabling Turbo, leads to the second authenticity token overwriting the first one, as expected because html forms work this way.
