### ISSUE TITLE
how to bind callback into ajax form success (using data attribute remote: true but it keep redirect to new page)

### ISSUE THREAD

**Issue by leduananh** [hotwired/turbo#761]
I have simple form:
<%= form_with(url: form_submit_path, data: {remote: true}) do |f| %>
  <%= f.submit 'Submit',
               class: "btn btn-primary"
  %>
<% end %>
=> Turbo keep redirect me to new page

**Comment by brunoprietog** [comment]
Hi @leduananh, `data-remote` is not supported by Turbo. You can see the list of events that Turbo emits [here](https://turbo.hotwired.dev/reference/events), where you can invoke the callbacks you want with event listeners.
