### ISSUE TITLE
Location not updated when clicking on same-page fragment links

### ISSUE THREAD

**Issue by kevinmcconnell** [hotwired/turbo#762]
When clicking on a link to a fragment on the current page, the location in the address bar does not update to reflect the fragment. However, clicking the same link a second time in a row _does_ update it.

This behaviour seems to have been introduced in #601.

A simple reproduction is as follows:

```html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.2.0/dist/turbo.es2017-umd.min.js"></script>
  </head>

  <body>
    <h1 id="id1">one</h1>
    <h1 id="id2">two</h1>

    <a href="#id1">one</a>
    <a href="#id2">two</a>
  </body>
</html>
```

On this page, clicking the anchor tags does not update the location in the browser address bar. Clicking the same link twice in a row will update it.

When using a version prior to #601, like Turbo 7.1.0, the location updates correctly.

**Comment by dhh** [comment]
Cc @manuelpuyol

**Comment by seanpdoyle** [comment]
Thank you for opening this issue @kevinmcconnell! I've opened https://github.com/hotwired/turbo/pull/763 to try and restore the previous behavior. Does it resolve your issue?

@manuelpuyol Could you manually test it to make sure it doesn't undo important changes from #601? Were there other places that called `Visit.updateHistory` that might result in double entries (one from the normal Visit process, one from the `Visit.goToSamePageAnchor` call)?

**Comment by kevinmcconnell** [comment]
@seanpdoyle thanks for the quick response! #763 does indeed resolve the issue that I was seeing 👍
