### ISSUE TITLE
turbo:render not being triggered

### ISSUE THREAD

**Issue by leei** [hotwired/turbo#769]
I'm trying to track this, but in my app (turbo-rails 1.3.1 so turbo 7.2.2) the last event being triggered when my <turbo-stream> is processed is turbo:before-stream-render (i.e. no turbo:render even after the event is successfully processed).

It seems to have something to do with the <turbo-stream> being processed through `StreamMessageRenderer`.  It seems to execute the `viewRenderedSnapshot()` pathway only if the message is **not** a stream (i.e. is processed by `View#render`). This means that none of the post-render processing seems to be done when this path is taken.

Am I missing something or should there be a generic post-render callback that handles all of this stuff and is also triggered asynchronously after the `StreamMessageRenderer` is finished?

**Comment by brunoprietog** [comment]
Hi @leei, that event is only fired when rendering a page, not when rendering Turbo streams. You can see more detailed information about the events [here](https://turbo.hotwired.dev/reference/events).
