### ISSUE TITLE
turbo-cable-stream-source is not getting replaced

### ISSUE THREAD

**Issue by rockwellll** [hotwired/turbo#773]
Hello, hoping you're having a good day :)

So, i was surprised to find out that the `turbo-cable-stream-source` element yielded by `turbo_stream_from` is not being replaced. So, i have a `show.turbo_stream.erb` that looks like this,

```
<%= turbo_stream.replace "conversation-inbox", class: "w-full flex" do %>
  <%= turbo_stream_from @conversation %>
.......
```

When the request is made multiple times, the element is not being replaced, which results in a markup that looks like this,

<img width="1028" alt="Screen Shot 2022-10-21 at 09 54 21" src="https://user-images.githubusercontent.com/38360603/197132011-76cc4df4-2f89-4d60-a4e6-8d850ab87e78.png">

This is weird because i saw that events that happened elsewhere(broadcasted to another stream) where showing up on wrong streams. 

Any idea what i might be doing wrong?

**Comment by seanpdoyle** [comment]
When you render a `<turbo-stream action="replace">`, its `<template>` element's contents replace whichever element is targeted by the `[target]` or `[targets]` attribute.

If you were to inspect the response, does the `<turbo-stream>` element's nested `<template>` render the `<turbo-cable-stream-source>` as a descendant of the element with `[id="conversation-inbox"]`, or a sibling?

Does the `<template>` element include an element with `[id="conversation-inbox"]`? If not, would a call to `turbo_stream.update` better suit your use case?
