### ISSUE TITLE
"this.form.submit()" call does not engage turbo-frames

### ISSUE THREAD

**Issue by helloguille** [hotwired/turbo#775]
Using this.form.submit() in the latest version of turbo (7.2.4) refreshes the entire page. 

<input onchange="this.form.submit()" > does not have the same effect as:

<input type="submit"> which actually works impeccably.

Could that be a bug?

**Comment by seanpdoyle** [comment]
Calls to [HTMLFormElement.submit()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit) and [HTMLFormElement.requestSubmit()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) have slightly different behaviors.

Turbo works by listening for `submit` events that `<form>` elements dispatch, then taking control of the ensuing submission. 

When calling `.submit()`, those events are not dispatched. 

Are you able to reproduce the unexpected behavior you're experiencing by calling `this.form.requestSubmit()`?

**Comment by helloguille** [comment]
Wow thanks! 

It works now.

**Comment by seanpdoyle** [comment]
@helloguille that's great to hear! If the problem is resolved, would it be appropriate to close this issue?

**Comment by helloguille** [comment]
Yes thanks!
