### ISSUE TITLE
Reloading a frame from the same URL

### ISSUE THREAD

**Issue by elliotcm** [hotwired/turbo#776]
Hi there,

I have a situation where I have an element on a page which needs to be reloaded when certain events happen.  One way I thought to do this was to wrap it in a `turbo-frame` and call `.reload()` on it when necessary.

This issue is that I have to specify a `src` attribute for the frame to be reloaded, and this page is already the canonical source for that element.  I'd rather not do a full page refresh if not otherwise needed.

That would mean that I'd have to specify `<turbo-frame src="/the-current-page">` which I can't do because it raises a specific error saying that's not valid.

I'm not entirely sure why that restiction exists, but is there a common way to solve this?

Thanks.

**Comment by brunoprietog** [comment]
Yes, you can make `frame.src = url` in the Turbo frame element and it will trigger a reload

**Comment by brunoprietog** [comment]
Alternatively, you can have a `<a href="url" hidden></a>` element, and create, for example, a stimulus controller that clicks on that element when you need to force reload.

**Comment by elliotcm** [comment]
Thanks!
