### ISSUE TITLE
iOS 13.7 Support

### ISSUE THREAD

**Issue by danieldocki** [hotwired/turbo#795]
I have an error in iOS 13.7, in a POST request, using turbo_stream.update

`
TypeError: e.replaceChildren is not a function. (In 'e.replaceChildren(this.templateContent)', 'e.replaceChildren' is undefined)
`

there seems to be something on this line the error

https://github.com/hotwired/turbo/blob/00b287af773952d6e122a19356a6cdadf5fd86d2/src/core/streams/stream_actions.ts#L34

**Comment by marcoroth** [comment]
Also, for context: https://github.com/hotwired/turbo/pull/534
