### ISSUE TITLE
Turbo data attributes not working when on custom elements

### ISSUE THREAD

**Issue by rctneil** [hotwired/turbo#801]
Hi,

I am using Turbo data attributes on an <sl-button> custom element coming from the Shoelace library and they don't appear to be working, even if I pass the data attribute down into the a of the element shadow dom.

Here's an issue I posted in Shoelace about this: https://github.com/shoelace-style/shoelace/discussions/998 @claviska

Just wanted to post here to get some insight from the Turbo side.

I'm wondering if Turbo needs some sort of config option to specify non default elements to watch?

Thanks.

**Comment by marcoroth** [comment]
Hey @rctneil, thanks for opening this issue!

Just to make sure: are you actually using `data-turbo_method="post"`? 
It's meant to be `data-turbo-method` with two dashes.

**Comment by rctneil** [comment]
@marcoroth Ah ok, I will make sure I update that.   The part I am testing is actually the turbo-frame attribute.   That's definitely using the correct data attribute name but not working.

**Comment by marcoroth** [comment]
ok cool, gotcha! 

Would you mind providing a minimal repro on something like https://jsfiddle.net/? That would help tremendously  with troubleshooting what you are seeing. Thank you!

**Comment by rctneil** [comment]
@marcoroth Apologies for the delay. I have created a demo here: https://codepen.io/rctneil/pen/KKeQMym

It has one frame and 4 links underneath.  It should all be commented to explain the differences.

I hope it helps!    Would be really cool to get Turbo detecting the custom elements being created by @claviska !

**Comment by yuki24** [comment]
I have looked into this issue and noticed that this is possibly because of the Shadow SOM preventing events from propagating across the shadow DOM boundary. The PR #802 should address this issue.

**Comment by rctneil** [comment]
With the patch, how should the data attributes be configured?

Like link 3 or link 4 in my demo?

**Comment by yuki24** [comment]
@rctneil The `data-turbo-frame` attribute was missing in the PR so I added it back. With that said, in your app, you don't have to configure that as the event target becomes the outer element and that element is the element that should have a `data-turbo-frame`:

<img width="1581" alt="turbo-frame" src="https://user-images.githubusercontent.com/386234/203270985-d6e35c08-bbf9-4422-ab92-baacde09cfb4.png">

(Which implies that one shadow DOM can't contain multiple `a` tags with different `data-turbo-frame` values... we may be able to make it more reliable by using `composedPath`, but it's probably something we can iterate on.)

**Comment by yuki24** [comment]
I'm noticing a lot more edge cases due to the Shadow DOM boundary, and these two lines likely need to be updated like #758, so it will cross the boundary of the Shadow DOM:

https://github.com/hotwired/turbo/blob/00b287af773952d6e122a19356a6cdadf5fd86d2/src/core/session.ts#L406-L407

But I would like to see #801 and #758 merged first to make smaller incremental steps. I'll send a few more PRs once they are ready.

**Comment by rctneil** [comment]
@yuki24 No rush but just wondering when the fix will be merged into stable?

**Comment by yuki24** [comment]
I don't actually have the commit rights and can't merge or push PRs. I think it's ultimately up to @marcoroth or other maintainers.

@marcoroth Apologies for pinging. I know you are quite busy and a just a few quick words like "I'm busy now so this will take a few weeks" or "onboard with the direction but needs time" would be greatly appreciated. Also let me know if there is anything I can do to accelerate the process. Thank you!

**Comment by marcoroth** [comment]
Hey @yuki24, full disclosure: I don't have commit rights either.

But I'm generally also in favor of properly supporting custom elements as good as possible within Turbo. Of course just if that means that we don't break existing functionality, otherwise we would need to find another way to support it. But I think both https://github.com/hotwired/turbo/pull/758 and https://github.com/hotwired/turbo/pull/802 are definitely worth to consider!

**Comment by yuki24** [comment]
@marcoroth I didn't know even you don't have commit rights, apologies for my misunderstanding! Let me know if there is anything I can do to get the PRs merged.
