### ISSUE TITLE
Turbo-frame within <table> tags

### ISSUE THREAD

**Issue by jsagl** [hotwired/turbo#81]
Hi !
It seems that when placing a turbo-frame tag within a table tag, it ends up outside of the table in the DOM. As a consequence, when clicking the link, only the content of the target page ends up being displayed, and outer html is gone. I don't have this issue when using simple div tags.

![image](https://user-images.githubusercontent.com/39709913/103789492-5fc7f100-5040-11eb-99e1-f342093c4c28.png)
![image](https://user-images.githubusercontent.com/39709913/103788949-b8e35500-503f-11eb-9656-e622e041183a.png)
![image](https://user-images.githubusercontent.com/39709913/103789129-f1832e80-503f-11eb-804a-ceb72b639e0a.png)

PS: first issue ever opened, so I am sorry if some information is missing or if it's not the proper place to submit this.

**Comment by seanpdoyle** [comment]
@jsagl thanks for opening this issue. Is this similar to https://github.com/hotwired/turbo/issues/48?

**Comment by jsagl** [comment]
> @jsagl thanks for opening this issue. Is this similar to #48?

Yes, sorry, closing now
