### ISSUE TITLE
Form submitted by JS provoke full page reload

### ISSUE THREAD

**Issue by benzen** [hotwired/turbo#816]
With the following html

```
<turbo-frame id="X">
    <form method="POST" action="/some-page" id="myForm">
         <input type="hidden" onchange="myForm.submit()" value="whatever">
    </form>
<tubo-frame>
```

The backend only need to redirect to the same page.

By contrast if the form us submitted with a button, then, with the same backend, turbo will replace the current turbo-frame with the new content, as expected

```
<turbo-frame id="X">
    <form method="POST" action="/some-page" id="myForm">
         <input type="hidden" value="whatever">
         <button>Submit</button>
    </form>
<tubo-frame>
```

And I've notice that the button could be hidden and triggerd by a change on the input field, in this case the behavior is as expected.

**Comment by seanpdoyle** [comment]
Thank you for opening this issue.

Calls to [HTMLFormElement.submit][] do not dispatch `submit`, whereas calls to [HTMLFormElement.requestSubmit][] will.

The [Turbo Handbook: Form Submissions][] section of the documentation mentions:

> To submit a `<form>` element programmatically, invoke the [HTMLFormElement.requestSubmit()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit) method and pass an `<input type="submit">` or `<button>` element as an optional parameter.

Could the Form Submission documentation be improved to make that requirement more clear?

[Turbo Handbook: Form Submissions]: https://turbo.hotwired.dev/handbook/drive#form-submissions
[HTMLFormElement.submit]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit
[HTMLFormElement.requestSubmit]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit

**Comment by benzen** [comment]
Thank you very much, very helpfull.

I don't understand the relation between the phrase you extracted and the context arround in this doc.
Maybe extract it into it's own paragraph?
