### ISSUE TITLE
Handling form submission validation errors within a modal

### ISSUE THREAD

**Issue by culov** [hotwired/turbo#82]
I'm trying to submit a form from within a modal overlay, and I'm struggling to find the right approach for handling validation errors with Turbo.

I'm wrapping the form in a `turbo-frame` tag so that I can gracefully hide the modal on a successful 200 response rather than letting the redirect swap out out the body. I have a Stimulus controller that hides my modal if the form receives a successful 200 response from the `turbo:submit-end` event. This works great as long as the response is a 200 without validation errors.

But when the form response comes back with validation errors and `unprocessable_entity` status, my new `turbo
-frame` tag with form validation errors is not swapped with the old form `turbo-frame`. Of course, if I send back a 200 status it works, but in that case, my stimulus controller detects a successful response and hides the modal.

What would be a more sound approach for handling form error validation with Turbo from within a modal?

**Comment by seanpdoyle** [comment]
Does the template you're rendering as part of the `unprocessable_entity` response include a `<turbo-frame>` element with an `[id]` attribute that matches the one that contains the `<form>` element?

**Comment by culov** [comment]
> Does the template you're rendering as part of the `unprocessable_entity` response include a `<turbo-frame>` element with an `[id]` attribute that matches the one that contains the `<form>` element?

Yes, they both `<turbo-frame>` tags use the same id.

**Comment by JulianFeinauer** [comment]
@culov I can only comment here from a Django perspective. I have a similar setup (Modal triggered by a Stimulus controller). Django returns a 200 on Validation Errors so I want my frame replaced by the response (the returned Form with errors). In case of a successful submission I get a 303 from Django (which I catch in the `turbo:submit-end` as well) and close my modal then as well (or perform a _global_ redirect with `Turbo.visit()`).

Wouldnt something like that work? But I know that Rails handles the responses to Form submissions quite different...
