### ISSUE TITLE
Is there a better way to intercept fetch request for a turbo-frame with src set, than a dynamic import?

### ISSUE THREAD

**Issue by helhum** [hotwired/turbo#823]
In my application, I need to intercept and add additional headers to the fetch request Turbo performs.
However, this did not work with the fetch request performed when initializing `turbo-frame` elements with `src` attribute.

I currently changed my own module from:

```js
import * as Turbo from "@hotwired/turbo"
registerTurboEventListeners();
```

to:

```js
registerTurboEventListeners();
import('@hotwired/turbo').then(Turbo => {
// ...
});
```

So I basically had to dynamically importing Turbo. While this works, I'm wondering, if there is a better way to achieve the same.

Thanks!

**Comment by brunoprietog** [comment]
Hi @helhum, you can use the `turbo:before-fetch-request` event to do that, [here](https://turbo.hotwired.dev/handbook/drive#pausing-requests) is an example.

**Comment by helhum** [comment]
@brunoprietog yes and no. It is only possible, when:

* Registering this event *before* importing the turbo library
* this means the event listener code must be in a separate module and this module must be imported *before* importing turbo
* one has to use a bundler, as importing natively is asynchronous and could lead to web components being executed before the event listener

What would be helpful, is if turbo would not have side effects when importing, but had api to explicitly execute those effects

**Comment by brunoprietog** [comment]
I don't understand your point. If you add an event listener, every time the event is fired you can execute the callback. Could you elaborate more on why that doesn't work with some test case please?

**Comment by helhum** [comment]
My point is: Events are fired once the custom elements are registered. The custom elements are registered once the turbo module is imported (as side effect of the import)

The following does therefore **not** work:

```js
// This import registers the turbo-frame custom element. 
// If there are turbo-frame element on the html page that, have a src attribute set, 
// a fetch request is performed events are fired,
// but no event listener is registered yet
import * as Turbo from '@hotwired/turbo'

// The event listener is only called for any subsequent fetch request performed by turbo frames
document.addEventListener('turbo:before-fetch-request', async (event) => {
    console.log('turbo:before-fetch-request');
})
```

This is my current workaround:

```js
import './turbo-listeners.js'
// Listeners MUST be imported first to be able to react to custom elements
// already firing events on init
import * as Turbo from '@hotwired/turbo'
```

This however depends on execution order and therefore usage of a bundler and assuming the bundler transpiles the code with respecting the order of imports


This is what I would like it to work:

```js
// Importing the module, does not run any side effects
import * as Turbo from '@hotwired/turbo'

document.addEventListener('turbo:before-fetch-request', async (event) => {
    console.log('turbo:before-fetch-request');
})

// Whatever the method is called, does not matter, but this method will execute side effects (like registering the custom elements)
Turbo.start();

```

**Comment by helhum** [comment]
@brunoprietog should I open a new ticket or create a PR that implements the above? The title of the issue is outdated, as my current workaround is ordered imports...
