### ISSUE TITLE
data-turbo-method="delete" does not maintain data-target nor dispatch turbo:clik

### ISSUE THREAD

**Issue by wljgo** [hotwired/turbo#824]
the dynamic change of a link in a form does non hold the target attribute:

`<a data-turbo-method="delete" data-dummy-target="link" data-action="turbo:click->dummyl#captureClick" class="btn btn-danger px-3" href="/article/1">delete</a>`

become:

`<form data-turbo=\"true\" action=\"http://127.0.0.1:3000/article/1\" method=\"delete\" data-turbo-frame=\"modal\" aria-busy=\"true\" hidden=\"\"></form>`

moreover the  event **turbo:clik is** not dispatched by the form, i think this is by design but here in origin was intended to be a link so to me click should be dispatched.
Thanks

**Comment by brunoprietog** [comment]
Hi @wljgo, further enhancements to `data-turbo-method` are not planned. I suggest converting this to a native browser form element with a submit button.
