### ISSUE TITLE
turbo isn't working with adsense

### ISSUE THREAD

**Issue by eladmarg** [hotwired/turbo#834]
I didn't find the root cause for this issue, but if adsense on page, links aren't working with turbo.
(every link will trigger full page reload)

this start happen after 7.1 version (on 7.1 works ok, on 7.2-beta-1 or higher the problem exists).

if adsense isn't presenting, everything works as expected.

**Comment by eladmarg** [comment]
update - found the issue, the function doesNotTargetIFrame(anchor)
is getting as parameter empty string (because the link target is empty)
this cause the selector to get all iframes in, and then it's not handled by turbo.

**Comment by eladmarg** [comment]
the fix is simple,
just add this as another check. 
if someone can create a PR, it would be great.

function doesNotTargetIFrame(anchor: HTMLAnchorElement): boolean {
    if (anchor.target === "")
        return true;

**Comment by seanpdoyle** [comment]
@eladmarg thank you for opening this issue.

Making an implementation change seems straightforward, but making that change without a test case wouldn't prevent future changes to re-introduce a regression. 

Could you share some more information like an error stack trace or a [JSFiddle](https://jsfiddle.net) with a minimum snippet of code to reproduce the behavior so that we can also include test coverage in the fix?

**Comment by eladmarg** [comment]
sure, 
very simple,
when you queryselector by empty name, you can get iframes if exists on the page (document.getElementsByTagName(""))

so simply add to the page an iframe of google ads

this for instance:

`<div id="google_ads_iframe_/4744526/ads_cat_top_desktop_0__container__" style="border: 0pt none; display: inline-block; width: 728px; height: 90px;"><iframe frameborder="0" src="https://5642dc6e614dd1d0e97dec6070467bae.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html" id="google_ads_iframe_/4744526/ads_cat_top_desktop_0" title="3rd party ad content" name="" scrolling="no" marginwidth="0" marginheight="0" width="728" height="90" data-is-safeframe="true" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" role="region" aria-label="Advertisement" tabindex="0" data-google-container-id="1" style="border: 0px; vertical-align: bottom;" data-load-complete="true"></iframe></div>`

then you'll see that its get selected when you click on another anchor element.

**Comment by seanpdoyle** [comment]
Thank you for sharing that snippet!

I've extracted the `<iframe>` element and broken it across several lines to make reading it easier:

```html
<iframe
  frameborder="0" 
  src="https://5642dc6e614dd1d0e97dec6070467bae.safeframe.googlesyndication.com/safeframe/1-0-40/html/container.html"
  id="google_ads_iframe_/4744526/ads_cat_top_desktop_0"
  title="3rd party ad content"
  name=""
  scrolling="no"
  marginwidth="0"
  marginheight="0"
  width="728" height="90"
  data-is-safeframe="true"
  sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation"
  role="region"
  aria-label="Advertisement"
  tabindex="0"
  data-google-container-id="1"
  style="border: 0px; vertical-align: bottom;"
  data-load-complete="true"></iframe>
```

Note the **name=""** attribute. The presence of that attribute is at the root of the issue.

I'll incorporate some tests into a pull request.

**Comment by eladmarg** [comment]
fixed.
