### ISSUE TITLE
Unable to reload a page on a redirect

### ISSUE THREAD

**Issue by agentkatie** [hotwired/turbo#845]
We recently faced a problem while trying to reload a page on a redirect. A payment provider we use injects loads of scripts and iframes onto the page that we would like to clear out on a redirect after a form submission by reloading the page, but we’ve had no luck in finding a straightforward way to do this.

We tried a solution of attaching a Stimulus action to the turbo:submit-end event that set the `window.location.href` of the redirect, however this appeared to redirect first with Turbo and then reload the page. The workaround we’ve implemented for now uses a Turbo Stream that connects a Stimulus controller to handle the reload like so: 

```
<%= turbo_stream.append_all("body") do %>
  <%= tag.template data: { controller: "redirect", redirect_href_value: @redirect_to } %>
<% end %>
```

```
export default class RedirectController extends Controller {
  static values = {
    href: String,
  };

  connect() {
    window.location.href = this.hrefValue;
  }
}
```

Is there a better way to do this? Should this be something added to Turbo to handle via a header or query param to force Turbo Drive to reload the page on a redirect?

**Comment by chrisgrande** [comment]
I use a Stimulus controller, similar to your example.

However this can now be done using customs Turbo Stream actions added in versions 7.2. These can also be used for all sorts of things. 

More information can be found in this post: https://marcoroth.dev/posts/guide-to-custom-turbo-stream-actions

Redirect example in turbo_power:
https://github.com/marcoroth/turbo_power/blob/main/src/actions/turbo.ts

**Comment by agentkatie** [comment]
> However this can now be done using customs Turbo Stream actions added in versions 7.2.

Thank you for your reply @chrisgrande. We were definitely considering using a custom Turbo Stream action for this, so we'll likely revisit the idea.

**Comment by brunoprietog** [comment]
Hello, you can use the meta tag `<meta name="turbo-visit-control" content="reload">` to do this. [Here](https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload) is more information.
