### ISSUE TITLE
Doesn't load the images or any div which contain AOS animation.

### ISSUE THREAD

**Issue by Muhammad-Sarfaraz** [hotwired/turbo#846]
Using turbo with AOS ("https://github.com/michalsnik/aos") is causes images or div doesn't load. Only blank shadow div is loaded.
Is turbo doesn't support animation on scroll ? or it is just a wired behavioud of turbo?

**Comment by marcoroth** [comment]
Hey @Muhammad-Sarfaraz, do you have an example that we can look at?

**Comment by Muhammad-Sarfaraz** [comment]
Yeah I have, I will attach it tomorrow.
