### ISSUE TITLE
Missing Turbo-Frame header when submitting a form

### ISSUE THREAD

**Issue by Intrepidd** [hotwired/turbo#86]
When clicking links while inside a frame, the `Turbo-Frame` header will be set.

This helps the backend to know this is a frame request and for instance to not render layout.

When submitting a form, this header is not set, I think it should be. 

Example : To respect progressive enhancement, we should be able to return a frame when the request comes from turbo, but perform a redirection when not.

**Comment by kaspth** [comment]
Adding the `Turbo-Frame` header on non-frame requests would blur the concept of frames.

For invalid forms, we recommend responding with the 422 HTTP status and the form contents will be replaced. See https://github.com/hotwired/turbo/pull/39. You can also respond with turbo streams.

**Comment by Intrepidd** [comment]
Sorry if it wasn't clear, I was advocating to set the `Turbo-Frame` header only when a form within a frame is being submitted

**Comment by kaspth** [comment]
Ah! Yeah, that should be set, and if not, it's a bug.

**Comment by weaverryan** [comment]
Hi!

If this is a bug, then I can also confirm it :). Inside the a frame, when I click a link, I can see the `Turbo-Frame` header. When I submit a form right below that link (inside the same frame), the `Turbo-Frame` header appears to be missing.

Cheers!

**Comment by tleish** [comment]
In the following example, only the first GET button will include a request header with `Turbo-Frame`, the other 2 do not include it in the header.

```erb
<%= turbo_frame_tag 'user_frame' do %>
  <%= button_to('Edit User', '/users/1', method: "get") %>    <!-- ADDS header['Turbo-Frame'] --> 
  <%= button_to('Save',      '/users/1', method: "post") %>   <!-- NO header['Turbo-Frame'] --> 
  <%= button_to('Delete',    '/users/1', method: "delete") %> <!-- NO header['Turbo-Frame'] --> 
<% end %>
```
Is this intended or a bug?

using: `@hotwired/turbo 7.0.0-beta.3`

**Comment by danjac** [comment]
I can confirm this issue (using Django): 

1. Request inside turbo frame using a link: Turbo-Frame header present.
2. Request inside turbo frame using a form submission: Turbo-Frame header not present.

**Comment by tleish** [comment]
If you prefer an alternative approach than PR https://github.com/hotwired/turbo/pull/110 I'm happy to work on it.

If not, does anyone have a suggestion for alternatives on how to handle form submissions when javascript is enabled (using turbo-frames) and javascript is not enabled?  I could always redirect to the same page, but in many cases the redirect after submission is different.

**Comment by oleksandr** [comment]
Run into the same issue today (using hotwire with Golang backend). Looks like the suggested fix is still hanging :-\

**Comment by seanpdoyle** [comment]
As part of https://github.com/hotwired/turbo/pull/142, we changed how the headers are constructed from a merge operation to [a direct mutation](https://github.com/hotwired/turbo/pull/142/files#diff-8f44fafd854f6f716d51a2b05b5689266a9b66e0b1ad9d68570bd4e8cefd0a47). Combined with https://github.com/hotwired/turbo/pull/127, all form submissions (GET or POST, inside a frame or referencing one from the outside) should result in a requests with the Turbo-Frame header.

That behavior was shipped as part of https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.4.

@Intrepidd @danjac @oleksandr are you still experiencing this issue?

**Comment by jmfederico** [comment]
I am still experiencing the issue in beta-4.

GET (links) send the header.
POST (form submissions) do not.

**Comment by tleish** [comment]
@seanpdoyle — created this [JSFiddle](https://jsfiddle.net/t4eqhbdL/) to show the headers being sent.  Click any of the buttons and see the headers sent through fetch below the buttons.  Turbo only adds turbo-frame to header on a GET.

**Comment by tleish** [comment]
One other item to note, should the GET request also include `text/vnd.turbo-stream.html` in the accept header (which it currently does not)?

**Comment by seanpdoyle** [comment]
@tleish that's intentional: see https://github.com/hotwired/turbo/pull/52 and https://github.com/hotwired/turbo/pull/127.

**Comment by tleish** [comment]
> @tleish that's intentional: see #52 and #127.

Ah.  I did not realize this was intentional.  I also didn't realize I could not use turbo-stream with a GET method.

**Comment by danjac** [comment]
@seanpdoyle using beta 4. Turbo header is *not* sent with POST request.

**Comment by Intrepidd** [comment]
I confirm as well, header is still not sent for my POST use-case
