### ISSUE TITLE
`<turbo-stream-source>` does not work as permanent 

### ISSUE THREAD

**Issue by morki** [hotwired/turbo#868]
I need to have this element permanent on all pages streaming updates to user, but on every navigation, it reconnects.
Attribute `data-turbo-permanent` is respected, but custom elements call their `connected` and `disconnected` callbacks even on node moves.

I prepared working implementation for anyone interested, which waits to next animation frame to check if it was just moved. 

```typescript
import { StreamSource } from "../core/types"
import { connectStreamSource, disconnectStreamSource } from "../index"

export class StreamSourceElement extends HTMLElement {
  streamSource: StreamSource | null = null

  connectedCallback() {
    if (!this.streamSource) {
      this.streamSource = this.src.match(/^ws{1,2}:/) ? new WebSocket(this.src) : new EventSource(this.src)
      connectStreamSource(this.streamSource)
    }
  }

  disconnectedCallback() {
    requestAnimationFrame(() => {
      if (this.streamSource && !this.isConnected) {
        disconnectStreamSource(this.streamSource)
        this.streamSource = null
      }
  }

  get src(): string {
    return this.getAttribute("src") || ""
  }
}
```

**Comment by seanpdoyle** [comment]
> but on every navigation, it reconnects.

When Turbo carries permanent elements forwards and backwards through Visit-driven navigations, the elements are disconnected from their previous document and connected to the new document. 

Are you able to change your code that depends on the element's callbacks to be [idempotent](https://turbo.hotwired.dev/handbook/building#making-transformations-idempotent)?

**Comment by seanpdoyle** [comment]
@morki could you share some more information about your use case, including some of the HTML and JavaScript code?

What behavior are you trying to achieve? In what way does rendering the `<turbo-stream-source>` with `[data-turbo-permanent]` prevent you from the outcome you expect? What are the issues you're experiencing that stem from the `connect` and `disconnect` callbacks being called more than once?
