### ISSUE TITLE
`hotwire-example-pagination` not works with `7.2.5`

### ISSUE THREAD

**Issue by seb-jean** [hotwired/turbo#873]
Hi,

I updated Turbo from `7.2.4` to `7.2.5` and the [hotwire-example-pagination](https://github.com/thoughtbot/hotwire-example-template/tree/hotwire-example-pagination) demo no longer works:
The url is modified in the browser’s path.

**Comment by seb-jean** [comment]
If I remove the line https://github.com/hotwired/turbo/blob/main/src/core/frames/frame_controller.ts#L180, it works fine.
Seems it's PR related https://github.com/hotwired/turbo/pull/790

**Comment by seanpdoyle** [comment]
@seb-jean thank you for opening this issue!

> The url is modified in the browser’s path.

Does the new URL reflect the path of the lazily-loaded `<turbo-frame>` element? Is that element rendered with a `[data-turbo-action]` attribute? From what I remember, that sounds like it's working as intended.

If you're able, could you try to experiment with the changes made in https://github.com/hotwired/turbo/pull/430? That PR re-arranges some of the frame promotion logic, and might help resolve the underlying issue.

**Comment by seb-jean** [comment]
I put the HTML code if it can help for the issue:
```html
<turbo-frame id="notifications-page-1" target="_top">
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <div class="item">[...]</div>
   <turbo-frame id="notifications-page-2" class="group block py-6" data-turbo-action="replace" src="/notifications?page=2" loading="lazy" data-controller="element" data-action="turbo:frame-render->element#replaceWithChildren">
      <a class="hidden group-last-of-type:flex justify-center pointer-events-none" tabindex="-1" aria-hidden="true" rel="next" href="/notifications?page=2">
         <svg>[...]</svg>
      </a>
   </turbo-frame>
</turbo-frame>
```

**Comment by seanpdoyle** [comment]
```html
<turbo-frame id="notifications-page-2" class="group block py-6" data-turbo-action="replace" ...>
```

Rendering that `<turbo-frame>` element with `[data-turbo-action="replace"]` means that it'll update the URL when it navigates. If you don't want that behavior, you can remove that attribute.

The intention behind that example code is to update the URL's `?page=` query parameter as you infinitely scroll so that if you were to refresh, you'd load the same page you were just looking at.

**Comment by seb-jean** [comment]
Ok, it works perfectly.

**Comment by seb-jean** [comment]
Thx @seanpdoyle
