### ISSUE TITLE
Stream append/prepend can produce duplicates if the template element is a form

### ISSUE THREAD

**Issue by ethancrawford** [hotwired/turbo#879]
Hi! So, I noticed that if you try to append or prepend a form which contains a child form control with the name 'id',  (such as in this minimal-ish example): 
```
<form id="myform">
  <input name="id">
</form>
```
...then the 'old' form is not removed when the new one is appended/prepended.
(Since `myform.id` will then refer to the named child control, not the form's id attribute, and the id match created previously to remove duplicates fails).

**Comment by seanpdoyle** [comment]
Thank you for opening this issue. 

I've opened https://github.com/hotwired/turbo/pull/1037 to deal with a similar collision with regard to the `[action]` attribute.
