### ISSUE TITLE
Turbo Stream Custom Actions documentation seems to be incorrect.

### ISSUE THREAD

**Issue by bennadel** [hotwired/turbo#881]
I'm trying to follow the documentation for creating a custom Turbo Stream action, ala:

https://turbo.hotwired.dev/handbook/streams#custom-actions

And, I'm guessing it's just out of date. It currently gives this as the example:

```javascript
import { TurboStreamActions } from "@hotwired/turbo"

// <turbo-stream action="log" message="Hello, world"></turbo-stream>
//
TurboStreamActions.log = function (streamElement) {
  console.log(streamElement.getAttribute("message"))
}
```

However, it looks like `TurboStreamActions` is `undefined`. But, from some `debugger` usage, I see that there is `Turbo.StreamActions`. That said, if I try to register an action on `Turbo.StreamActions`, the callback that is invoked has no `streamElement` argument. When I look at the SRC for the other handlers, I can also see that _none of them_ currently receive any arguments:

https://github.com/hotwired/turbo/blob/1e78f3b1ef4e5263c4d6fd2003ae8298e27b3b3c/src/core/streams/stream_actions.ts

So, I just think there is a disconnect between the docs and the current code.

**Comment by bennadel** [comment]
After some further debugging, it looks like the `this` binding inside the callback is the `streamElement` equivalent.

**Comment by marcoroth** [comment]
Hey @bennadel, yes you are right! `TurboStreamActions` is the TypeScript type and not the actual object which holds the stream actions. If you import `StreamActions` it should work as expected:

```js
import { StreamActions } from "@hotwired/turbo"
 
StreamActions.log = function() {
    console.log(this.getAttribute("message"))
}
```

**Comment by bennadel** [comment]
@marcoroth ah, ok cool - yeah, I'm just authoring plain JavaScript (and bundling with Parcel). Thanks for the insight!

**Comment by marcoroth** [comment]
Looks like the changes are now live in the docs 🙌🏼

**Comment by bennadel** [comment]
You guys are fast, thank you!

**Comment by bennadel** [comment]
You guys are fast, thank you!

**Comment by mattpolito** [comment]
@bennadel Should this issue be closed?

**Comment by AAlvarez90** [comment]
This is the way it works now:
`import { Turbo } from "@hotwired/turbo-rails"`
`Turbo.StreamActions.log = function () {`

**Comment by searls** [comment]
It would be really great if docs snippets like the above were included for the docsite, given the percentage of users using Turbo in conjunction with Rails. It was only because of this issue I realized this was how I needed to access `StreamActions` because I was using `@hotwire/turbo-rails`
