### ISSUE TITLE
Turbo should ignore `<form method='dialog'>` and `formmethod="dialog"` buttons

### ISSUE THREAD

**Issue by leevigraham** [hotwired/turbo#889]
From MDN:

> [`<form>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) elements can close a `<dialog>` if they have the attribute `method="dialog"` or if the button used to submit the form has` formmethod="dialog"` set. In this case, the state of the form controls are saved, not submitted, the `<dialog>` closes, and the [returnValue](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/returnValue) property gets set to the value of the button that was used to save the form's state.

Turbo intercepts the `submit` event and sends a `fetch`. This is not desirable behaviour inside a `dialog` which is already controlled by javascript.

**Comment by seanpdoyle** [comment]
@leevigraham thank you for opening this issue!

Could you share some sample code that demonstrates this behavior? The [FormSubmitObserver](https://github.com/hotwired/turbo/blob/main/src/observers/form_submit_observer.ts#L54-L58) incorporates a guard clause that intends to prevent `form[method="dialog"]` or `button[formmethod="dialog"]` from being handled by Turbo. It was added in version `7.2.0`. 

Which version of Turbo does your application depend on?

**Comment by leevigraham** [comment]
Closing this… not sure what I did but it was 100% user error… probably forgot to add `method=dialog` to the form the first time round
