### ISSUE TITLE
Webpack import error

### ISSUE THREAD

**Issue by lu4p** [hotwired/turbo#89]
With webpack this works:
```js
const Turbo = require("@hotwired/turbo")

Turbo.connectStreamSource(new WebSocket("ws://" + document.location.host + "/recieve"));
```

While the [suggested](https://turbo.hotwire.dev/handbook/installing#as-an-npm-package) import from the docs doesn't:
```js
import Turbo from "@hotwired/turbo"

Turbo.connectStreamSource(new WebSocket("ws://" + document.location.host + "/recieve"));
```

It prints this warning in webpack:
```
WARNING in ./js/index.js 7:0-25
export 'default' (imported as 'Turbo') was not found in '@hotwired/turbo' (possible exports: clearCache, connectStreamSource, disconnectStreamSource, navigator, registerAdapter, renderStreamMessage, setProgressBarDelay, start, visit)
```
Which leads to this error in the browser console:
```
Uncaught TypeError: _hotwired_turbo__WEBPACK_IMPORTED_MODULE_1__.default is undefined
```

**Comment by boardfish** [comment]
I'm experiencing this too. I also can't reach it with `import { Turbo } from "@hotwired/turbo"`.

Using `webpack@4.43.0`.

**Comment by kzkn** [comment]
How's this?
https://github.com/hotwired/turbo-rails/blob/main/app/javascript/turbo/index.js#L3

**Comment by lu4p** [comment]
That works

**Comment by weaverryan** [comment]
```
import * as Turbo from '@hotwired/turbo';
```

That also works for me. But, is that the intended way for it to work or is this a bug that slipped in?

Thanks!

**Comment by marie-maxime** [comment]
Having the same issue using parcel-bundler@1.12.4 in dev mode. Using this fixes it.

`import { Turbo } from "@hotwired/turbo"`
