### ISSUE TITLE
make data-turbo-submits-with attribute work with links that have data-turbo-method (feature-request)

### ISSUE THREAD

**Issue by krebil** [hotwired/turbo#896]
The [**data-turbo-submits-with**](https://turbo.hotwired.dev/reference/attributes) attribute is useful for showing simple text when doing long-running posts. It would be helpful if this worked for Anchor tags with the **data-turbo-method** attribute set

**Comment by seanpdoyle** [comment]
I don't speak for the maintainers when I say this, but [I'm personally opposed to expanding support for `<a>`-to-`<form>` element](https://github.com/hotwired/turbo/pull/856#issuecomment-1409538549).

In the short-term, while you wait for any potential development, have you tried to explore an alternative solution that replaces your [unsafe](https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP) `<a data-turbo-method="...">` elements with `<form>` element counterparts?

If you're using Rails, an `<a>` element like:

```html
<a data-turbo-method="put" href="/articles/1">...</a>
```

could be replaced by a `<form>` element like:

```html
<form method="post" action="/articles/1">
  <input type="hidden" name="_method" value="put">
  <button>...</button>
</form>
```

**Comment by krebil** [comment]
I agree that a link such as this could be implemented as a form. 
I also agree that anchors to forms is a weird feature. I do think that as long as it's supported it should be close to feature parity with the forms implementation though

**Comment by brunoprietog** [comment]
Agree with @seanpdoyle, closing this
