### ISSUE TITLE
Refresh a Turbo Frame every second

### ISSUE THREAD

**Issue by treefall-source** [hotwired/turbo#900]
I'm sure this is a noob problem, but I would appreciate some guidance.

I have two Turbo Frames that I currently efresh every second. I currently use this javascript to call /tasks/refresh_frames:

```
<script>
  window.addEventListener("load", refreshFocus);
  setInterval(refreshFocus, 1000);
  
  function refreshFocus() {
    document.getElementById("COL1_HEADING").src = '/tasks/refresh_frames'
  }
</script>
```

/tasks/frames is a Flask route, which runs:

```
    return turbo.stream([
        turbo.update(render_template('/blocks/_focus.html', focus_task = current_focus_task), target="COL1_FOCUS_BOX"),
        turbo.update(render_template('/blocks/_heading.html'), target="COL2_HEADING"),
        turbo.update(render_template('/blocks/_tasks.html'), target="COL2_TASKS_LIST"),
        turbo.update(render_template('/blocks/_today.html'), target="COL1_TASKS_LIST"),
        turbo.update(render_template('/blocks/_buttons.html', inbox_button_badge = len(task_filter('#inbox'))), target="COL2_BUTTONS"),
        ])
```

The HTML contains a basic request code which calls on a JSON api to add data to the page, hence the need for regular updates. 

This works generally, but I now want to only update the page when there is a change to the HTML/JSON and it's getting extremely complicated. I'm sure there must be an easier way to do this.

Does anyone have any recommendations, please?

Thanks in advance for any help you can provide.

**Comment by guillehorno** [comment]
Hi @treefall-source , there's a great official forum in https://discuss.hotwired.dev/, where you can ask questions and get help from the community. I'd recommend posting your problem there instead of here in the issues.
