### ISSUE TITLE
No compiled version?

### ISSUE THREAD

**Issue by tebeso** [hotwired/turbo#914]
https://turbo.hotwired.dev/handbook/installing states that there is a compiled version which i can use in a <script> tag. I dont find it here. Using npm also doesnt work in Laravel 10 (which is the reason i wanted to try out the compiled version)

"Failed to resolve entry for package "@hotwired/turbo". The package may have incorrect main/module/exports specified in its package.json"

**Comment by dhh** [comment]
You can use any JS CDN. Like this: https://www.jsdelivr.com/package/npm/@hotwired/turbo
