### ISSUE TITLE
Add new event turbo:after-stream-render

### ISSUE THREAD

**Issue by lu4p** [hotwired/turbo#92]
Similar to the `turbo:before-stream-render` event, it would be useful to fire an event after rendering a Turbo Stream page update

**Comment by sstephenson** [comment]
We don't plan on adding an after-stream-render event: https://discuss.hotwire.dev/t/event-to-know-a-turbo-stream-has-been-rendered/1554/6

**Comment by woto** [comment]
It helped me https://github.com/hotwired/turbo/pull/20#issue-773325276. Didn't found any drawbacks yet.

**Comment by modusss** [comment]
The big problem in my case is that after turbo_stream is loaded, the javacript library input_mask doesn't work anymore because the content that changes is the form itself. 

They brought to us a solution with Stimulus and "connect()" method b but it does not trigger after turbo stream is loaded. 

There is nothing that triggers after page changes.

**Comment by jtoy** [comment]
ran into similar issue  and stimulus is not the answer for me.

**Comment by searls** [comment]
Agree with @leewa, this would be of tremendous use to me. 

I have this situation:

* wrapping div (with a Stimulus controller connected)
    * a `select` input to change modes (where `change` triggers an action that makes a `responseKind: 'turbo-stream'` request using `'@rails/request.js'`
    * a `fieldset` containing some fields (that gets re-rendered by that turbo-stream update)
    * a `input[type=hidden]` that contains a JSON-serialized dump of the above fieldset (which is updated any time the user changes anything)

The stimulus controller just needs to know when that `fieldset` has been re-rendered so it can re-serialize its contents into that `input[type=hidden]`. Without this event, I'm not left with a lot of awesome options. Manual `MutationObserver`? Reaching upward to the wrapping form's `submit` event? This event would be great to have

**Comment by ricvillagrana** [comment]
I did this and worked perfectly for what I needed. If you need to update the event listeners on a controller, you can do this:

```javascript
export default class extends Controller {
  static targets = ['button'];

  connect() {
    this.addEventListeners();

    const observer = new MutationObserver(() => {
      this.addEventListeners();
    });

    observer.observe(this.element, { childList: true });
  }

  addEventListeners() {
    this.buttonTarget.addEventListener('click' () => { /* Do something */ })
  }
}
```

**Comment by tomashomey** [comment]
here is a solution: https://nts.strzibny.name/rails-turbo-after-stream-render/

```
// application.js
const afterRenderEvent = new Event("turbo:after-stream-render");
addEventListener("turbo:before-stream-render", (event) => {
  const originalRender = event.detail.render

  event.detail.render = function (streamElement) {
    originalRender(streamElement)
    document.dispatchEvent(afterRenderEvent);
  }
})
```
