### ISSUE TITLE
Turbo frame contains busy and complete when navigating history

### ISSUE THREAD

**Issue by trsteel88** [hotwired/turbo#927]
I've noticed that when using 7.3.0, my <turbo-frame> which I navigate inside using data-turbo-action="advance" incorrectly shows the busy attribute when going back in history.

e.g, initial load is a regular frame, navigate (css displays a loading style due to turbo-frame[busy], frame loads (all good so far). Navigate again, looks fine. Now go back and the frame is stuck on busy.

Is anyone else experiencing this issue?

**Comment by trsteel88** [comment]
Sorry, normal navigation is actually fine. The issue occurs when I have a form with an action=GET

```
<form method="get" action="/my-path" data-turbo-frame="my-frame">
```

**Comment by sascha-egerer** [comment]
@dhh Any reason why the issue has been closed? I've got the same problem that the history back stuff breaks when using a form with method GET.
