### ISSUE TITLE
Chrome crashes when a turbo frame response contains <form name="location">

### ISSUE THREAD

**Issue by janklan** [hotwired/turbo#931]
The title is an accurate description of the problem I randomly found: if a Turbo Frame loaded by injecting an URL into a frame's src value contains `<form name="location">`, Chrome crashes.

Here is the reproducer code:

```html
<html>
  <head>
    <script type="module">
      import hotwiredturbo from "https://cdn.jsdelivr.net/npm/@hotwired/turbo@7.3.0/+esm";
    </script>
  </head>
  <body>
    <button
      onclick="document.getElementById('frame').src = window.location.href"
    >
      Click this button to crash your Chrome/Edge.
    </button>
    <turbo-frame id="frame">
      <!-- change the word "location" to anything else and the crash will no longer occur -->
      <form name="location"></form>
    </turbo-frame>
  </body>
</html>
```

See it live at https://janklan.github.io/, or check out my own experience:

![2023-06-09 15 36 19](https://github.com/hotwired/turbo/assets/5463371/e5932cc2-2994-4a50-95b4-86e3e72a897c)

I'm using Chrome `Version 114.0.5735.106 (Official Build) (arm64)`. I heard reports that the same occurs on Windows, but I have no version information. 

The `document.getElementById('frame').src = window.location.href` is there just for legibility. Any URL with `<turbo-frame id="frame"><form name="location"></form></turbo-frame>` will behave the same.

**Comment by rik** [comment]
I'm not a Turbo maintainer but I believe this should be a bug filed for Chrome, not Turbo.

**Comment by janklan** [comment]
Look, probably both, but I started here.

Maybe Turbo people can work out more details than I could on what could be wrong.

**Comment by janklan** [comment]
For anyone interested, the Chromium bug report is here https://bugs.chromium.org/p/chromium/issues/detail?id=1454272

**Comment by rik** [comment]
Seems like a protected bug so not publicly visible at the moment.

**Comment by janklan** [comment]
> Seems like a protected bug so not publicly visible at the moment.

Yeah, I can't do anything about that. Let's hope it changes when someone attends it, confirms it's not a security issue, and makes it public.

**Comment by dhh** [comment]
Going to leave this for the Chrome team.

**Comment by oleg-andreyev** [comment]
Just for the note:
- Today faced same issue with Chromium based browsers >= 124
- Opera which is as of today is 123, works.
