### ISSUE TITLE
Documentation: Navigating with forms

### ISSUE THREAD

**Issue by alexdelgado** [hotwired/turbo#944]
I've read the documentation and walked through the code and I'm still not sure how to make a form submission update the URL.

On submit, my form POSTS to `next_step` which 303 redirects to `step` which returns a `turbo_stream.replace`. The frame is updating exactly as it should, but the URL never updates and it appears to me as though visit/session is never called. 

Can anyone provide a working example or help me figure out what's wrong?

```
<form class="form" action="/steps" accept-charset="UTF-8" method="post">
  <turbo-frame id="wizard">
    <input type="hidden" name="step" value="1">
    <input type="hidden" name="step_name" value="one">
  </turbo-frame>
  <button type="submit">Continue</button>
</form>
```

I'm using Rails @ 7.0.4.3 and Turbo @ 7.3.0.

**Comment by alexdelgado** [comment]
@seanpdoyle - I saw your PR on this and tried to work through the logic, but I can't figure this out. The frustrating part is that everything except the URL update works..

thanks in advance!

**Comment by seanpdoyle** [comment]
@alexdelgado The example code you've shared is combining three distinct and potentially unrelated facets of Turbo.

When the `<form>` element is submitted, are you hoping to:

* drive the `<turbo-frame id="wizard">` element
* drive the entire page
* update a fragment of the page with a `<turbo-stream action="replace">` element

My recommendation is to choose one. Driving the `<turbo-frame id="wizard">` can also change the URL if the `<turbo-frame>` element is rendered with [data-turbo-action](https://turbo.hotwired.dev/handbook/frames#promoting-a-frame-navigation-to-a-page-visit) attribute.
