### ISSUE TITLE
Script only execute when page reload

### ISSUE THREAD

**Issue by rizki5411** [hotwired/turbo#945]
![image](https://github.com/hotwired/turbo/assets/31713769/5397d56a-1915-4b37-a09f-296680f6cf78)

Script with name `soft-ui-dashboard-tailwind.js` only work in first load, after click other page this script not working, must reload page again.

Please solution, thanks.

**Comment by septianmalela** [comment]
https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload
see documentation

![image](https://github.com/hotwired/turbo/assets/46917044/ec2ffabd-661d-46d0-9df8-562e1aa98fe9)

**Comment by rizki5411** [comment]
Makasih mas e

> https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload see documentation, maybe can solved you issue
> 
> ![image](https://user-images.githubusercontent.com/46917044/253461717-ec2ffabd-661d-46d0-9df8-562e1aa98fe9.png)

**Comment by rizki5411** [comment]
> https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload see documentation, maybe can solved you issue
> 
> ![image](https://user-images.githubusercontent.com/46917044/253461717-ec2ffabd-661d-46d0-9df8-562e1aa98fe9.png)

But, with this solution every click menu page always reload.

**Comment by seanpdoyle** [comment]
@rizki5411 Turbo Drive relies on using a [single, persistent process](https://turbo.hotwired.dev/handbook/introduction#turbo-drive%3A-navigate-within-a-persistent-process) when navigating pages. The `<script>` element will only be executed a single time.

Therefore, the JavaScript needs to account for that single persistent process. If you're using something like [Stimulus](https://stimulus.hotwired.dev/handbook/hello-stimulus#is-this-thing-on%3F), code in a controller's `connect()` callback would execute whenever the controller's element is attached to the page (including during a Turbo Drive navigation).

If you aren't using Stimulus, you'll likely want to execute that code within a [turbo:load](https://turbo.hotwired.dev/handbook/building#working-with-script-elements) event listener:

```js
addEventListener("turbo:load", () => {
  // this code will execute whenever a Turbo Drive navigation occurs
})
```
