### ISSUE TITLE
Is there a way to make lazy Turbo Frames accept `text/vnd.turbo-stream.html`?

### ISSUE THREAD

**Issue by shepmaster** [hotwired/turbo#956]
I have a lazy Turbo Frame, roughly like this:

```html
<turbo-frame id="this-frame" src="/my/cool/url" loading="lazy" />
```

When that frame is visible, a request is made to the server. Among other things, the request headers contain:

```
Accept: text/html, application/xhtml+xml
Turbo-Frame: this-frame
```

Right now, my code looks for that `Turbo-Frame` header to decide if it should return a focused amount of data via a Turbo Stream or the whole page as straight HTML.

This *works*, but it feels weird that this part of my app looks for the `Turbo-Frame` header while other endpoints look for the `Accept` header to contain `text/vnd.turbo-stream.html`. Is there a way to add that content type to the request made by the lazy frame request?

(Originally [posted to the forum](https://discuss.hotwired.dev/t/is-there-a-way-to-make-lazy-turbo-frames-accept-text-vnd-turbo-stream-html/5229?u=shepmaster), but I figured I'd share here as there was no response there).

**Comment by sudzhaev** [comment]
It seems to be done intentionally. 
For instance in rails applications turbo is already [substituting your default layout with a smaller one](https://github.com/hotwired/turbo-rails#a-note-on-custom-layouts) by checking that exact `Turbo-Frame` header. It even has a helper function `turbo_frame_request?` available in application controllers.

However if you still need to pass turbo-stream header you can intercept fetch request initiated by turbo in your javascript code and do your thing:
```js
let turboFrame = document.getElementById("frame-id");
turboFrame.addEventListener("turbo:before-fetch-request", (event) => {
    // You may want to append extra content type here, not reassign. Depends on your needs
    event.detail.fetchOptions.headers['Accept'] = 'text/vnd.turbo-stream.html'
});
```

**Comment by brunoprietog** [comment]
This is the expected behavior, see this [comment](https://github.com/hotwired/turbo/issues/1013#issuecomment-1760098052)
