### ISSUE TITLE
Tailwind CSS classes don't apply to turbo-frame children

### ISSUE THREAD

**Issue by vkz** [hotwired/turbo#959]
Here's an example, where `space-y-*` class is present but fails to effect `turbo-frame` children elements i.e. no vertical gap is added:

<img width="313" alt="Drills" src="https://github.com/hotwired/turbo/assets/917220/a463b3a9-d4ba-4d99-ad12-1118f5781b06">

Only way to fix this is to wrap each `turbo-frame` into a `div` like so:

<img width="352" alt="Drills" src="https://github.com/hotwired/turbo/assets/917220/a6460b62-2aaf-4049-aa43-0653d84df9f9">

Is this a known issue or expected behavior?

Thank you

**Comment by domchristie** [comment]
Custom elements like `<turbo-frame>`s are inline by default. You may wish to globally style your turbo-frames as `display: block`:

```css
turbo-frame {
  display: block;
}
```

**Comment by vkz** [comment]
@domchristie yep, that fixed it. I'm guessing RoR has it right somewhere in the depths of its CSS machinery. Not using it, so ...

I can't be the first to have run into this. Probably belongs as a NB gotcha in Hotwire docs or smth. Going to close this and hope someone opens a separate one for docs change if they feel it is necessary.

Thank you for your help!
