### ISSUE TITLE
Events with the same meaning as ajax:success and ajax:error for form submission

### ISSUE THREAD

**Issue by kzkn** [hotwired/turbo#96]
I was using the remote feature of rails-ujs and stimulus to build a modal with a form.
I had written the following code to close the modal when submit succeeds, and to display an error message when it fails.

```erb
<div class="modal" data-controller="modal">
  <%= form_with url: '...', data: { controller: 'remote', action: 'ajax:success->modal#close ajax:error->remote#replace' } %>
</div>
```

```js
// modal_controller
export default class extends Controller {
  close() {
    $(this.element).modal('hide')
  }
}

// remote_controller
export default class extends Controller {
  replace(ev) {
    const { detail: [, , xhr] } = event
    this.element.outerHTML = xhr.responseText
  }
}
```

I think it would be nice to have an event to achieve the same thing with turbo.
For example, events like `turbo:submit-success`, `turbo:submit-error`.

**Comment by seanpdoyle** [comment]
There's some slight variations, but [`turbo:submit-end`](https://turbo.hotwire.dev/reference/events) could serve both purposes (either in a single combined action, or split across two):

```diff
<div class="modal" data-controller="modal">
-  <%= form_with url: '...', data: { controller: 'remote', action: 'ajax:success->modal#close ajax:error->remote#replace' } %>
+  <%= form_with url: '...', data: { controller: 'remote', action: 'turbo:submit-end->modal#close turbo:submit-end->remote#replace' } %>
</div>
```

```js
// modal_controller
export default class extends Controller {
  close(event) {
    const { detail: { success } } = event

    if (success) {
      $(this.element).modal('hide')
    }
  }
}

// remote_controller
export default class extends Controller {
  replace(event) {
    const { detail: { success } } = event
    if (!success) {
      this.element.outerHTML = xhr.responseText
    }
  }
}
```

https://github.com/hotwired/turbo/pull/40 demonstrates how you might map UJS events to Turbo events.

Not being familiar with your codebase and application, I might be off base, but it seems like using a [`<turbo-frame>`](https://turbo.hotwire.dev/reference/frames#frame-with-overwritten-navigation-targets) in place of this JavaScript might be possible as well.

**Comment by kzkn** [comment]
@seanpdoyle 
That code does indeed work. In fact, I am adopting that method now :smile: 
I also checked that the `remote#replace` part in the example is replaced by an HTML response using `<turbo-frame>` and `status: 422`.

However, I don't think we should include an if statement in `modal#close` to check if the submission is successful or not.
For example, if I want to display a notification message only when a submit is successful, I must include the same if statement there as well.

```erb
<div class="modal" data-controller="modal">
  <%= form_with url: '...', data: { controller: 'notification', action: 'turbo:submit-end->modal#close turbo:submit-end->notification#show', notification_message_value: 'Succeeded' } %>
</div>
```

```js
// notification_controller.js
export default class extends Controller {
  static values = { message: String }

  show(event) {
    const { detail: { success } } = event
    if (success) {
      toastr.success(this.messageValue) // show notification message
    }
  }
}
```

To keep the stimulus controller simple and reusable, I think it would be helpful to have a dedicated event to write this common conditional branch declaratively.

**Comment by matthee** [comment]
I agree with @kzkn. Checking in the modal controller if the form submission was successful feels like a violation of separation of concerns.

Why not introduce two additional events `turbo:submit-success` and `turbo:submit-error`? We could use these events to trigger stimulus actions without the need for checking the actual event details.

```html
<div data-controller='modal' data-action='turbo:submit-success->modal#close'>...</div>
vs.
<div data-controller='modal' data-action='turbo:submit-end->modal#closeOnSuccessfulFormSubmission'>...</div>
```

@dhh What are your thoughts on this?

Also: I am willing to help implementing that feature.

**Comment by davidalejandroaguilar** [comment]
@seanpdoyle @dhh  Would you consider @matthee's suggestion? (separating `turbo:submit-success` and `turbo:submit-end`)

Also, I might be missing where, but `turbo:submit-end` is not present in any documentation, right? If so, I can add it.
