### ISSUE TITLE
Make progress bar finish on `turbo:load`

### ISSUE THREAD

**Issue by fritzmg** [hotwired/turbo#962]
We have one page that takes not very long to transmit (low TTFB) but very long to render in the browser. This provides confusing UX when using Turbo as the progress bar indicates that the page has finished loading, but the content isn't actually shown for a long time after that.

Is there any way to make the progress bar actually finish when the `turbo:load` event fires? Rather than when `turbo:before-render` fires (which is roughly what happens now).

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/1036 to change this behavior.
