### ISSUE TITLE
Preloader does not use FetchRequest and therefore does not trigger events

### ISSUE THREAD

**Issue by sascha-egerer** [hotwired/turbo#963]
When using [`data-turbo-preload`](https://turbo.hotwired.dev/handbook/drive#preload-links-into-the-cache) the FetchRequest implementation is not used but a native fetch(). See https://github.com/hotwired/turbo/blob/c0b6bb6b321e918fc062ba7c5df935fe859a6899/src/core/drive/preloader.ts#L45

So the preload function will not trigger any events and is therefore useless in some cases e.g. if fetchOptions are set in `turbo:before-fetch-request`

Expected behavior: Preload function should trigger fetch events like `turbo:before-fetch-request`

**Comment by seanpdoyle** [comment]
Thank you for opening this issue! I've opened https://github.com/hotwired/turbo/pull/1034 to implement this behavior, and I've opened https://github.com/hotwired/turbo-site/pull/151 to document it.
