### ISSUE TITLE
Link to a stream and advance the URL

### ISSUE THREAD

**Issue by trsteel88** [hotwired/turbo#965]
I know it's possible to link to a stream by using <a href="/foo" data-turbo-stream>

However, doing so means the URL doesn't update (even with data-turbo-action="advance"

In my example /foo will handle a normal request and a stream. This means if we navigate there with a stream and the user refreshes, it still works. 

Is there a way to achieve this?

I have also tried using the target as a turbo frame with a data-turbo-action advance and then forcing that turbo frame to be a stream request. However, the stream works but it doesn't advance.

**Comment by mathieumahe** [comment]
I'm wondering the same thing. Have you find a way to achieve that ? 

Thanks!

**Comment by tannakartikey** [comment]
One way to achieve is to use Stimulus controller and respond with HTML that triggers this Stimulus controller. The controller can than perform `Turbo.visit`
