### ISSUE TITLE
Update the html lang attribute

### ISSUE THREAD

**Issue by jmsche** [hotwired/turbo#967]
Hi,

In an application, I have the `lang` attribute set on the  `<html>` tag.
When the user switches the locale, the body is changed with Turbo.
However, the `lang` attribute is not updated by Turbo, and some of my JavaScript relies on this attribute to use the correct locale.

I know that I could either add an event listener listening to a Turbo event to update the attribute, or trigger a full page refresh instead.

Would it make sense for Turbo to also update the `lang` attribute by default instead of adding custom logic?

**Comment by seanpdoyle** [comment]
Turbo should probably monitor changes to the `<html>` element's `[lang]` attribute.

Until that support is baked in, applications that drive to pages with different `html[lang]` attributes should disable Turbo Drive for those mechanisms by annotating those `<a>` and `<form>` elements with `[data-turbo="false"]`, or by [requesting a full-page reload](https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload) by including `<meta name="turbo-visit-control" content="reload">` in the response.

**Comment by seanpdoyle** [comment]
I've opened https://github.com/hotwired/turbo/pull/1035 to implement this behavior.

**Comment by sedubois** [comment]
I came here after encountering this exact issue: the document's `lang` attribute stays stuck in the previous language when switching language. So for example this kind of CSS doesn't work until the page is reloaded: `html[lang="fr"] q { quotes: "« " " »"; }`.

Thank you so much @seanpdoyle for the PR.
