### ISSUE TITLE
Why are WS/SEE not being closed after turbo-stream-source is gone?

### ISSUE THREAD

**Issue by guillermo** [hotwired/turbo#969]
I am using Hotwired/Turbo in a go application. 
On one specific page, I want to update several partials from the server asynchronously as they arrive to the server through external apis (openAI in this case).

I used this on my views:

```html
<turbo-frame id="articles_list">
...
<turbo-stream-source src="/repurpose/{{ .ID }}/"></turbo-stream>
...
</turbo-frame>
```

It normally works as expected, and I can update the page nicely.

But the moment that I navigate to another page (so the turbo-stream-source gets unloaded), the ws/see connection is ignored but not closed.

https://github.com/hotwired/turbo/blob/0826b8152c0e97f19d459c1a1c364fa89cc62829/src/elements/stream_source_element.ts#L14-L16

This creates unlimited connections until I reach the browsers max, and can't navigate anymore.

I fixed it locally by modifying the source and manually closing the connection with `this.streamSource.close();`: 

```javascript
class StreamSourceElement extends HTMLElement {
...
    disconnectedCallback() {
        if (this.streamSource) {
            disconnectStreamSource(this.streamSource);
            this.streamSource.close();
        }
    }
...
}
```

The change seems obvious for my use case, but makes me wonder if I am using hotwire turbo as design.

Are only fixed constant connections like `/cable` in rails the only recommended use case?

**Comment by seanpdoyle** [comment]
Thank you for opening this issue, and for sharing your solution.

I've opened https://github.com/hotwired/turbo/pull/970 to resolve it.

**Comment by kwhandy** [comment]
is this issue causing response on network tab which keep receives `{"type":"ping","message":Id}`, even after we move to another page which doesn't have `turbo-stream-source` tag in it? if yes, it's still happening right now cuz i just upgrade mine to v8 @seanpdoyle @guillermo 

rails 7.1.3
turbo 8.0.0
turbo-rails 2.0.0
