### ISSUE TITLE
Missing TypeScript typings 

### ISSUE THREAD

**Issue by Mati365** [hotwired/turbo#975]
After building the package from the source code, TypeScript typing is missing. Is there any plan to add updated typings to https://github.com/DefinitelyTyped/tsd?

**Comment by jt3k** [comment]
this language gets in the way of development and makes things that should be simple difficult. The additional compilation stage and gymnastics with types only worsen the situation.  In addition, neural networks are increasingly breaking into our lives, and in the end typescript will be supplanted by them. Don't resist, just relax and have fun.
