### ISSUE TITLE
Go back to Typescript

### ISSUE THREAD

**Issue by ghost** [hotwired/turbo#978]
Not liking typing is like a surgeon saying he doesn't like Scalpels. It is a tool that is needed. You are lazy at best, and everyone in favor of this change should really reconsider their job. 

If you want to create spaghetti, do it in your personal projects. Here in the real world we need clean code.

**Comment by DASPRiD** [comment]
At least adding JSDoc to not lose any type information (and maybe providing d.ts files) would have alleviated some issues.

**Comment by TechStudent10** [comment]
I agree, some people prefer to work with types. At least give them the option :/

**Comment by DASPRiD** [comment]
Also, having JSDoc in place would allow to a) still have static type checking in CI as well as b) allowing to generate `d.ts` files out for release (supported as of TS 3.7).

**Comment by almokhtarbr** [comment]
If you don't like it, fork it and move on !

**Comment by craigmiller160** [comment]
Damn. I had never heard of this project before, and now I will never consider using it. You're really screwing this project over by rejecting TS. First, your code quality will massively suffer. Second, the entire TS community, which is slowly absorbing the JS community, will ignore you.

Maybe you have outdated personal preferences, but you're screwing over your whole project for it.

**Comment by almokhtarbr** [comment]
@craigmiller160 
**This is the problem people have nothing to do with hotwire coming and giving why you should and you must use typescript**

**Comment by Qodestackr** [comment]
Let the project be what it is, 🙂✍️
