### ISSUE TITLE
thank u for removing that stupid ts here some alternative 

### ISSUE THREAD

**Issue by xalteropsx** [hotwired/turbo#987]
![image](https://github.com/hotwired/turbo/assets/103671642/593eb63a-3cc9-4c02-aa7a-ae92101aa867)

or with jsdocs annoation

**Comment by darnfish** [comment]
Lol <1 line of `: HTMLInputElement` now turned into two lines, good job

**Comment by 0xF7A4C6** [comment]
lmao

**Comment by malarahfelipe** [comment]
**at least** some jsdoc annotations, also would enforce ppl to write more comments about the absurdities they'll (read as we'll) eventually write

Now without anything, better to switch back to old php (prior to v7 - dec 2015) or old python (prior to v3.5 - sep 2015)

nice 2014 move @dhh 😅
