### ISSUE TITLE
Update readme to explain what this project about

### ISSUE THREAD

**Issue by vitonsky** [hotwired/turbo#995]
Hey, let's improve readme to explain what problems this project solves.

As [i have mentioned or reddit](https://www.reddit.com/r/programming/comments/16e6ijh/comment/jzul1up/), it is not clear from readme what this project do.

I propose to improve readme and answer there on questions
- What this project about? Short description in one paragraph with no marketing wording
- What problems this project solves? Why i may want to need your tool
- What another solutions of the problem exists and why your solution better?

Imagine that you don't know nothing about this project and try to explain yourself why you may need the tool

**Comment by dhh** [comment]
Feel free to propose improvements with a PR.
