### ISSUE TITLE
We should have some basic guarantees of types, rather than killing off it all

### ISSUE THREAD

**Issue by stevefan1999-personal** [hotwired/turbo#999]
This has never been a strong/dynamic/static typed language problem. 

It is about having the basic level of [design by contracts](https://en.wikipedia.org/wiki/Design_by_contract). Nobody want to have data/states that is chaotic and unpredictable, so it is logical why the computer scientists introduced types that you can assert this data should have those properties and expect to have predictable behaviors. This is just the first step. 

**Without types, then the source of truth for that data/variables/methods/states would not be bounded**. The shift to a pure Javascript project would essentially be no worse than treating everything as `any`. There won't be any guarantees about whether the data/variables/methods/states would absolutely be there when I need them.

So, as a defense, I have to place a lot of null/undefined guards everywhere just to be sure when I access something. Not only this impacts performance at a noticeable cost on large scale, since there would be a lot more unnecessary null-checks branches (which puts pressure on the [branch predictor](https://en.wikipedia.org/wiki/Branch_predictor)) and handling different type cases using `typeof` (all of which would be subjectable to [combinatorial explosion](https://en.wikipedia.org/wiki/Combinatorial_explosion)), but...

But the very fundamental problem is that the whole thing (everything; the whole architecture) becomes ad-hoc pretty quick because nobody is going to restrict you anymore, so you can take any shape or form, fire and forgot. 

Today I'm going to add this feature, and tomorrow I will break it down into different pieces. **All hell can break loose just because we don't have a fundamental trust, and types provided a basic level of trust I can assume**. 

Take for example, my extensions can break tomorrow just because of a simple change in method parameters, and after days of debugging I still scratches my head, and not until I proactively looked up the documentations for Turbo and see that, oh, there's a breaking change: the callback parameter in the API and the positions have changed. This happened to me before when I was doing [NodeBB](https://github.com/NodeBB/NodeBB) development, which is a pure JS forum software with extension supports. There is no red-highlight telling you the positions are wrong.

Do I really have to look up the documentations all the time just for a simple verification of such state-of-affairs?

So, to reiterate, at the end of the day, if we don't have types, then the burden of proofing/examination/[introspection](https://en.wikipedia.org/wiki/Type_introspection) is put down to the end developers. the best thing you can do, is an educated guess what that data/variables/states/method would do by looking up the name and praying that your code would work in the long run. If you are lucky then the documentations may tell you some information, but those are more of a high-level stuff.

I do understand that deducing the right types maybe hard, because [some smart people actually realized it is comparable to writing mathematical proofs](https://en.wikipedia.org/wiki/Curry%E2%80%93Howard_correspondence), and writing mathematical proofs are obviously hard, as most of us out here who have adequate CS educations, still recalled the horrors in discrete mathematics to write those logic proofs, statements and theorems, but the long-term benefits it brings, obviously outweighed the temporal headache it makes at the present.

Rich Harris set a very good premise for Svelte to convert all of the types to JSDoc, instead of killing of it all. That is a responsible compromise well-received by the community, because far as I can see, there are no booings and hooligans when the commitment to JSDoc for Svelte was made. There is existing code that turns TypeScript code to Javascript with JSDoc: [https://github.com/futurGH/ts-to-jsdoc.](https://github.com/futurGH/ts-to-jsdoc.) Maybe we should do the same.

###### Excuse my rudeness, but I never understood why dynamically typed languages like Javascript, Lua, Python and Ruby are so popular nowadays. Those are just toy languages we use to express algorithms and pseudocode (I got to admit I use Python for Leetcode, but I would NEVER choose Python as my main language) and should never been adopted to the software industry as a standard. The only explanation would be the [sunk cost](https://en.wikipedia.org/wiki/Sunk_cost) by all of those big tech companies who just wanted things quick and never thought about the consequences.

**Comment by afcapel** [comment]
> Excuse my rudeness, but I never understood why dynamically typed languages like Javascript, Lua, Python and Ruby are so popular nowadays. Those are just toy languages we use to express algorithms and pseudocode (I got to admit I use Python for Leetcode, but I would NEVER choose Python as my main language) and should never been adopted to the software industry as a standard. The only explanation would be the [sunk cost](https://en.wikipedia.org/wiki/Sunk_cost) by all of those big tech companies who just wanted things quick and never thought about the consequences.

I understand people can have different takes on this and no amount of discussion is going to settle the question. As a data point, at 37Signals we develop successful products that customers love, mostly using and enjoying dynamically typed languages. And we keep choosing dynamically typed languages like Ruby and JavaScript for new products because we really enjoy working with them.
